### ISSUE TITLE
Issue getting @pact-foundation/pact module to load 

### ISSUE THREAD

**Issue by AlisonYoon** [pact-foundation/pact-js#1086]
### Software versions
OS: Mac OS Ventura 13.3.1
Node version: 14.21.1
 @pact-foundation/pact: ^11.0.2
@pact-foundation/pact-core: ^13.13.4

### Issue Checklist

Please confirm the following:

- [ x] I have upgraded to the latest
- [ ]x I have the read the FAQs in the Readme
- [x ] I have triple checked, that there are **no unhandled promises** in my code and have [read](https://github.com/pact-foundation/pact-js/blob/master/docs/troubleshooting.md#test-fails-when-it-should-pass) the section on intermittent test failures
- [ ] I have set my log level to debug and attached a log file showing the complete request/response cycle
- [ ] For bonus points and virtual high fives, I have created a reproduceable git repository (see below) to illustrate the problem

### Expected behaviour

_fill in here_

### Actual behaviour
Pact testing failure with below error message.

```
  dlopen(/Users/alison.yoon/Developer/kraken-core/src/octoenergy/interfaces/node_modules/@pact-foundation/pact-core/build/Release/pact.node, 0x0001): Library not loaded: @rpath/libpact_ffi.dylib
      Referenced from: <409E86F7-030E-31C9-8506-0E6A80B0F755> /Users/alison.yoon/Developer/kraken-core/src/octoenergy/interfaces/node_modules/@pact-foundation/pact-core/build/Release/pact.node
      Reason: tried: '/Users/alison.yoon/Developer/kraken-core/src/octoenergy/interfaces/node_modules/@pact-foundation/pact-core/build/Release/libpact_ffi.dylib' (no such file), '/Users/alison.yoon/Developer/kraken-core/src/octoenergy/interfaces/node_modules/@pact-foundation/pact-core/build/Release/libpact_ffi.dylib' (no such file), '/usr/local/lib/libpact_ffi.dylib' (no such file), '/usr/lib/libpact_ffi.dylib' (no such file, not in dyld cache)

      at Runtime._loadModule (node_modules/jest-runtime/build/index.js:1180:29)
      at bindings (../../node_modules/bindings/bindings.js:112:48)
      at Object.<anonymous> (../../node_modules/@pact-foundation/pact-core/src/ffi/index.ts:6:21)
```
### Steps to reproduce
In Mac OS Ventural 13.3.1, in a project, install pact testing package, write some tests and run it.

**Comment by TimothyJones** [comment]
A few questions:

* Can you try removing node_modules and reinstalling?
* Do you get errors during a clean `npm install`? (and what are they)
* Are you using a different package manager (ie, other than `npm`)?

I have MacOS Ventura 13.3.1, and no trouble running Pact. Could you be more specific in your reproduction instructions?

**Comment by mefellows** [comment]
You can see the paths of the library it is trying to install.

```
      '/Users/alison.yoon/Developer/kraken-core/src/octoenergy/interfaces/node_modules/@pact-foundation/pact-core/build/Release/libpact_ffi.dylib' (no such file)
      '/usr/local/lib/libpact_ffi.dylib' (no such file)
      '/usr/lib/libpact_ffi.dylib' (no such file, not in dyld cache)
```

 It's interesting  that it's found (and compiled) the `pact.node` native interface, but hasn't found the library. I wonder if they are somehow installed in a different place. Are you running a monorepo by any chance and the root project is in `/Users/alison.yoon/Developer/kraken-core/`? 

Could you please run this command from that folder please: `find . -name libpact_ffi.dylib`

Also, could you please confirm if you're running from a Rosetta mode enabled? If not, I'd expect it to be loading a slightly different file.

**Comment by mefellows** [comment]
Closing due to inactivity.
