### ISSUE TITLE
Pact doesn't display the matcher errors when actual and expected requests are different

### ISSUE THREAD

**Issue by satishautade** [pact-foundation/pact-js#1113]
### Software versions

- **OS**:  Mac OSX 13.4.1
- **Consumer Pact library**:  Pact JS v3
- **Provider Pact library**:  N/A
- **Node Version**: v18.14.2

### Issue Checklist

Please confirm the following:

- [ ] I have upgraded to the latest
- [ ] I have the read the FAQs in the Readme
- [ ] I have triple checked, that there are **no unhandled promises** in my code and have [read](https://github.com/pact-foundation/pact-js/blob/master/docs/troubleshooting.md#test-fails-when-it-should-pass) the section on intermittent test failures
- [ ] I have set my log level to debug and attached a log file showing the complete request/response cycle
- [ ] For bonus points and virtual high fives, I have created a reproduceable git repository (see below) to illustrate the problem

### Expected behaviour

Log level INFO. When the actual consumer request is different from the request specified in pact mock provider, the pact should show useful error highlighting the mismatch. 

### Actual behaviour

Log level INFO. When the actual consumer request is different from the request specified in pact mock provider, the pact just fails without any useful information about the differences. 
```
[12:20:00.532] ERROR (97438): pact@12.1.0: Test failed for the following reasons:

  Mock server failed with the following mismatches:

	0) The following request was incorrect:

            	GET /dogs

 RUNS  __tests__/simple-example.pact.js

```

### Steps to reproduce

1. Clone this example repo https://github.com/satishautade/pact-bug 
2. Run npm install && npm test in the root directory of this project. 

### Relevant log files

Attached the log file of the same test by re-running it in DEBUG mode.
[pact-failure-debug-log.log](https://github.com/pact-foundation/pact-js/files/12531377/pact-failure-debug-log.log)

**Comment by mefellows** [comment]
Thanks so much for the repro - this will be very helpful!

**Comment by mefellows** [comment]
I had a quick look tonight. It's a curious one, the error message is being formatted correctly, but is being truncated (I think) by the logger.

If I add an adjacent log at level `info` it prints the whole thing (as does a `console.log`):

```
[22:00:32.797] INFO (88044): pact@12.1.0: Test failed for the following reasons:

  Mock server failed with the following mismatches yes sir re:

	0) The following request was incorrect:

            	GET /cats

			 1.0 Unexpected query parameter 'catId[]' received
[22:00:32.798] ERROR (88044): pact@12.1.0: Test failed for the following reasons:

  Mock server failed with the following mismatches yes sir re:

	0) The following request was incorrect:

            	GET /cats
```

That might help future me or somebody else get to the bottom of it.

**Comment by mefellows** [comment]
I think I have a fix for this - as I suspected, the issue to have been in Pino and the way it writes and buffers output.

With the fix, the full output is visible:

```
npm t

> pact-bug@1.0.0 test
> jest __tests__/ --runInBand

  console.log
    [22:27:38.170] INFO (6681): 0.4.7: pact native library successfully found, and the correct version

      at Object.write (node_modules/@pact-foundation/pact-core/src/logger/pino.ts:5:26)
          at Array.every (<anonymous>)


 RUNS  __tests__/simple-example.pact.js
  console.log
    [22:27:38.339] ERROR (6681): pact@12.1.0: Test failed for the following reasons:

      Mock server failed with the following mismatches:

    	0) The following request was incorrect:

                	GET /dogs

    			 1.0 Mismatch with header 'Host': Expected '127.0.0.1:8081' to be equal to 'localhost'

      at Object.write (node_modules/@pact-foundation/pact-core/src/logger/pino.ts:5:26)

  console.log
    [22:27:38.359] ERROR (6681): pact@12.1.0: Test failed for the following reasons:

      Mock server failed with the following mismatches:

    	0) The following request was expected but not received:
    	    Method: GET
    	    Path: /cats
    	    Query String: catId[]=1&catId[]=1
    	    Headers:
    	      Accept: application/json
```
