### ISSUE TITLE
Port XXXX is unavailable, run with Jest

### ISSUE THREAD

**Issue by dongxiaonan** [pact-foundation/pact-js#129]
I try to add consumer pact test in our project, which use Jest.

While run test, I met two errors as below:

```sh
Exception has occurred: Error
Error: Port XXXX is unavailable
    at Server.net.createServer.listen.on.err (c:\...\node_modules\pact\src\common\net.js:14:63)
    at emitOne (events.js:115:13)
    at Server.emit (events.js:210:7)
    at emitErrorNT (net.js:1339:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

Exception has occurred: TypeError
TypeError: Cannot read property 'addExpectationResult' of undefined
    at Env.fail (c:\...\node_modules\jest-jasmine2\build\jasmine\Env.js:510:24)
    at next.fail (c:\...\node_modules\jest-jasmine2\build\queue_runner.js:42:22)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

Could you help to show any clue about it?

Test code like this: 
```js
describe('Retrieve API Contract Test', () => {
   const port = 9123;
   const provider = Pact({
       port: port,
       log: path.resolve(process.cwd(), 'logs', 'contract-test.log'),
       dir: path.resolve(process.cwd(), 'pacts'),
       spec: 2,
       consumer: 'Consumer - Retrieve API',
       provider: 'Provider - Retrieve API',
   });
   const EXCEPTED_BODY = { name: "LIU", age: 20 };
    describe("Start to describe contract", () => {
        beforeEach((done) => {
            provider.setup()
            .then(() => {
                provider.addInteraction({
                    state: 'retrieve data',
                    uponReceiving: 'a request for projects',
                    withRequest: {
                        method: 'GET',
                        path: '/api/v1/retrieve',
                        query: {
                            name: Pact.Matchers.somethingLike('LIU')
                        },
                        headers: { 'Accept': 'application/json' }
                    },
                    willRespondWith: {
                        status: 200,
                        headers: { 'Content-Type': 'application/json' },
                        body: EXPECTED_BODY
                    }
                }).then(() => done())
            });
        });
        xit('should get booking data', async () => {
            const data = await API.callRetrieve({name: "LIU"});
            expect(data).toEqual(EXCEPTED_BODY);
        });
        it('successfully verifies', () => provider.verify());
        afterEach(() => { provider.finalize() });
    });
```

**Comment by mefellows** [comment]
Based on what you've provided, it seems that port `9123` is currently unavailable - did you start a server on that port?

Also, could you please complete the issue template so we know what version of things you're using?

Thanks.

**Comment by dongxiaonan** [comment]
Just find when to send the request, there mush have a port. thanks, I will close this ticket.
