### ISSUE TITLE
Can't require() module in 6.0.0-alpha.8

### ISSUE THREAD

**Issue by TomRK1089** [pact-foundation/pact-js#173]
## Software versions

* **OS**: Windows 7
* **Consumer Pact library**: Pact JS v6.0.0-alpha.8
* **Node Version**: `v8.9.4`

## Expected behaviour

I can run tests that import Pact like so:
```
const { Matchers, MessageConsumer, Message, synchronousBodyHandler } = require("@pact-foundation/pact");
```

## Actual behaviour

I get an error when invoking the test via Mocha:
```
Error: Cannot find module '../../package.json'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (<redacted>\node_modules\@pact-foundation\pact\common\logger.js:15:11)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (<redacted>\node_modules\@pact-foundation\pact\pact.js:28:16)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (<redacted>\test\mq-consumer.test.js:1:134)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at <redacted>\node_modules\mocha\lib\mocha.js:253:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (<redacted>\node_modules\mocha\lib\mocha.js:250:14)
    at Mocha.run (<redacted>node_modules\mocha\lib\mocha.js:577:10)
    at Object.<anonymous> (<redacted>\node_modules\mocha\bin\_mocha:591:18)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```
It looks like `@pact-foundation/pact/common/logger.js` is requiring `package.json` from the wrong relative location:
```
L15: var pkg = require("../../package.json");
```
Manually editing this in my `node_modules` to ../package.json allows the test to pass. Were directories reorganized that might have led to the changed path?

## Steps to reproduce

Run `mocha spec test` with...
test/mq-consumer.test.js:
```
const { Matchers, MessageConsumer, Message, synchronousBodyHandler } = require("@pact-foundation/pact");
const path = require("path");

const batchHandler = function() {
  return;//Dummy impl
};
const messagePact = new MessageConsumer({
  consumer: "FOO",
  provider: "BAR",
  dir: path.resolve(process.cwd(), "pacts")//Seems to be required even though .d.ts shows it as optional?
});
describe("the suite", function() {
  it("the test", function() {
    return messagePact.given("pre")
      .expectsToReceive("test")
      .withContent({ foo: "bar" })
      .verify(synchronousBodyHandler(batchHandler));
    });
});
```

**Comment by mefellows** [comment]
Thanks, I noticed this the other day also. Should be a simple one to fix, by converting to an absolute path and having a fallback.

PR welcome ;)

**Comment by mefellows** [comment]
This is fixed now, closing. Thanks @TomRK1089
