### ISSUE TITLE
Error with Typescript Pact.io test: PopsicleError: Unable to connect to

### ISSUE THREAD

**Issue by leongaban** [pact-foundation/pact-js#212]
## Software versions

* **OS**:  Mac OSX 10.13.6
* **Consumer Pact library**: e.g. Pact JS `^5.9.1`
* **Provider Pact library**: ? This wasn't specified in the JS guide
* **Node Version**:  Used both `v10.8.0` & `v8.11.4`

## Expected behaviour

Running npm run pactTest should generate a pact file (JSON).

## Actual behaviour

I get an Unable to connect error.

## Steps to reproduce

https://stackoverflow.com/questions/52410277/error-with-typescript-pact-io-test-popsicleerror-unable-to-connect-to

Appreciate any thoughts or ideas as to what I'm doing wrong :)

----------

**The Error**

>  FAIL  src/services/api/TotalPayout.test.pact.ts
  The API
    getUsersTotalPayout
      ✕ Should call getUsersTotalPayout and return an object with the total_payout (45ms)

>  ● The API › getUsersTotalPayout › Should call getUsersTotalPayout and return an object with the total_payout

>    PopsicleError: Unable to connect to "http://127.0.0.1:12345/interactions"
    Caused by: Error: connect ECONNREFUSED 127.0.0.1:12345

>      at Request.Object.<anonymous>.Request.error (node_modules/popsicle/src/request.ts:91:12)
      at ClientRequest.<anonymous> (node_modules/popsicle/src/index.ts:218:31)

**package.json script:**

    "pactTest": "export NODE_ENV=pactTest && jest --testRegex \"/*(.test.pact.ts)\" --runInBand --setupFiles ./pactSetup.ts --setupTestFrameworkScriptFile ./pactTestWrapper.ts",

**My src/pactSetup.ts file**

    // @ts-ignore
    import path from 'path';
    import { Pact } from '@pact-foundation/pact/pact';
    ​
    // @ts-ignore
    global.provider = new Pact({
      port: 1234,
      log: path.resolve(process.cwd(), 'logs', 'mockserver-integration.log'),
      dir: path.resolve(process.cwd(), 'pacts'),
      spec: 2,
      cors: true,
      pactfileWriteMode: 'update',
      consumer: 'Exchange',
      provider: 'LP Service'
    });

**My src/pactTestWrapper.ts**

    jasmine.DEFAULT_TIMEOUT_INTERVAL = 10000; // This is to give the pact mock server time to start
    ​
    // @ts-ignore
    beforeAll(() => provider.setup()); // Create mock provider
    // @ts-ignore
    afterEach(() => provider.verify()); // Ensure the mock provider verifies expected interactions for each test
    // @ts-ignore
    afterAll(() => provider.finalize()); // Tear down the mock and write the pact

**The test: src/services/api/TotalPayout.test.pact.ts**

    // @ts-ignore
    import path from 'path';
    import { Pact } from '@pact-foundation/pact';
    import { getTotalPayout } from './apiPayout';

    const port = 12345;
    const endpoint = '/frontoffice/api/get-total-payout';

    const EXPECTED_BODY = {
      total_payout: 100.21,
    };

    const userId = 'foo';

    const provider = new Pact({
      port,
      log: path.resolve(process.cwd(), 'logs', 'mockserver-integration.log'),
      dir: path.resolve(process.cwd(), 'pacts'),
      spec: 2,
      consumer: 'Exchange',
      provider: 'LP Service',
      pactfileWriteMode: 'merge'
    });
    ​​
    describe('The API', () => {
      // Copy this block once per interaction under test
      describe('getUsersTotalPayout', () => {
        beforeEach(() => {
          const interaction = {
            uponReceiving: 'a GET request with a user id',
            withRequest: {
              method: 'GET',
              path: endpoint,
              headers: {
                Accept: 'application/json',
              },
            },
            willRespondWith: {
              status: 200,
              headers: {
                'Content-Type': 'application/json'
              },
              body: EXPECTED_BODY
            },
          };

          // @ts-ignore
          return provider.addInteraction(interaction);
        });
    ​
        // add expectations
        it('Should call getUsersTotalPayout and return an object with the total_payout', done => {
          getTotalPayout(userId)
            .then((response: any) => {
              expect(response).toEqual(EXPECTED_BODY);
            })
            .then(done);
        });
      });
    });

**The api service file apiPayout.ts**

    // @ts-ignore
    import axios, * as others from 'axios';

    const endpoint = '/frontoffice/api/';

    export const getTotalPayout = async (userId: string) => {
      const response = await axios.get(`${endpoint}get-total-payout`, { params: userId });
      return response.data;
    };

**From the mockserver-integration.log**

    I, [2018-09-19T11:07:41.259437 #79922]  INFO -- : Verifying - interactions matched
    I, [2018-09-19T11:07:41.264440 #79922]  INFO -- : Cleared interactions

**From the debug-log**

    20 error code ELIFECYCLE
    21 error errno 1
    22 error react-redux-starter-kit@1.0.0 pactTest: `export NODE_ENV=pactTest && jest --testRegex "/*(.test.pact.ts)" --runInBand --setupFiles ./pactSetup.ts --setupTestFrameworkScriptFile ./pactTestWrapper.ts`
    22 error Exit status 1
    23 error Failed at the react-redux-starter-kit@1.0.0 pactTest script.

  [1]: https://docs.pact.io/implementation_guides/javascript
  [2]: https://github.com/pact-foundation/pact-js/blob/master/examples/typescript/test/get-dog.spec.ts

**Comment by leongaban** [comment]
Update, after removing the provider setup from my TotalPayout.test.pact.ts file it seems to be working better, still getting errors though:

> console.error node_modules/@pact-foundation/pact/pact.js:110
    Pact verification failed!
> console.error node_modules/@pact-foundation/pact/pact.js:111
    Actual interactions do not match expected interactions for mock MockService.
> Missing requests:
    	GET /frontoffice/api/liquidity-pool/get-total-payout

And the log file:

    I, [2018-09-19T14:12:19.128823 #82330]  INFO -- : Registered expected interaction GET /frontoffice/api/liquidity-pool/get-total-payout
    D, [2018-09-19T14:12:19.129127 #82330] DEBUG -- : {
      "description": "a GET request with a user id",
      "request": {
        "method": "GET",
        "path": "/frontoffice/api/liquidity-pool/get-total-payout",
        "headers": {
          "Accept": "application/json"
        }
      },
      "response": {
        "status": 200,
        "headers": {
          "Content-Type": "application/json"
        },
        "body": {
          "total_payout": 100.21
        }
      }
    }
    W, [2018-09-19T14:12:19.139198 #82330]  WARN -- : Verifying - actual interactions do not match expected interactions. 
    Missing requests:
    	GET /frontoffice/api/liquidity-pool/get-total-payout


    W, [2018-09-19T14:12:19.139254 #82330]  WARN -- : Missing requests:
    	GET /frontoffice/api/liquidity-pool/get-total-payout

**Comment by leongaban** [comment]
Closing since the current error no longer happens. Will post a new issue if the other error can't be resolved.
