### ISSUE TITLE
Jest/babel compilation error with v7

### ISSUE THREAD

**Issue by czebe** [pact-foundation/pact-js#230]
I've upgraded to v7 and my tests are failing to run now.
I tried adjusting `.babelrc` as well as Jest config `transformIgnorePatterns`, but nothing seems to help the compilation.

(The Jest example in your repo is also failing, but with a different error, so I couldn't confirm if it's working at all with Jest).

```
import { Source } from './source';
    ^^^^^^

    SyntaxError: Unexpected token import

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:403:17)
      at node_modules/graphql-tag/lib/graphql-tag.umd.js:7:14
      at node_modules/graphql-tag/lib/graphql-tag.umd.js:2:65
      at Object.<anonymous> (node_modules/graphql-tag/lib/graphql-tag.umd.js:5:2)
```

**Comment by czebe** [comment]
I cloned the repo, `npm install`-ed the dependencies in `/examples/jest` then try to run `npm test` and it errors out with:

```
 FAIL  __tests__/multipleSpecs.spec.js
  ● Test suite failed to run

    Couldn't find preset "es2015" relative to directory "/Users/czebe/Work/pact-js"

      at node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
          at Array.map (<anonymous>)
```

**Comment by mefellows** [comment]
Ah, you will need to do an `npm install` in the root of the project also.

**Comment by mefellows** [comment]
How did you go @czebe ?
