### ISSUE TITLE
@pact-foundation/pact-node should be a direct dependency

### ISSUE THREAD

**Issue by travi** [pact-foundation/pact-js#25]
or at least a peer-dependency instead of just a devDependency

https://github.com/pact-foundation/pact-js/search?utf8=%E2%9C%93&q=pact-node shows multiple usages under `src/`.  if my project does not define `@pact-foundation/pact-node` as a dependency in addition to `pact`, i get the following error:

```
module.js:472
    throw err;
    ^

Error: Cannot find module '@pact-foundation/pact-node'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/path/to/my/project/node_modules/pact/src/dsl/verifier.js:8:24)
    at Module._compile (module.js:571:32)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .js] (/path/to/my/project/node_modules/babel-cli/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
```

**Comment by mefellows** [comment]
See also #26.

**Comment by mefellows** [comment]
OK `v2.0.1` is released that should sort this one out. I've pushed a test e2e repository (disconnected from main project to ensure no relative path funny business) to https://github.com/mefellows/pact-js-example should you want to test.

**Comment by travi** [comment]
Looks good on my end. Thanks for the quick resolution. In case it is helpful, I use an [eslint rule](https://github.com/benmosher/eslint-plugin-import/blob/b5a962f6c80d0e0ec71a895a603e8e8096292f0e/docs/rules/no-extraneous-dependencies.md) to protect my projects from this issue.

**Comment by mefellows** [comment]
Thanks Matt, I'll add this in.
