### ISSUE TITLE
cli-color should be a direct dependency

### ISSUE THREAD

**Issue by travi** [pact-foundation/pact-js#26]
`cli-color` is used by `src/pact.js`, but is only marked as a `devDependency`, resulting in the following error:

```
Error: Cannot find module 'cli-color'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/path/to/my/project/node_modules/pact/src/pact.js:17:13)
    at Module._compile (module.js:571:32)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .js] (/path/to/my/project/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
```

**Comment by mefellows** [comment]
Most of the dependencies in pact-js are part of `devDependencies` because they are not required for any runtime operation.

How are you running this?

**Comment by travi** [comment]
So far, i haven't gotten very deep, but i don't think I'm far off from what is suggested in the readme. My script is public here: https://github.com/travi/travi.org-admin/blob/master/scripts/pact.js

**Comment by mefellows** [comment]
Sorry, I just updated my comment - looking into this @travi.

**Comment by mefellows** [comment]
As per #25, `v2.0.1` is released and should sort this one out. I've pushed a test e2e repository (disconnected from main project to ensure no relative path funny business) to https://github.com/mefellows/pact-js-example should you want to test.
