### ISSUE TITLE
Could not load existing consumer contract from "contract/file/path" due to undefined method `gsub' for nil:NilClass. Creating a new file.

### ISSUE THREAD

**Issue by asadzaheer** [pact-foundation/pact-js#279]
## Software versions

* **OS**:  Windows 10
* **Consumer Pact library**:  Pactjs 8.0.2
* **Node Version**:  11.2.0
* **Js test library**:  jest 24.1.0

## Expected behaviour

Provider test should pass

## Actual behaviour

When i run provider test i am getting following error

```
$ npm run test:provider

> render-service@1.0.0 test:provider C:\xampp\htdocs\render-service
> jest --testRegex "/*(provider.test.pact.js)" --runInBand --setupFiles ./tests/config/pactSetup.js --setupTestFrameworkScriptFile=./tests/config/pactTestWrapper.js

[2019-03-07T10:14:23.616Z]  INFO: pact-node@6.21.5/3360 on DESKTOP-KOB10PR:
    Creating Pact Server with options:
    consumer = render,
    cors = false,
    dir = C:\xampp\htdocs\render-service\pacts,
    host = 127.0.0.1,
    log = C:\xampp\htdocs\render-service\pact logs\pact-tests.log,
    pactFileWriteMode = update,
    port = 8991,
    provider = prestac,
    spec = 2,
    ssl = false,
    sslcert = ,
    sslkey =
FAIL tests/provider.test.pact.js (6.689s)
  Message provider tests
    send a render message
      × sends a valid render message (2046ms)

  ● Message provider tests › send a render message › sends a valid render message

    INFO: Reading pact at /xampp/htdocs/render-service/pacts/render-prestac.json


    Verifying a pact between render and prestac
      Given message is valid
        a request for rendering

          has matching content (FAILED - 1)


    Failures:

      1) Verifying a pact between render and prestac Given message is valid a request for rendering has matching content
         Failure/Error: raise "An error was raised while verifying the message.The response body is: #{response.body}"

         RuntimeError:
           An error was raised while verifying the message. The response body is: {}


    1 interaction, 1 failure

    Failed interactions:


    * A request for rendering given message is valid


      at ChildProcess.<anonymous> (node_modules/@pact-foundation/pact-node/src/verifier.ts:172:57)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        10.63s
Ran all test suites.
Jest did not exit one second after the test run has completed.

This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
```

Pact log file

```
W, [2019-03-07T12:19:48.394818 #17152]  WARN -- : Could not load existing consumer contract from C:/xampp/htdocs/render-service/pacts/render-prestac.json due to undefined method `gsub' for nil:NilClass. Creating a new file.
E, [2019-03-07T12:19:48.394818 #17152] ERROR -- : undefined method `gsub' for nil:NilClass (NoMethodError)
C:/xampp/htdocs/render-service/node_modules/@pact-foundation/pact-node/standalone/win32-1.63.0/lib/vendor/ruby/2.2.0/gems/pact-support-1.8.1/lib/pact/consumer_contract/consumer_contract.rb:62:in `maintain_backwards_compatiblity_with_producer_keys'
C:/xampp/htdocs/render-service/node_modules/@pact-foundation/pact-node/standalone/win32-1.63.0/lib/vendor/ruby/2.2.0/gems/pact-support-1.8.1/lib/pact/consumer_contract/consumer_contract.rb:51:in `from_json'
C:/xampp/htdocs/render-service/node_modules/@pact-foundation/pact-node/standalone/win32-1.63.0/lib/vendor/ruby/2.2.0/gems/pact-mock_service-2.12.0/lib/pact/consumer_contract/consumer_contract_writer.rb:122:in `existing_consumer_contract'
C:/xampp/htdocs/render-service/node_modules/@pact-foundation/pact-node/standalone/win32-1.63.0/lib/vendor/ruby/2.2.0/gems/pact-mock_service-2.12.0/lib/pact/consumer_contract/consumer_contract_writer.rb:98:in `existing_interactions'
C:/xampp/htdocs/render-service/node_modules/@pact-foundation/pact-node/standalone/win32-1.63.0/lib/vendor/ruby/2.2.0/gems/pact-mock_service-2.12.0/lib/pact/consumer_contract/consumer_contract_writer.rb:85:in `interactions_for_new_consumer_contract'
C:/xampp/htdocs/render-service/node_modules/@pact-foundation/pact-node/standalone/win32-1.63.0/lib/vendor/ruby/2.2.0/gems/pact-mock_service-2.12.0/lib/pact/consumer_contract/consumer_contract_writer.rb:37:in `consumer_contract'
C:/xampp/htdocs/render-service/node_modules/@pact-foundation/pact-node/standalone/win32-1.63.0/lib/vendor/ruby/2.2.0/gems/pact-mock_service-2.12.0/lib/pact/consumer_contract/consumer_contract_writer.rb:80:in `decorated_pact'
C:/xampp/htdocs/render-service/node_modules/@pact-foundation/pact-node/standalone/win32-1.63.0/lib/vendor/ruby/2.2.0/gems/pact-mock_service-2.12.0/lib/pact/consumer_contract/consumer_contract_writer.rb:76:in `pact_json'
C:/xampp/htdocs/render-service/node_modules/@pact-foundation/pact-node/standalone/win32-1.63.0/lib/vendor/ruby/2.2.0/gems/pact-mock_service-2.12.0/lib/pact/consumer_contract/consumer_contract_writer.rb:42:in `write'
C:/xampp/htdocs/render-service/node_modules/@pact-foundation/pact-node/standalone/win32-1.63.0/lib/vendor/ruby/2.2.0/gems/pact-mock_service-2.12.0/lib/pact/mock_service/request_handlers/pact_post.rb:33:in `respond'
C:/xampp/htdocs/render-service/node_modules/@pact-foundation/pact-node/standalone/win32-1.63.0/lib/vendor/ruby/2.2.0/gems/pact-mock_service-2.12.0/lib/pact/mock_service/request_handlers/base_request_handler.rb:17:in `call'
C:/xampp/htdocs/render-service/node_modules/@pact-foundation/pact-node/standalone/win32-1.63.0/lib/vendor/ruby/2.2.0/gems/rack-2.0.6/lib/rack/cascade.rb:33:in `block in call'
C:/xampp/htdocs/render-service/node_modules/@pact-foundation/pact-node/standalone/win32-1.63.0/lib/vendor/ruby/2.2.0/gems/rack-2.0.6/lib/rack/cascade.rb:24:in `each'
C:/xampp/htdocs/render-service/node_modules/@pact-foundation/pact-node/standalone/win32-1.63.0/lib/vendor/ruby/2.2.0/gems/rack-2.0.6/lib/rack/cascade.rb:24:in `call'
C:/xampp/htdocs/render-service/node_modules/@pact-foundation/pact-node/standalone/win32-1.63.0/lib/vendor/ruby/2.2.0/gems/pact-mock_service-2.12.0/lib/pact/consumer/mock_service/cors_origin_header_middleware.rb:11:in `call'
C:/xampp/htdocs/render-service/node_modules/@pact-foundation/pact-node/standalone/win32-1.63.0/lib/vendor/ruby/2.2.0/gems/pact-mock_service-2.12.0/lib/pact/consumer/mock_service/error_handler.rb:13:in `call'
C:/xampp/htdocs/render-service/node_modules/@pact-foundation/pact-node/standalone/win32-1.63.0/lib/vendor/ruby/2.2.0/gems/pact-mock_service-2.12.0/lib/pact/mock_service/app.rb:33:in `call'
C:/xampp/htdocs/render-service/node_modules/@pact-foundation/pact-node/standalone/win32-1.63.0/lib/vendor/ruby/2.2.0/gems/pact-mock_service-2.12.0/lib/pact/consumer/mock_service/set_location.rb:14:in `call'
C:/xampp/htdocs/render-service/node_modules/@pact-foundation/pact-node/standalone/win32-1.63.0/lib/vendor/ruby/2.2.0/gems/rack-2.0.6/lib/rack/handler/webrick.rb:86:in `service'
C:/xampp/htdocs/render-service/node_modules/@pact-foundation/pact-node/standalone/win32-1.63.0/lib/vendor/ruby/2.2.0/gems/webrick-1.3.1/lib/webrick/httpserver.rb:138:in `service'
C:/xampp/htdocs/render-service/node_modules/@pact-foundation/pact-node/standalone/win32-1.63.0/lib/vendor/ruby/2.2.0/gems/webrick-1.3.1/lib/webrick/httpserver.rb:94:in `run'
C:/xampp/htdocs/render-service/node_modules/@pact-foundation/pact-node/standalone/win32-1.63.0/lib/vendor/ruby/2.2.0/gems/webrick-1.3.1/lib/webrick/server.rb:191:in `block in start_thread'
E, [2019-03-07T12:19:48.395820 #17152] ERROR -- : ["C:/xampp/htdocs/render-service/node_modules/@pact-foundation/pact-node/standalone/win32-1.63.0/lib/vendor/ruby/2.2.0/gems/pact-support-1.8.1/lib/pact/consumer_contract/consumer_contract.rb:62:in `maintain_backwards_compatiblity_with_producer_keys'", "C:/xampp/htdocs/render-service/node_modules/@pact-foundation/pact-node/standalone/win32-1.63.0/lib/vendor/ruby/2.2.0/gems/pact-support-1.8.1/lib/pact/consumer_contract/consumer_contract.rb:51:in `from_json'", "C:/xampp/htdocs/render-service/node_modules/@pact-foundation/pact-node/standalone/win32-1.63.0/lib/vendor/ruby/2.2.0/gems/pact-mock_service-2.12.0/lib/pact/consumer_contract/consumer_contract_writer.rb:122:in `existing_consumer_contract'", "C:/xampp/htdocs/render-service/node_modules/@pact-foundation/pact-node/standalone/win32-1.63.0/lib/vendor/ruby/2.2.0/gems/pact-mock_service-2.12.0/lib/pact/consumer_contract/consumer_contract_writer.rb:98:in `existing_interactions'", "C:/xampp/htdocs/render-service/node_modules/@pact-foundation/pact-node/standalone/win32-1.63.0/lib/vendor/ruby/2.2.0/gems/pact-mock_service-2.12.0/lib/pact/consumer_contract/consumer_contract_writer.rb:85:in `interactions_for_new_consumer_contract'", "C:/xampp/htdocs/render-service/node_modules/@pact-foundation/pact-node/standalone/win32-1.63.0/lib/vendor/ruby/2.2.0/gems/pact-mock_service-2.12.0/lib/pact/consumer_contract/consumer_contract_writer.rb:37:in `consumer_contract'", "C:/xampp/htdocs/render-service/node_modules/@pact-foundation/pact-node/standalone/win32-1.63.0/lib/vendor/ruby/2.2.0/gems/pact-mock_service-2.12.0/lib/pact/consumer_contract/consumer_contract_writer.rb:80:in `decorated_pact'", "C:/xampp/htdocs/render-service/node_modules/@pact-foundation/pact-node/standalone/win32-1.63.0/lib/vendor/ruby/2.2.0/gems/pact-mock_service-2.12.0/lib/pact/consumer_contract/consumer_contract_writer.rb:76:in `pact_json'", "C:/xampp/htdocs/render-service/node_modules/@pact-foundation/pact-node/standalone/win32-1.63.0/lib/vendor/ruby/2.2.0/gems/pact-mock_service-2.12.0/lib/pact/consumer_contract/consumer_contract_writer.rb:42:in `write'", "C:/xampp/htdocs/render-service/node_modules/@pact-foundation/pact-node/standalone/win32-1.63.0/lib/vendor/ruby/2.2.0/gems/pact-mock_service-2.12.0/lib/pact/mock_service/request_handlers/pact_post.rb:33:in `respond'", "C:/xampp/htdocs/render-service/node_modules/@pact-foundation/pact-node/standalone/win32-1.63.0/lib/vendor/ruby/2.2.0/gems/pact-mock_service-2.12.0/lib/pact/mock_service/request_handlers/base_request_handler.rb:17:in `call'", "C:/xampp/htdocs/render-service/node_modules/@pact-foundation/pact-node/standalone/win32-1.63.0/lib/vendor/ruby/2.2.0/gems/rack-2.0.6/lib/rack/cascade.rb:33:in `block in call'", "C:/xampp/htdocs/render-service/node_modules/@pact-foundation/pact-node/standalone/win32-1.63.0/lib/vendor/ruby/2.2.0/gems/rack-2.0.6/lib/rack/cascade.rb:24:in `each'", "C:/xampp/htdocs/render-service/node_modules/@pact-foundation/pact-node/standalone/win32-1.63.0/lib/vendor/ruby/2.2.0/gems/rack-2.0.6/lib/rack/cascade.rb:24:in `call'", "C:/xampp/htdocs/render-service/node_modules/@pact-foundation/pact-node/standalone/win32-1.63.0/lib/vendor/ruby/2.2.0/gems/pact-mock_service-2.12.0/lib/pact/consumer/mock_service/cors_origin_header_middleware.rb:11:in `call'", "C:/xampp/htdocs/render-service/node_modules/@pact-foundation/pact-node/standalone/win32-1.63.0/lib/vendor/ruby/2.2.0/gems/pact-mock_service-2.12.0/lib/pact/consumer/mock_service/error_handler.rb:13:in `call'", "C:/xampp/htdocs/render-service/node_modules/@pact-foundation/pact-node/standalone/win32-1.63.0/lib/vendor/ruby/2.2.0/gems/pact-mock_service-2.12.0/lib/pact/mock_service/app.rb:33:in `call'", "C:/xampp/htdocs/render-service/node_modules/@pact-foundation/pact-node/standalone/win32-1.63.0/lib/vendor/ruby/2.2.0/gems/pact-mock_service-2.12.0/lib/pact/consumer/mock_service/set_location.rb:14:in `call'", "C:/xampp/htdocs/render-service/node_modules/@pact-foundation/pact-node/standalone/win32-1.63.0/lib/vendor/ruby/2.2.0/gems/rack-2.0.6/lib/rack/handler/webrick.rb:86:in `service'", "C:/xampp/htdocs/render-service/node_modules/@pact-foundation/pact-node/standalone/win32-1.63.0/lib/vendor/ruby/2.2.0/gems/webrick-1.3.1/lib/webrick/httpserver.rb:138:in `service'", "C:/xampp/htdocs/render-service/node_modules/@pact-foundation/pact-node/standalone/win32-1.63.0/lib/vendor/ruby/2.2.0/gems/webrick-1.3.1/lib/webrick/httpserver.rb:94:in `run'", "C:/xampp/htdocs/render-service/node_modules/@pact-foundation/pact-node/standalone/win32-1.63.0/lib/vendor/ruby/2.2.0/gems/webrick-1.3.1/lib/webrick/server.rb:191:in `block in start_thread'"]
```

consumer test that is generating pact
```
const {
  MessageConsumerPact,
  asynchronousBodyHandler,
} = require('@pact-foundation/pact');

const path = require('path');

const { validateMessage } = require('./../render');

const msg = {
  identifier: {},
  body: {
    projectId: 538481,
    projectPath: 'C:/xampp/htdocs/render-service/538481.aep',
    movPath: 'C:/xampp/htdocs/render-service/538481.mov',
    mp4Path: 'C:/xampp/htdocs/render-service/538481.mp4',
  },
};

describe('Message consumer tests', () => {
  const messagePact = new MessageConsumerPact({
    consumer: 'render',
    dir: path.resolve(process.cwd(), 'pacts'),
    pactfileWriteMode: 'update',
    provider: 'prestac',
    logLevel: 'fatal',
  });

  describe('Receive a valid message for rendering', () => {
    it('Process rendering', () => messagePact
      .given('message is valid')
      .expectsToReceive('a request for rendering')
      .withContent(msg)
      .verify(asynchronousBodyHandler(validateMessage)), 600000);
  });
});
```

contract/pact that is generated 
```
{
  "consumer": {
    "name": "render"
  },
  "provider": {
    "name": "prestac"
  },
  "messages": [
    {
      "description": "a request for rendering",
      "providerStates": [
        {
          "name": "message is valid",
          "params": null
        }
      ],
      "contents": {
        "identifier": {
        },
        "body": {
          "projectId": 1,
          "projectPath": "path",
          "movPath": "path",
          "mp4Path": "path"
        }
      },
      "matchingRules": {
        "body": {
        }
      },
      "metaData": {
      }
    }
  ],
  "metadata": {
    "pactSpecification": {
      "version": "3.0.0"
    }
  }
}
```

**Comment by mefellows** [comment]
Hi @asadzaheer, your language is confusing here as you mention both provider and consumer tests.

Can I just confirm:

1. your consumer test above is working, and is producing the contract above?
2. The Provider Verification is failing, when _reading_ this pact file?

Lastly, if it is indeed the provider test that is failing, please provide the test.

FWIW I've just taken that pact file, and run it against the messages example in this repository (modifying the example to send back your data) and it works just fine, including on Windows.

**Comment by mefellows** [comment]
FYI here is the relevant passing message test on AppVeyor: https://ci.appveyor.com/project/pact-foundation/pact-js/build/job/5uryi4w36xxbabu9#L3937

**Comment by mefellows** [comment]
I'm beginning to think that perhaps your provider code is not running at all (or is not returning anything), and therefore is not sending a body. The error message is certainly unhelpful, however.

**Comment by asadzaheer** [comment]
1. Yes its working and producing the contract mentioned above (following is output i get when i run consumer test).
```
> render-service@1.0.0 test:consumer C:\xampp\htdocs\render-service
> jest --testRegex "/*(consumer.test.pact.js)" --runInBand --setupFiles ./tests/config/pactSetup.js --setupTestFrameworkScriptFile=./tests/config/pactTestWrapper.js

[2019-03-11T11:02:59.558Z]  INFO: pact-node@6.21.5/11592 on DESKTOP-KOB10PR: 
    Creating Pact Server with options: 
    consumer = render,
    cors = false,
    dir = C:\xampp\htdocs\render-service\pacts,
    host = 127.0.0.1,
    log = C:\xampp\htdocs\render-service\pact logs\pact-tests.log,
    pactFileWriteMode = update,
    port = 8991,
    provider = prestac,
    spec = 2,
    ssl = false,
    sslcert = ,
    sslkey = 
[2019-03-11T11:03:03.378Z]  INFO: pact@8.0.2/11592 on DESKTOP-KOB10PR:
    Setting up Pact with Consumer "render" and Provider "prestac"
        using mock service on Port: "8991"
[2019-03-11T11:03:03.380Z]  INFO: pact@8.0.2/11592 on DESKTOP-KOB10PR: Verifying message
[2019-03-11T11:03:05.103Z]  INFO: pact@8.0.2/11592 on DESKTOP-KOB10PR: Pact File Written
 PASS  tests/consumer.test.pact.js (6.7s)
  Message consumer tests
    Receive a valid message for rendering
      √ Process rendering (1700ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        11.021s
Ran all test suites.
```

2. I am not sure about that part i mentioned the output and logs i get when i run provider test.

3. Following is my provider test (forgot to mention in initial post)
provider test
```
const { MessageProviderPact } = require('@pact-foundation/pact');
const path = require('path');
const { getMsg } = require('./../mock-prestac');

describe('Message provider tests', () => {
  const messagePact = new MessageProviderPact({
    messageProviders: {
      'a request for rendering': () => getMsg(),
    },
    log: path.resolve(process.cwd(), 'logs'),
    provider: 'prestac',
    providerVersion: '1.0.0',
    logLevel: 'fatal',
    },

    // For local validation
    pactUrls: [
      path.resolve(process.cwd(), 'pacts', 'render-prestac.json'),
    ],
   
  });

  describe('send a render message', () => {
    it('sends a valid render message', () => messagePact.verify(), 60000);
  });
});
```

and mock-prestac is as follow 
```
const getMsg = function getMsg() {
  return new Promise(resolve => resolve({
    identifier: {},
    body: {
      projectId: 538481,
      projectPath: 'C:/xampp/htdocs/render-service/538481.aep',
      movPath: 'C:/xampp/htdocs/render-service/538481.mov',
      mp4Path: 'C:/xampp/htdocs/render-service/538481.mp4',
    },
  }));
};

module.exports = getMsg;
```

**Comment by asadzaheer** [comment]
> FYI here is the relevant passing message test on AppVeyor: https://ci.appveyor.com/project/pact-foundation/pact-js/build/job/5uryi4w36xxbabu9#L3937

so i guess issue is in my code only difference is i am using jest not mocha

> I'm beginning to think that perhaps your provider code is not running at all (or is not returning anything), and therefore is not sending a body. The error message is certainly unhelpful, however.

hmm can you suggest or help on how i can debugg this issue? @mefellows 

and in error while running provider tests there is line which shows body is empty 

``` 
RuntimeError:
           An error was raised while verifying the message. The response body is: {}
```

**Comment by mefellows** [comment]
Hi Asad, apologies for the delay. I've just updated the repro branch with your `getMsg` function. 

I get the following expected error:

```
Failures:

  1) Verifying a pact between render and prestac Given message is valid a request for rendering has matching content
     Failure/Error: expect(actual_contents).to match_term expected_contents, diff_options, example

       Actual: {"body":{"movPath":"C:/xampp/htdocs/render-service/538481.mov","mp4Path":"C:/xampp/htdocs/render-service/538481.mp4","projectId":538481,"projectPath":"C:/xampp/htdocs/render-service/538481.aep"},"identifier":{}}

       Diff
       --------------------------------------
       Key: - is expected
            + is actual
       Matching keys and values are not shown

        {
          "body": {
       -    "projectId": 1,
       -    "projectPath": "path",
       -    "movPath": "path",
       -    "mp4Path": "path"
       +    "projectId": 538481,
       +    "projectPath": "C:/xampp/htdocs/render-service/538481.aep",
       +    "movPath": "C:/xampp/htdocs/render-service/538481.mov",
       +    "mp4Path": "C:/xampp/htdocs/render-service/538481.mp4"
          }
        }

       Description of differences
       --------------------------------------
       * Expected 1 but got 538481 at $.body.projectId
       * Expected "path" but got "C:/xampp/htdocs/render-service/538481.aep" at $.body.projectPath
       * Expected "path" but got "C:/xampp/htdocs/render-service/538481.mov" at $.body.movPath
       * Expected "path" but got "C:/xampp/htdocs/render-service/538481.mp4" at $.body.mp4Path


1 interaction, 1 failure

Failed interactions:

* A request for rendering given message is valid
```

The error is expected, because in your consumer test you have expected the value of each property to be _exactly_ `path`, and not use any matchers.

To match based on type, checkout the Matchers section of the README.

To progress this issue, could you please create (by either modifying my branch or creating a new one) an example that reproduces your issue directly? 

> so i guess issue is in my code only difference is i am using jest not mocha

Yes, this may be the case. If you could create a repo with your version of Jest etc., that will help us narrow in on the issue.

**Comment by asadzaheer** [comment]
Hi Matt, i checked the changes you did in [issue-279](https://github.com/pact-foundation/pact-js/tree/repro/issue-279) , there was no msg-client.ts file but i copied the code of dog-client.ts ( it was removed in this [commit](https://github.com/pact-foundation/pact-js/commit/85619007884bc1036f687186e6802b344aa03b55) ) and renamed it to msg-client.ts and than run `npm run test:provider` in messages directory (did npm I in root and messages directory as-well ) got the following error 

```
> pact-message-example@1.0.0 test:provider C:\xampp\htdocs\pact-js\examples\messages
> nyc --check-coverage --reporter=html --reporter=text-summary mocha -t 10000 provider/*.spec.ts



(node:6668) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
  Message provider tests
    send a render message
      1) sends a valid render message


  0 passing (2s)
  1 failing

  1) Message provider tests send a render message sends a valid render message:
     Error: INFO: Reading pact at /xampp/htdocs/pact-js/examples/messages/myjsmessageconsumer-myjsmessageprovider.json


Verifying a pact between render and prestac
  Given message is valid
    a request for rendering

WARN: Skipping set up for provider state 'message is valid' for consumer 'render' as there is no --provider-states-setup-url specified.

      has matching content (FAILED - 1)


Failures:

  1) Verifying a pact between render and prestac Given message is valid a request for rendering has matching content
     Failure/Error: raise "An error was raised while verifying the message. Theresponse body is: #{response.body}"

     RuntimeError:
       An error was raised while verifying the message. The response body is: {}


1 interaction, 1 failure

Failed interactions:


* A request for rendering given message is valid



      at ChildProcess.<anonymous> (C:\xampp\htdocs\pact-js\node_modules\@pact-foundation\pact-node\src\verifier.ts:172:57)
      at maybeClose (internal/child_process.js:978:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
```

But i was able to find issue why my provider test was returning empty response body, it was a small and stupid mistake from me 😞.
i was importing the `getMsg` as `const { getMsg } = require('../mock-prestac');`
where i was exporting it as `module.exports = getMsg;`. changing it to `const getMsg  = require('../mock-prestac');` made the test green.

you can close this issue now, because above problem is some different issue i guess? 


on a side note are you testing it on windows 10 environment?  also i noticed you linked issue 271 while commiting code in issue 279 branch (was confusing for me if its related to my issue or not 😄  )

**Comment by mefellows** [comment]
Oh dear, yes I did get those wires crossed a bit - apologies!

Anyhow, good to see you got it sorted :)
