### ISSUE TITLE
Option providerBaseUrl is not propagated

### ISSUE THREAD

**Issue by Filipoliko** [pact-foundation/pact-js#337]
## Software versions

* **OS**: Windows 7
* **Consumer Pact library**: @pact-foundation/pact v9.0.1
* **Provider Pact library**: @pact-foundation/pact v9.0.1
* **Node Version**: 10.16.0

## Expected behaviour
Option `providerBaseUrl` should set provider base url.

## Actual behaviour
Whatever I put in `providerBaseUrl` option, it is changed to `http://localhost:<randomPort>`.

## Steps to reproduce
verifier.js
```javascript
const path = require('path');
const { Verifier } = require('@pact-foundation/pact');
let opts = {
    providerBaseUrl: 'https://api.thecatapi.com',
    pactUrls: [
        path.join(process.cwd(), 'pacts/cat-api-cat.json')
    ]
};

new Verifier(opts)
    .verifyProvider()
    .then(() => console.log('Success!'))
    .catch(e => {
        console.error(e);
        process.exit(1);
    });
```

pacts/cat-api-cat.json
```json
{
  "consumer": {
    "name": "cat"
  },
  "provider": {
    "name": "api-cat"
  },
  "interactions": [
    {
      "description": "get cat",
      "request": {
        "method": "GET",
        "path": "/v1/images/search",
        "headers": {
          "Accept": "application/json"
        }
      },
      "response": {
        "status": 200,
        "headers": {
          "Content-Type": "application/json; charset=utf-8"
        },
        "body": [
            {
            "id": "7ph",
            "url": "https://cdn2.thecatapi.com/images/7ph.jpg",
            "width": 640,
            "height": 427
          }
        ],
        "matchingRules": {
          "$.body": {
            "min": 1
          },
          "$.body[*].*": {
            "match": "type"
          },
          "$.body[*].id": {
            "match": "type"
          },
          "$.body[*].url": {
            "match": "type"
          },
          "$.body[*].width": {
            "match": "type"
          },
          "$.body[*].height": {
            "match": "type"
          }
        }
      }
    }
  ],
  "metadata": {
    "pactSpecification": {
      "version": "2.0.0"
    }
  }
}
```

Now run `node verifier.js` and see the results.

## Relevant log files
```
[2019-07-29T12:36:41.808Z]  INFO: pact@9.0.1/15464 on BRN-Satek: Verifying provider
[2019-07-29T12:36:41.829Z]  INFO: pact-node@9.0.0/15464 on BRN-Satek: Verifying Pacts.
[2019-07-29T12:36:41.835Z]  INFO: pact-node@9.0.0/15464 on BRN-Satek: Verifying Pact Files
[2019-07-29T12:36:41.858Z]  INFO: pact-node@9.0.0/15464 on BRN-Satek: Created 'standalone\win32-1.69.0\bin\pact-provider-verifier.bat '/Seznam/skeletonx/admin/pacts/cat-api-cat.json' --provider-states-setup-url 'http://localhost:52400/_pactSetup' --provider-base-url 'http://localhost:52400'' process with PID: 14132
[2019-07-29T12:36:44.070Z]  WARN: pact@9.0.1/15464 on BRN-Satek: No state handler found for "null", ignorning
C:\Seznam\skeletonx\admin\node_modules\http-proxy\lib\http-proxy\index.js:120
    throw err;
    ^

Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: Host: localhost. is not in the cert's altnames: DNS:thecatapi.com, DNS:*.thecatapi.com
    at Object.checkServerIdentity (tls.js:239:17)
    at TLSSocket.onConnectSecure (_tls_wrap.js:1065:27)
    at TLSSocket.emit (events.js:198:13)
    at TLSSocket._finishInit (_tls_wrap.js:633:8)
```

Note, that `[2019-07-29T12:36:41.858Z]  INFO: pact-node@9.0.0/15464 on BRN-Satek: Created 'standalone\win32-1.69.0\bin\pact-provider-verifier.bat '/Seznam/skeletonx/admin/pacts/cat-api-cat.json' --provider-states-setup-url 'http://localhost:52400/_pactSetup' --provider-base-url 'http://localhost:52400'' process with PID: 14132` actually sends `--provider-base-url 'http://localhost:52400'`, even though we have `providerBaseUrl` set to `https://api.thecatapi.com`.

**Comment by mefellows** [comment]
As mentioned in your PR, please look at `changeOrigin` and set to true. I'll  look to merge in #319 soon to simplify this, but would appreciate your feedback on that PR if it help solve _your_ issue.

**Comment by MarkConway94** [comment]
Hi, we are seeing this issue with our provider test running in an azure pipeline. 
We have set the providerBaseUrl in the options passed in to the new Verifier but a random localhost seems to be used in the pipeline
Here is a console.log of the options we are passing in to create the Verifier
```
  console.log
    ### opts {
      provider: 'MyProvider',
      providerBaseUrl: 'https://www.myprovider.com',
      pactBrokerUrl: 'http://my-pactbroker.com',
      publishVerificationResult: true,
      providerVersion: '1.0',
      timeout: 600000,
      changeOrigin: true,
      logLevel: 'debug',
      verbose: true,
      requestFilter: [AsyncFunction: requestFilter]
    }
```
And here is the error we see, as you can see the only option that we pass in that changes is the providerBaseUrl
```
[2022-01-21 10:04:59.467 +0000] INFO (1230 on ip-x-x-x-x.us-east-2.compute.internal): pact@9.17.2: Verifying provider
[2022-01-21 10:04:59.475 +0000] INFO (1230 on ip-x-x-x-x.us-east-2.compute.internal): pact@9.17.2: debug request/response logging enabled
[2022-01-21 10:04:59.479 +0000] INFO (1230 on ip-x-x-x-x.us-east-2.compute.internal): pact-node@10.17.1: Verifying Pacts.
[2022-01-21 10:04:59.481 +0000] INFO (1230 on ip-x-x-x-x.us-east-2.compute.internal): pact-node@10.17.1: Verifying Pact Files
[2022-01-21 10:04:59.483 +0000] DEBUG (1230 on ip-x-x-x-x.us-east-2.compute.internal): pact-node@10.17.1: Starting pact binary '/usr/bin/myagent/_work/4/s/services/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.88.81/pact/bin/pact-provider-verifier', with arguments [--provider-states-setup-url http://localhost:33403/_pactSetup --provider MyProvider --provider-base-url http://localhost:33403 --pact-broker-base-url http://my-pactbroker.com --publish-verification-results true --provider-app-version 1.0 --log-level debug --verbose true]
[2022-01-21 10:04:59.521 +0000] DEBUG (1230 on ip-x-x-x-x.us-east-2.compute.internal): pact-node@10.17.1: Created '/usr/bin/myagent/_work/4/s/services/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.88.81/pact/bin/pact-provider-verifier' process with PID: undefined
[2022-01-21 10:04:59.522 +0000] ERROR (1230 on ip-x-x-x-x.us-east-2.compute.internal): pact-node@10.17.1: 
    errno: -2
    code: "ENOENT"
    syscall: "spawn /usr/bin/myagent/_work/4/s/services/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.88.81/pact/bin/pact-provider-verifier"
    path: "/usr/bin/myagent/_work/4/s/services/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.88.81/pact/bin/pact-provider-verifier"
    spawnargs: [
      "--provider-states-setup-url",
      "http://localhost:33403/_pactSetup",
      "--provider",
      "MyProvider",
      "--provider-base-url",
      "http://localhost:33403",
      "--pact-broker-base-url",
      "http://my-pactbroker.com",
      "--publish-verification-results",
      "true",
      "--provider-app-version",
      "1.0",
      "--log-level",
      "debug",
      "--verbose",
      "true"
    ]
[2022-01-21 10:04:59.525 +0000] WARN (1230 on ip-x-x-x-x.us-east-2.compute.internal): pact-node@10.17.1: Pact exited with code -2.
```
I've tried setting `changeOrigin` as was mentioned in this thread but that didn't seem to have any effect.

Any other ideas?
Thanks,
Mark
