### ISSUE TITLE
Intermittent consumer test failure when pactfileWriteMode = 'update'

### ISSUE THREAD

**Issue by tristanHessell** [pact-foundation/pact-js#346]
## Software versions

* **OS**: e.g. Ubuntu 18.04.2 MATE 1.20.1
* **Consumer Pact library**: @pact-foundation/pact v9.1.0
* **Provider Pact library**: 
* **Node Version**: v11.15.0
* **Jest Version**: v24.7.1
I am running these tests through jest using `jest <blob for tests> --runInBand`.

## Expected behaviour

The tests to consistently pass (or consistently fail!).

## Actual behaviour

- The tests will intermittently fail, with the error as seen in the logs.
- Its never the same test that fails.
- The error only seems to occur when `pactfileWriteMode: 'update'` - when using `merge` the tests appear to be consistently passing.

## Steps to reproduce
With 
```javascript
new Pact({
  consumer: 'SpotifyListApp',
  provider: 'SpotifyListService',
  port: 5000,
  log: path.resolve(process.cwd(), 'logs', 'pact.log'),
  dir: path.resolve(process.cwd(), 'src/tests', 'pact'),
  logLevel: 'DEBUG',
  pactfileWriteMode: 'update',
});
```
Running tests with jest as specified above.

## Relevant log files

```
I, [2019-08-21T01:20:30.300691 #18941]  INFO -- : Received request GET /playlist/BLAH
D, [2019-08-21T01:20:30.300962 #18941] DEBUG -- : {
  "path": "/playlist/BLAH",
  "query": "",
  "method": "get",
  "headers": {
    "Accept": "application/json",
    "Accept-Encoding": "gzip,deflate",
    "User-Agent": "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)",
    "Connection": "close",
    "Host": "localhost:5000",
    "Version": "HTTP/1.1"
  }
}
E, [2019-08-21T01:20:30.301062 #18941] ERROR -- : No matching interaction found for GET /playlist/BLAH
E, [2019-08-21T01:20:30.301116 #18941] ERROR -- : Interaction diffs for that route:
I, [2019-08-21T01:20:30.304615 #18941]  INFO -- : Registered expected interaction GET /playlist/BLAH
E, [2019-08-21T01:20:30.304777 #18941] ERROR -- : 
D, [2019-08-21T01:20:30.305379 #18941] DEBUG -- : {
  "description": "a request for a playlist",
  "providerState": "a playlist",
  "request": {
    "method": "GET",
    "path": "/playlist/BLAH",
    "headers": {
      "Accept": "application/json"
    }
  },
  "response": {
    "status": 200,
    "headers": {
      "Content-Type": "application/json; charset=utf-8"
    },
    "body": {
      "id": "BLAH",
      "url": "",
      "name": "PLAYLIST NAME",
      "description": "hello description is me",
      "songs": [
        {
          "id": "01",
          "artists": [
            {
              "id": 1,
              "name": "Gus Dapperton"
            },
            {
              "id": 2,
              "name": "Miley Cyrus"
            }
          ],
          "name": "Hello name 1"
        },
        {
          "id": "02",
          "artists": [
            {
              "id": 1,
              "name": "Gus Dapperton"
            },
            {
              "id": 2,
              "name": "Miley Cyrus"
            }
          ],
          "name": "Hello name 2"
        }
      ]
    }
  }
}
W, [2019-08-21T01:20:30.316634 #18941]  WARN -- : Verifying - actual interactions do not match expected interactions. 
Missing requests:
	GET /playlist/BLAH

Unexpected requests:
	GET /playlist/BLAH


W, [2019-08-21T01:20:30.316700 #18941]  WARN -- : Missing requests:
	GET /playlist/BLAH

Unexpected requests:
	GET /playlist/BLAH


I, [2019-08-21T01:20:30.324142 #18941]  INFO -- : Cleared interactions
W, [2019-08-21T01:20:30.339222 #18941]  WARN -- : Could not load existing consumer contract from /home/thessell/repos/spotify-list/src/tests/pact/spotifylistapp-spotifylistservice.json due to 757: unexpected token at 'null'. Creating a new file.
E, [2019-08-21T01:20:30.339286 #18941] ERROR -- : 757: unexpected token at 'null' (JSON::ParserError)
/home/thessell/repos/spotify-list/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.69.0/lib/vendor/ruby/2.2.0/gems/json-2.2.0/lib/json/common.rb:156:in `parse'
/home/thessell/repos/spotify-list/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.69.0/lib/vendor/ruby/2.2.0/gems/json-2.2.0/lib/json/common.rb:156:in `parse'
/home/thessell/repos/spotify-list/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.69.0/lib/vendor/ruby/2.2.0/gems/json-2.2.0/lib/json/common.rb:335:in `load'
/home/thessell/repos/spotify-list/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.69.0/lib/vendor/ruby/2.2.0/gems/pact-support-1.11.0/lib/pact/consumer_contract/consumer_contract.rb:51:in `from_json'
/home/thessell/repos/spotify-list/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.69.0/lib/vendor/ruby/2.2.0/gems/pact-mock_service-3.1.1/lib/pact/consumer_contract/consumer_contract_writer.rb:122:in `existing_consumer_contract'
/home/thessell/repos/spotify-list/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.69.0/lib/vendor/ruby/2.2.0/gems/pact-mock_service-3.1.1/lib/pact/consumer_contract/consumer_contract_writer.rb:98:in `existing_interactions'
/home/thessell/repos/spotify-list/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.69.0/lib/vendor/ruby/2.2.0/gems/pact-mock_service-3.1.1/lib/pact/consumer_contract/consumer_contract_writer.rb:85:in `interactions_for_new_consumer_contract'
/home/thessell/repos/spotify-list/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.69.0/lib/vendor/ruby/2.2.0/gems/pact-mock_service-3.1.1/lib/pact/consumer_contract/consumer_contract_writer.rb:37:in `consumer_contract'
/home/thessell/repos/spotify-list/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.69.0/lib/vendor/ruby/2.2.0/gems/pact-mock_service-3.1.1/lib/pact/consumer_contract/consumer_contract_writer.rb:80:in `decorated_pact'
/home/thessell/repos/spotify-list/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.69.0/lib/vendor/ruby/2.2.0/gems/pact-mock_service-3.1.1/lib/pact/consumer_contract/consumer_contract_writer.rb:76:in `pact_json'
/home/thessell/repos/spotify-list/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.69.0/lib/vendor/ruby/2.2.0/gems/pact-mock_service-3.1.1/lib/pact/consumer_contract/consumer_contract_writer.rb:42:in `write'
/home/thessell/repos/spotify-list/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.69.0/lib/vendor/ruby/2.2.0/gems/pact-mock_service-3.1.1/lib/pact/mock_service/request_handlers/pact_post.rb:33:in `respond'
/home/thessell/repos/spotify-list/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.69.0/lib/vendor/ruby/2.2.0/gems/pact-mock_service-3.1.1/lib/pact/mock_service/request_handlers/base_request_handler.rb:17:in `call'
/home/thessell/repos/spotify-list/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.69.0/lib/vendor/ruby/2.2.0/gems/rack-2.0.7/lib/rack/cascade.rb:33:in `block in call'
/home/thessell/repos/spotify-list/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.69.0/lib/vendor/ruby/2.2.0/gems/rack-2.0.7/lib/rack/cascade.rb:24:in `each'
/home/thessell/repos/spotify-list/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.69.0/lib/vendor/ruby/2.2.0/gems/rack-2.0.7/lib/rack/cascade.rb:24:in `call'
/home/thessell/repos/spotify-list/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.69.0/lib/vendor/ruby/2.2.0/gems/pact-mock_service-3.1.1/lib/pact/consumer/mock_service/cors_origin_header_middleware.rb:11:in `call'
/home/thessell/repos/spotify-list/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.69.0/lib/vendor/ruby/2.2.0/gems/pact-mock_service-3.1.1/lib/pact/consumer/mock_service/error_handler.rb:13:in `call'
/home/thessell/repos/spotify-list/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.69.0/lib/vendor/ruby/2.2.0/gems/pact-mock_service-3.1.1/lib/pact/mock_service/app.rb:33:in `call'
/home/thessell/repos/spotify-list/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.69.0/lib/vendor/ruby/2.2.0/gems/pact-mock_service-3.1.1/lib/pact/consumer/mock_service/set_location.rb:14:in `call'
/home/thessell/repos/spotify-list/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.69.0/lib/vendor/ruby/2.2.0/gems/rack-2.0.7/lib/rack/handler/webrick.rb:86:in `service'
/home/thessell/repos/spotify-list/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.69.0/lib/vendor/ruby/2.2.0/gems/webrick-1.3.1/lib/webrick/httpserver.rb:138:in `service'
/home/thessell/repos/spotify-list/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.69.0/lib/vendor/ruby/2.2.0/gems/webrick-1.3.1/lib/webrick/httpserver.rb:94:in `run'
/home/thessell/repos/spotify-list/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.69.0/lib/vendor/ruby/2.2.0/gems/webrick-1.3.1/lib/webrick/server.rb:191:in `block in start_thread'
E, [2019-08-21T01:20:30.339458 #18941] ERROR -- : ["/home/thessell/repos/spotify-list/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.69.0/lib/vendor/ruby/2.2.0/gems/json-2.2.0/lib/json/common.rb:156:in `parse'", "/home/thessell/repos/spotify-list/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.69.0/lib/vendor/ruby/2.2.0/gems/json-2.2.0/lib/json/common.rb:156:in `parse'", "/home/thessell/repos/spotify-list/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.69.0/lib/vendor/ruby/2.2.0/gems/json-2.2.0/lib/json/common.rb:335:in `load'", "/home/thessell/repos/spotify-list/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.69.0/lib/vendor/ruby/2.2.0/gems/pact-support-1.11.0/lib/pact/consumer_contract/consumer_contract.rb:51:in `from_json'", "/home/thessell/repos/spotify-list/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.69.0/lib/vendor/ruby/2.2.0/gems/pact-mock_service-3.1.1/lib/pact/consumer_contract/consumer_contract_writer.rb:122:in `existing_consumer_contract'", "/home/thessell/repos/spotify-list/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.69.0/lib/vendor/ruby/2.2.0/gems/pact-mock_service-3.1.1/lib/pact/consumer_contract/consumer_contract_writer.rb:98:in `existing_interactions'", "/home/thessell/repos/spotify-list/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.69.0/lib/vendor/ruby/2.2.0/gems/pact-mock_service-3.1.1/lib/pact/consumer_contract/consumer_contract_writer.rb:85:in `interactions_for_new_consumer_contract'", "/home/thessell/repos/spotify-list/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.69.0/lib/vendor/ruby/2.2.0/gems/pact-mock_service-3.1.1/lib/pact/consumer_contract/consumer_contract_writer.rb:37:in `consumer_contract'", "/home/thessell/repos/spotify-list/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.69.0/lib/vendor/ruby/2.2.0/gems/pact-mock_service-3.1.1/lib/pact/consumer_contract/consumer_contract_writer.rb:80:in `decorated_pact'", "/home/thessell/repos/spotify-list/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.69.0/lib/vendor/ruby/2.2.0/gems/pact-mock_service-3.1.1/lib/pact/consumer_contract/consumer_contract_writer.rb:76:in `pact_json'", "/home/thessell/repos/spotify-list/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.69.0/lib/vendor/ruby/2.2.0/gems/pact-mock_service-3.1.1/lib/pact/consumer_contract/consumer_contract_writer.rb:42:in `write'", "/home/thessell/repos/spotify-list/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.69.0/lib/vendor/ruby/2.2.0/gems/pact-mock_service-3.1.1/lib/pact/mock_service/request_handlers/pact_post.rb:33:in `respond'", "/home/thessell/repos/spotify-list/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.69.0/lib/vendor/ruby/2.2.0/gems/pact-mock_service-3.1.1/lib/pact/mock_service/request_handlers/base_request_handler.rb:17:in `call'", "/home/thessell/repos/spotify-list/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.69.0/lib/vendor/ruby/2.2.0/gems/rack-2.0.7/lib/rack/cascade.rb:33:in `block in call'", "/home/thessell/repos/spotify-list/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.69.0/lib/vendor/ruby/2.2.0/gems/rack-2.0.7/lib/rack/cascade.rb:24:in `each'", "/home/thessell/repos/spotify-list/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.69.0/lib/vendor/ruby/2.2.0/gems/rack-2.0.7/lib/rack/cascade.rb:24:in `call'", "/home/thessell/repos/spotify-list/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.69.0/lib/vendor/ruby/2.2.0/gems/pact-mock_service-3.1.1/lib/pact/consumer/mock_service/cors_origin_header_middleware.rb:11:in `call'", "/home/thessell/repos/spotify-list/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.69.0/lib/vendor/ruby/2.2.0/gems/pact-mock_service-3.1.1/lib/pact/consumer/mock_service/error_handler.rb:13:in `call'", "/home/thessell/repos/spotify-list/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.69.0/lib/vendor/ruby/2.2.0/gems/pact-mock_service-3.1.1/lib/pact/mock_service/app.rb:33:in `call'", "/home/thessell/repos/spotify-list/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.69.0/lib/vendor/ruby/2.2.0/gems/pact-mock_service-3.1.1/lib/pact/consumer/mock_service/set_location.rb:14:in `call'", "/home/thessell/repos/spotify-list/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.69.0/lib/vendor/ruby/2.2.0/gems/rack-2.0.7/lib/rack/handler/webrick.rb:86:in `service'", "/home/thessell/repos/spotify-list/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.69.0/lib/vendor/ruby/2.2.0/gems/webrick-1.3.1/lib/webrick/httpserver.rb:138:in `service'", "/home/thessell/repos/spotify-list/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.69.0/lib/vendor/ruby/2.2.0/gems/webrick-1.3.1/lib/webrick/httpserver.rb:94:in `run'", "/home/thessell/repos/spotify-list/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.69.0/lib/vendor/ruby/2.2.0/gems/webrick-1.3.1/lib/webrick/server.rb:191:in `block in start_thread'"]
```
---

My suspicions is that there is a race condition around `existing_interactions` in `consumer_contract_writer.rb` (pact-foundation/pact-mock_service), but I my ruby proficiency is not at the standard of to get any further

**Comment by mefellows** [comment]
Hi @tristanHessell, the entries into the pact log  are quite suspicious

There is a request (what should be in your `it` [test] block) to `GET /playlist/BLAH` before the interaction is registered, so I'm almost certain it has nothing to do with the update mode.

My suspicion is that there is a promise that is not being properly returned/`await`ed in a setup/before block somewhere, and your test is occasionally beating the setup  call.

i.e. I'm expecting to see something like t his in your code:

```js
before(() => {
   provider.setup(...) // <- no  return here, may or may not happen before the test itself
})

it('does something with a playlist', async () => {
   const playlists = await fetchPlaylists() // <- makes a call to  GET /playlist/BLAH, occasionally races the before()
})
````

If you have code to share, that would help.

**Comment by tristanHessell** [comment]
@mefellows you are correct - I wasn't returning the promise in the `beforeEach` block so jest wasn't waiting for the `addInteration` call to finish.

I guess all those times it passed was due to some (un)lucky timing with the stack and/or the microtask queue.

```javascript
beforeEach(async () => {
  await provider.setup();
  provider.addInteraction({ // <- missing return here
    state: 'a list of playlists',
    uponReceiving: 'a request for playlists',
    withRequest: {
      method: 'GET',
      path: '/playlists',
      headers: { Accept: 'application/json' },
    },
    willRespondWith: {
      status: 200,
      headers: { 'Content-Type': 'application/json; charset=utf-8' },
      body: EXPECTED_BODY,
    },
  });
});
```
---
Thanks for the help!

**Comment by mefellows** [comment]
👍 no dramas, glad that was it!
