### ISSUE TITLE
Error executing tests

### ISSUE THREAD

**Issue by leonleo997** [pact-foundation/pact-js#369]
Hello I'm trying to execute a test that used to work but now it is not working. Can you help me to discover the reason of fail?
These are my dependencies
    "@pact-foundation/karma-pact": "^2.2.0",
    "@pact-foundation/pact": "^9.0.0",
    "@pact-foundation/pact-web": "^9.0.0",
I'm using karma + jasmine
I attached the log after execute my test

[output.txt](https://github.com/pact-foundation/pact-js/files/3682485/output.txt)

**Comment by leonleo997** [comment]
yarn run v1.17.3
$ ng run clarifi-core-ui:contract --browsers ChromeCodeBuildCi
[[37m2019-10-02T17:32:13.199Z[39m] [36m INFO[39m: pact-node@9.0.4/23532 on YLOPEZS: 
[90m    [36mCreating Pact Server with options: 
    {"cors":true,"port":1234,"dir":"C:\\Users\\ylopezs\\git\\Loan-Logics\\dummy-project-core\\clarifi-core-ui\\test\\00-contract\\pacts","spec":2,"pactFileWriteMode":"overwrite","ssl":false,"host":"localhost"}[39m
[39m[[37m2019-10-02T17:32:13.225Z[39m] [36m INFO[39m: pact-node@9.0.4/23532 on YLOPEZS: [36mCreated 'standalone\win32-1.70.2\bin\pact-mock-service.bat service --cors 'true' --port '1234' --pact_dir 'C:\Users\ylopezs\git\Loan-Logics\dummy-project-core\clarifi-core-ui\test\00-contract\pacts' --pact_specification_version '2' --pact-file-write-mode 'overwrite' --host 'localhost'' process with PID: 26112[39m
[[37m2019-10-02T17:32:17.720Z[39m] [31mERROR[39m: pact-node@9.0.4/23532 on YLOPEZS: 
[90m    [36mPact Binary Error: C:/Users/ylopezs/git/Loan-Logics/dummy-project-core/clarifi-core-ui/node_modules/@pact-foundation/pact-node/standalone/win32-1.70.2/lib/vendor/ruby/2.2.0/gems/pact-mock_service-3.1.1/lib/pact/mock_service/request_handlers/interaction_post.rb:1:in `require': cannot load such file -- pact/mock_service/request_handlers/base_administration_request_handler (LoadError)
    	from C:/Users/ylopezs/git/Loan-Logics/dummy-project-core/clarifi-core-ui/node_modules/@pact-foundation/pact-node/standalone/win32-1.70.2/lib/vendor/ruby/2.2.0/gems/pact-mock_service-3.1.1/lib/pact/mock_service/request_handlers/interaction_post.rb:1:in `<top (required)>'
    	from C:/Users/ylopezs/git/Loan-Logics/dummy-project-core/clarifi-core-ui/node_modules/@pact-foundation/pact-node/standalone/win32-1.70.2/lib/vendor/ruby/2.2.0/gems/pact-mock_service-3.1.1/lib/pact/mock_service/request_handlers.rb:1:in `require'
    	from C:/Users/ylopezs/git/Loan-Logics/dummy-project-core/clarifi-core-ui/node_modules/@pact-foundation/pact-node/standalone/win32-1.70.2/lib/vendor/ruby/2.2.0/gems/pact-mock_service-3.1.1/lib/pact/mock_service/request_handlers.rb:1:in `<top (required)>'
    	from C:/Users/ylopezs/git/Loan-Logics/dummy-project-core/clarifi-core-ui/node_modules/@pact-foundation/pact-node/standalone/win32-1.70.2/lib/vendor/ruby/2.2.0/gems/pact-mock_service-3.1.1/lib/pact/mock_service/app.rb:6:in `require'
    	from C:/Users/ylopezs/git/Loan-Logics/dummy-project-core/clarifi-core-ui/node_modules/@pact-foundation/pact-node/standalone/win32-1.70.2/lib/vendor/ruby/2.2.0/gems/pact-mock_service-3.1.1/lib/pact/mock_service/app.rb:6:in `<top (required)>'
    	from C:/Users/ylopezs/git/Loan-Logics/dummy-project-core/clarifi-core-ui/node_modules/@pact-foundation/pact-node/standalone/win32-1.70.2/lib/vendor/ruby/2.2.0/gems/pact-mock_service-3.1.1/lib/pact/mock_service/run.rb:2:in `require'
    	from C:/Users/ylopezs/git/Loan-Logics/dummy-project-core/clarifi-core-ui/node_modules/@pact-foundation/pact-node/standalone/win32-1.70.2/lib/vendor/ruby/2.2.0/gems/pact-mock_service-3.1.1/lib/pact/mock_service/run.rb:2:in `<top (required)>'
    	from C:/Users/ylopezs/git/Loan-Logics/dummy-project-core/clarifi-core-ui/node_modules/@pact-foundation/pact-node/standalone/win32-1.70.2/lib/vendor/ruby/2.2.0/gems/pact-mock_service-3.1.1/lib/pact/mock_service/cli.rb:33:in `require'
    	from C:/Users/ylopezs/git/Loan-Logics/dummy-project-core/clarifi-core-ui/node_modules/@pact-foundation/pact-node/standalone/win32-1.70.2/lib/vendor/ruby/2.2.0/gems/pact-mock_service-3.1.1/lib/pact/mock_service/cli.rb:33:in `service'
    	from C:/Users/ylopezs/git/Loan-Logics/dummy-project-core/clarifi-core-ui/node_modules/@pact-foundation/pact-node/standalone/win32-1.70.2/lib/vendor/ruby/2.2.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
    	from C:/Users/ylopezs/git/Loan-Logics/dummy-project-core/clarifi-core-ui/node_modules/@pact-foundation/pact-node/standalone/win32-1.70.2/lib/vendor/ruby/2.2.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
    	from C:/Users/ylopezs/git/Loan-Logics/dummy-project-core/clarifi-core-ui/node_modules/@pact-foundation/pact-node/standalone/win32-1.70.2/lib/vendor/ruby/2.2.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
    	from C:/Users/ylopezs/git/Loan-Logics/dummy-project-core/clarifi-core-ui/node_modules/@pact-foundation/pact-node/standalone/win32-1.70.2/lib/vendor/ruby/2.2.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
    	from C:/Users/ylopezs/git/Loan-Logics/dummy-project-core/clarifi-core-ui/node_modules/@pact-foundation/pact-node/standalone/win32-1.70.2/lib/app/pact-mock-service.rb:15:in `<main>'
    [39m
[39m[[37m2019-10-02T17:32:17.726Z[39m] [35m WARN[39m: pact-node@9.0.4/23532 on YLOPEZS: [36mPact exited with code 1.[39m
[[37m2019-10-02T17:32:17.726Z[39m] [36m INFO[39m: pact-node@9.0.4/23532 on YLOPEZS: [36mRemoving Pact with PID: 26112[39m
[91m02 10 2019 12:32:43.232:ERROR [pact]: [39mError while trying to run karma-pact: Error: Couldn't start Pact with PID: 26112
[32m02 10 2019 12:32:43.314:INFO [karma-server]: [39mKarma v4.1.0 server started at http://0.0.0.0:9876/
[32m02 10 2019 12:32:43.314:INFO [launcher]: [39mLaunching browsers ChromeCodeBuildCi with concurrency unlimited
[32m02 10 2019 12:32:43.320:INFO [launcher]: [39mStarting browser ChromeHeadless
[32m02 10 2019 12:32:44.461:INFO [HeadlessChrome 77.0.3865 (Windows 10.0.0)]: [39mConnected on socket 4YWlRqUzZ2abh6KmAAAA with id 47354904
HeadlessChrome 77.0.3865 (Windows 10.0.0): Executed 0 of 1[32m SUCCESS[39m (0 secs / 0 secs)
WARN LOG: [36m'Passing in consumer/provider to PactWeb is deprecated,
        and will be removed in the next major version'[39m
[1A[2KWARN: [36m'Passing in consumer/provider to PactWeb is deprecated,
        and will be removed in the next major version'[39m
HeadlessChrome 77.0.3865 (Windows 10.0.0): Executed 0 of 1[32m SUCCESS[39m (0 secs / 0 secs)
INFO LOG: [36m'Setting up Pact using mock service on port: "1234"'[39m
[1A[2KINFO: [36m'Setting up Pact using mock service on port: "1234"'[39m
HeadlessChrome 77.0.3865 (Windows 10.0.0): Executed 0 of 1[32m SUCCESS[39m (0 secs / 0 secs)
[33m02 10 2019 12:32:54.749:WARN [proxy]: [39mfailed to proxy /api/notifications/notifications (connect ECONNREFUSED 127.0.0.1:1234)
[33m02 10 2019 12:32:56.756:WARN [proxy]: [39mfailed to proxy /api/notifications/notifications (connect ECONNREFUSED 127.0.0.1:1234)
[33m02 10 2019 12:32:59.065:WARN [proxy]: [39mfailed to proxy /api/notifications/notifications (connect ECONNREFUSED 127.0.0.1:1234)

  Given a Notifications service class
    when a user request GET on getNotifications method
      [31m× [39m[31mthen it should return a notification[39m
	Error: Timeout - Async function did not complete within 5000ms (set by jasmine.DEFAULT_TIMEOUT_INTERVAL)
	    at <Jasmine>

	Failed: PopsicleError: Unable to connect to "http://127.0.0.1:1234/interactions/verification"
	Error: PopsicleError: Unable to connect to "http://127.0.0.1:1234/interactions/verification"
	    at new VerificationError (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@pact-foundation/pact-web/pact-web.js:22474:1)
	    at http://localhost:9876/_karma_webpack_/webpack:/node_modules/@pact-foundation/pact-web/pact-web.js:20137:1
	    at tryCatch (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@pact-foundation/pact-web/pact-web.js:488:1)
	    at invokeCallback (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@pact-foundation/pact-web/pact-web.js:503:1)
	    at publish (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@pact-foundation/pact-web/pact-web.js:477:1)
	    at publishRejection (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@pact-foundation/pact-web/pact-web.js:418:1)
	    at MutationObserver.flush (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@pact-foundation/pact-web/pact-web.js:207:1)
	    at ZoneDelegate.../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:391:1)
	    at Zone.../node_modules/zone.js/dist/zone.js.Zone.runGuarded (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:161:1)
	    at MutationObserver.<anonymous> (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:144:1)

[1A[2K[31mHeadlessChrome 77.0.3865 (Windows 10.0.0) Given a Notifications service class when a user request GET on getNotifications method then it should return a notification FAILED[39m
	Error: Timeout - Async function did not complete within 5000ms (set by jasmine.DEFAULT_TIMEOUT_INTERVAL)
	    at <Jasmine>
	Failed: PopsicleError: Unable to connect to "http://127.0.0.1:1234/interactions/verification"
	Error: PopsicleError: Unable to connect to "http://127.0.0.1:1234/interactions/verification"
	    at new VerificationError (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@pact-foundation/pact-web/pact-web.js:22474:1)
	    at http://localhost:9876/_karma_webpack_/webpack:/node_modules/@pact-foundation/pact-web/pact-web.js:20137:1
	    at tryCatch (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@pact-foundation/pact-web/pact-web.js:488:1)
	    at invokeCallback (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@pact-foundation/pact-web/pact-web.js:503:1)
	    at publish (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@pact-foundation/pact-web/pact-web.js:477:1)
	    at publishRejection (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@pact-foundation/pact-web/pact-web.js:418:1)
	    at MutationObserver.flush (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@pact-foundation/pact-web/pact-web.js:207:1)
	    at ZoneDelegate.../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:391:1)
	    at Zone.../node_modules/zone.js/dist/zone.js.Zone.runGuarded (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:161:1)
	    at MutationObserver.<anonymous> (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:144:1)
HeadlessChrome 77.0.3865 (Windows 10.0.0): Executed 1 of 1[31m (1 FAILED)[39m (0 secs / 7.065 secs)
[31mHeadlessChrome 77.0.3865 (Windows 10.0.0) ERROR[39m
  An error was thrown in afterAll
  Failed: Unable to connect to "http://127.0.0.1:1234/interactions"
  error properties: Error
      at <Jasmine>
      at Request.error (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@pact-foundation/pact-web/pact-web.js:18968:1)
      at XMLHttpRequest.xhr.onerror [as __zone_symbol__ON_PROPERTYerror] (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@pact-foundation/pact-web/pact-web.js:22374:1)
      at XMLHttpRequest.wrapFn (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:1281:1)
      at ZoneDelegate.../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:423:1)
      at Zone.../node_modules/zone.js/dist/zone.js.Zone.runTask (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:195:1)
      at ZoneTask.../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask [as invoke] (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:498:1)
      at invokeTask (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:1693:1)
      at XMLHttpRequest.globalZoneAwareCallback (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:1719:1)
[1A[2K[31mHeadlessChrome 77.0.3865 (Windows 10.0.0) ERROR[39m
  An error was thrown in afterAll
  Failed: Unable to connect to "http://127.0.0.1:1234/interactions"
  error properties: Error
      at <Jasmine>
      at Request.error (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@pact-foundation/pact-web/pact-web.js:18968:1)
      at XMLHttpRequest.xhr.onerror [as __zone_symbol__ON_PROPERTYerror] (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@pact-foundation/pact-web/pact-web.js:22374:1)
      at XMLHttpRequest.wrapFn (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:1281:1)
      at ZoneDelegate.../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:423:1)
      at Zone.../node_modules/zone.js/dist/zone.js.Zone.runTask (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:195:1)
      at ZoneTask.../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask [as invoke] (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:498:1)
      at invokeTask (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:1693:1)
      at XMLHttpRequest.globalZoneAwareCallback (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:1719:1)
HeadlessChrome 77.0.3865 (Windows 10.0.0): Executed 1 of 1[31m (1 FAILED)[39m[31m ERROR[39m (0 secs / 7.065 secs)
[1A[2KHeadlessChrome 77.0.3865 (Windows 10.0.0): Executed 1 of 1[31m (1 FAILED)[39m[31m ERROR[39m (9.769 secs / 7.065 secs)

HeadlessChrome 77.0.3865 (Windows 10.0.0): Executed 1 of 1[31m (1 FAILED)[39m[31m ERROR[39m (9.769 secs / 7.065 secs)

[[37m2019-10-02T17:33:00.144Z[39m] [36m INFO[39m: pact-node@9.0.4/23532 on YLOPEZS: [36mRemoving all Pact servers.[39m
[[37m2019-10-02T17:33:00.145Z[39m] [36m INFO[39m: pact-node@9.0.4/23532 on YLOPEZS: [36mRemoving Pact with PID: 26112[39m
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by leonleo997** [comment]
```
yarn run v1.17.3
$ ng run clarifi-core-ui:contract --browsers ChromeCodeBuildCi
[[37m2019-10-02T17:32:13.199Z[39m] [36m INFO[39m: pact-node@9.0.4/23532 on YLOPEZS: 
[90m    [36mCreating Pact Server with options: 
    {"cors":true,"port":1234,"dir":"C:\\Users\\ylopezs\\git\\Loan-Logics\\dummy-project-core\\clarifi-core-ui\\test\\00-contract\\pacts","spec":2,"pactFileWriteMode":"overwrite","ssl":false,"host":"localhost"}[39m
[39m[[37m2019-10-02T17:32:13.225Z[39m] [36m INFO[39m: pact-node@9.0.4/23532 on YLOPEZS: [36mCreated 'standalone\win32-1.70.2\bin\pact-mock-service.bat service --cors 'true' --port '1234' --pact_dir 'C:\Users\ylopezs\git\Loan-Logics\dummy-project-core\clarifi-core-ui\test\00-contract\pacts' --pact_specification_version '2' --pact-file-write-mode 'overwrite' --host 'localhost'' process with PID: 26112[39m
[[37m2019-10-02T17:32:17.720Z[39m] [31mERROR[39m: pact-node@9.0.4/23532 on YLOPEZS: 
[90m    [36mPact Binary Error: C:/Users/ylopezs/git/Loan-Logics/dummy-project-core/clarifi-core-ui/node_modules/@pact-foundation/pact-node/standalone/win32-1.70.2/lib/vendor/ruby/2.2.0/gems/pact-mock_service-3.1.1/lib/pact/mock_service/request_handlers/interaction_post.rb:1:in `require': cannot load such file -- pact/mock_service/request_handlers/base_administration_request_handler (LoadError)
    	from C:/Users/ylopezs/git/Loan-Logics/dummy-project-core/clarifi-core-ui/node_modules/@pact-foundation/pact-node/standalone/win32-1.70.2/lib/vendor/ruby/2.2.0/gems/pact-mock_service-3.1.1/lib/pact/mock_service/request_handlers/interaction_post.rb:1:in `<top (required)>'
    	from C:/Users/ylopezs/git/Loan-Logics/dummy-project-core/clarifi-core-ui/node_modules/@pact-foundation/pact-node/standalone/win32-1.70.2/lib/vendor/ruby/2.2.0/gems/pact-mock_service-3.1.1/lib/pact/mock_service/request_handlers.rb:1:in `require'
    	from C:/Users/ylopezs/git/Loan-Logics/dummy-project-core/clarifi-core-ui/node_modules/@pact-foundation/pact-node/standalone/win32-1.70.2/lib/vendor/ruby/2.2.0/gems/pact-mock_service-3.1.1/lib/pact/mock_service/request_handlers.rb:1:in `<top (required)>'
    	from C:/Users/ylopezs/git/Loan-Logics/dummy-project-core/clarifi-core-ui/node_modules/@pact-foundation/pact-node/standalone/win32-1.70.2/lib/vendor/ruby/2.2.0/gems/pact-mock_service-3.1.1/lib/pact/mock_service/app.rb:6:in `require'
    	from C:/Users/ylopezs/git/Loan-Logics/dummy-project-core/clarifi-core-ui/node_modules/@pact-foundation/pact-node/standalone/win32-1.70.2/lib/vendor/ruby/2.2.0/gems/pact-mock_service-3.1.1/lib/pact/mock_service/app.rb:6:in `<top (required)>'
    	from C:/Users/ylopezs/git/Loan-Logics/dummy-project-core/clarifi-core-ui/node_modules/@pact-foundation/pact-node/standalone/win32-1.70.2/lib/vendor/ruby/2.2.0/gems/pact-mock_service-3.1.1/lib/pact/mock_service/run.rb:2:in `require'
    	from C:/Users/ylopezs/git/Loan-Logics/dummy-project-core/clarifi-core-ui/node_modules/@pact-foundation/pact-node/standalone/win32-1.70.2/lib/vendor/ruby/2.2.0/gems/pact-mock_service-3.1.1/lib/pact/mock_service/run.rb:2:in `<top (required)>'
    	from C:/Users/ylopezs/git/Loan-Logics/dummy-project-core/clarifi-core-ui/node_modules/@pact-foundation/pact-node/standalone/win32-1.70.2/lib/vendor/ruby/2.2.0/gems/pact-mock_service-3.1.1/lib/pact/mock_service/cli.rb:33:in `require'
    	from C:/Users/ylopezs/git/Loan-Logics/dummy-project-core/clarifi-core-ui/node_modules/@pact-foundation/pact-node/standalone/win32-1.70.2/lib/vendor/ruby/2.2.0/gems/pact-mock_service-3.1.1/lib/pact/mock_service/cli.rb:33:in `service'
    	from C:/Users/ylopezs/git/Loan-Logics/dummy-project-core/clarifi-core-ui/node_modules/@pact-foundation/pact-node/standalone/win32-1.70.2/lib/vendor/ruby/2.2.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
    	from C:/Users/ylopezs/git/Loan-Logics/dummy-project-core/clarifi-core-ui/node_modules/@pact-foundation/pact-node/standalone/win32-1.70.2/lib/vendor/ruby/2.2.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
    	from C:/Users/ylopezs/git/Loan-Logics/dummy-project-core/clarifi-core-ui/node_modules/@pact-foundation/pact-node/standalone/win32-1.70.2/lib/vendor/ruby/2.2.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
    	from C:/Users/ylopezs/git/Loan-Logics/dummy-project-core/clarifi-core-ui/node_modules/@pact-foundation/pact-node/standalone/win32-1.70.2/lib/vendor/ruby/2.2.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
    	from C:/Users/ylopezs/git/Loan-Logics/dummy-project-core/clarifi-core-ui/node_modules/@pact-foundation/pact-node/standalone/win32-1.70.2/lib/app/pact-mock-service.rb:15:in `<main>'
    [39m
[39m[[37m2019-10-02T17:32:17.726Z[39m] [35m WARN[39m: pact-node@9.0.4/23532 on YLOPEZS: [36mPact exited with code 1.[39m
[[37m2019-10-02T17:32:17.726Z[39m] [36m INFO[39m: pact-node@9.0.4/23532 on YLOPEZS: [36mRemoving Pact with PID: 26112[39m
[91m02 10 2019 12:32:43.232:ERROR [pact]: [39mError while trying to run karma-pact: Error: Couldn't start Pact with PID: 26112
[32m02 10 2019 12:32:43.314:INFO [karma-server]: [39mKarma v4.1.0 server started at http://0.0.0.0:9876/
[32m02 10 2019 12:32:43.314:INFO [launcher]: [39mLaunching browsers ChromeCodeBuildCi with concurrency unlimited
[32m02 10 2019 12:32:43.320:INFO [launcher]: [39mStarting browser ChromeHeadless
[32m02 10 2019 12:32:44.461:INFO [HeadlessChrome 77.0.3865 (Windows 10.0.0)]: [39mConnected on socket 4YWlRqUzZ2abh6KmAAAA with id 47354904
HeadlessChrome 77.0.3865 (Windows 10.0.0): Executed 0 of 1[32m SUCCESS[39m (0 secs / 0 secs)
WARN LOG: [36m'Passing in consumer/provider to PactWeb is deprecated,
        and will be removed in the next major version'[39m
[1A[2KWARN: [36m'Passing in consumer/provider to PactWeb is deprecated,
        and will be removed in the next major version'[39m
HeadlessChrome 77.0.3865 (Windows 10.0.0): Executed 0 of 1[32m SUCCESS[39m (0 secs / 0 secs)
INFO LOG: [36m'Setting up Pact using mock service on port: "1234"'[39m
[1A[2KINFO: [36m'Setting up Pact using mock service on port: "1234"'[39m
HeadlessChrome 77.0.3865 (Windows 10.0.0): Executed 0 of 1[32m SUCCESS[39m (0 secs / 0 secs)
[33m02 10 2019 12:32:54.749:WARN [proxy]: [39mfailed to proxy /api/notifications/notifications (connect ECONNREFUSED 127.0.0.1:1234)
[33m02 10 2019 12:32:56.756:WARN [proxy]: [39mfailed to proxy /api/notifications/notifications (connect ECONNREFUSED 127.0.0.1:1234)
[33m02 10 2019 12:32:59.065:WARN [proxy]: [39mfailed to proxy /api/notifications/notifications (connect ECONNREFUSED 127.0.0.1:1234)

  Given a Notifications service class
    when a user request GET on getNotifications method
      [31m× [39m[31mthen it should return a notification[39m
	Error: Timeout - Async function did not complete within 5000ms (set by jasmine.DEFAULT_TIMEOUT_INTERVAL)
	    at <Jasmine>

	Failed: PopsicleError: Unable to connect to "http://127.0.0.1:1234/interactions/verification"
	Error: PopsicleError: Unable to connect to "http://127.0.0.1:1234/interactions/verification"
	    at new VerificationError (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@pact-foundation/pact-web/pact-web.js:22474:1)
	    at http://localhost:9876/_karma_webpack_/webpack:/node_modules/@pact-foundation/pact-web/pact-web.js:20137:1
	    at tryCatch (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@pact-foundation/pact-web/pact-web.js:488:1)
	    at invokeCallback (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@pact-foundation/pact-web/pact-web.js:503:1)
	    at publish (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@pact-foundation/pact-web/pact-web.js:477:1)
	    at publishRejection (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@pact-foundation/pact-web/pact-web.js:418:1)
	    at MutationObserver.flush (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@pact-foundation/pact-web/pact-web.js:207:1)
	    at ZoneDelegate.../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:391:1)
	    at Zone.../node_modules/zone.js/dist/zone.js.Zone.runGuarded (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:161:1)
	    at MutationObserver.<anonymous> (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:144:1)

[1A[2K[31mHeadlessChrome 77.0.3865 (Windows 10.0.0) Given a Notifications service class when a user request GET on getNotifications method then it should return a notification FAILED[39m
	Error: Timeout - Async function did not complete within 5000ms (set by jasmine.DEFAULT_TIMEOUT_INTERVAL)
	    at <Jasmine>
	Failed: PopsicleError: Unable to connect to "http://127.0.0.1:1234/interactions/verification"
	Error: PopsicleError: Unable to connect to "http://127.0.0.1:1234/interactions/verification"
	    at new VerificationError (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@pact-foundation/pact-web/pact-web.js:22474:1)
	    at http://localhost:9876/_karma_webpack_/webpack:/node_modules/@pact-foundation/pact-web/pact-web.js:20137:1
	    at tryCatch (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@pact-foundation/pact-web/pact-web.js:488:1)
	    at invokeCallback (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@pact-foundation/pact-web/pact-web.js:503:1)
	    at publish (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@pact-foundation/pact-web/pact-web.js:477:1)
	    at publishRejection (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@pact-foundation/pact-web/pact-web.js:418:1)
	    at MutationObserver.flush (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@pact-foundation/pact-web/pact-web.js:207:1)
	    at ZoneDelegate.../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:391:1)
	    at Zone.../node_modules/zone.js/dist/zone.js.Zone.runGuarded (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:161:1)
	    at MutationObserver.<anonymous> (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:144:1)
HeadlessChrome 77.0.3865 (Windows 10.0.0): Executed 1 of 1[31m (1 FAILED)[39m (0 secs / 7.065 secs)
[31mHeadlessChrome 77.0.3865 (Windows 10.0.0) ERROR[39m
  An error was thrown in afterAll
  Failed: Unable to connect to "http://127.0.0.1:1234/interactions"
  error properties: Error
      at <Jasmine>
      at Request.error (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@pact-foundation/pact-web/pact-web.js:18968:1)
      at XMLHttpRequest.xhr.onerror [as __zone_symbol__ON_PROPERTYerror] (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@pact-foundation/pact-web/pact-web.js:22374:1)
      at XMLHttpRequest.wrapFn (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:1281:1)
      at ZoneDelegate.../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:423:1)
      at Zone.../node_modules/zone.js/dist/zone.js.Zone.runTask (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:195:1)
      at ZoneTask.../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask [as invoke] (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:498:1)
      at invokeTask (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:1693:1)
      at XMLHttpRequest.globalZoneAwareCallback (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:1719:1)
[1A[2K[31mHeadlessChrome 77.0.3865 (Windows 10.0.0) ERROR[39m
  An error was thrown in afterAll
  Failed: Unable to connect to "http://127.0.0.1:1234/interactions"
  error properties: Error
      at <Jasmine>
      at Request.error (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@pact-foundation/pact-web/pact-web.js:18968:1)
      at XMLHttpRequest.xhr.onerror [as __zone_symbol__ON_PROPERTYerror] (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@pact-foundation/pact-web/pact-web.js:22374:1)
      at XMLHttpRequest.wrapFn (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:1281:1)
      at ZoneDelegate.../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:423:1)
      at Zone.../node_modules/zone.js/dist/zone.js.Zone.runTask (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:195:1)
      at ZoneTask.../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask [as invoke] (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:498:1)
      at invokeTask (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:1693:1)
      at XMLHttpRequest.globalZoneAwareCallback (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:1719:1)
HeadlessChrome 77.0.3865 (Windows 10.0.0): Executed 1 of 1[31m (1 FAILED)[39m[31m ERROR[39m (0 secs / 7.065 secs)
[1A[2KHeadlessChrome 77.0.3865 (Windows 10.0.0): Executed 1 of 1[31m (1 FAILED)[39m[31m ERROR[39m (9.769 secs / 7.065 secs)

HeadlessChrome 77.0.3865 (Windows 10.0.0): Executed 1 of 1[31m (1 FAILED)[39m[31m ERROR[39m (9.769 secs / 7.065 secs)

[[37m2019-10-02T17:33:00.144Z[39m] [36m INFO[39m: pact-node@9.0.4/23532 on YLOPEZS: [36mRemoving all Pact servers.[39m
[[37m2019-10-02T17:33:00.145Z[39m] [36m INFO[39m: pact-node@9.0.4/23532 on YLOPEZS: [36mRemoving Pact with PID: 26112[39m
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by mefellows** [comment]
Might be windows path length issues. Search through previous issues here and in `pact-node` to see if they help

**Comment by mefellows** [comment]
@leonleo997, could you please provide a reproduceable example for this? We have an appveyor build to test this on Windows, so if it's a problem with Pact JS we should be able to get a failed build on that.

See https://github.com/pact-foundation/pact-node/issues/100 for issues relating to path length.

**Comment by mefellows** [comment]
Closing due to inactivity.
