### ISSUE TITLE
Pact >= 9.0.0 breaks npm audit

### ISSUE THREAD

**Issue by riccardoNovaglia** [pact-foundation/pact-js#378]
## Software versions

* **OS**: Mac OSX 10.14.6
* **Library**: @pact-foundation/pact (npm)
* **Consumer Pact library**: N/A
* **Provider Pact library**: N/A
* **Node Version**: v12.11.1 (attempted on v11.15.0)
* **npm Version**: 6.12.0

## Expected behaviour

Npm audit produces a vulnerabilty report

## Actual behaviour

With node v12.11.1
```
-> npm audit
npm ERR! code ENOAUDIT
npm ERR! audit Your configured registry (https://registry.npmjs.org/) may not support audit requests, or the audit endpoint may be temporarily unavailable.
npm ERR! audit The server said: Invalid package tree, run  npm install  to rebuild your package-lock.json

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/novar/.npm/_logs/2019-10-11T11_32_14_575Z-debug.log
```

With node v11.15.0
```
npm audit    
npm ERR! code ENOAUDIT
npm ERR! audit Your configured registry (https://registry.npmjs.org/) does not support audit requests, or the audit endpoint is temporarily unavailable.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/novar/.npm/_logs/2019-10-11T11_38_44_508Z-debug.log
```
This currently happens on my machine, I've tried on a windows desktop and another laptop and cannot replicate the problem. I appreciate it might mean that it's something off with my machine, but I can't replicate this with any other library, and I've found that it works on on 8.x.x versions

## Steps to reproduce

Add `"@pact-foundation/pact": "9.0.0"` to `dependencies` or `devDependencies` of a project, run `npm install`,  run `npm audit`.

Sample repo:
https://github.com/riccardoNovaglia/broken-pact-audit
Clone, install, audit

## Relevant log files

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/Users/xxxxx/.nvm/versions/node/v12.11.1/bin/node',
1 verbose cli   '/Users/xxxxx/.nvm/versions/node/v12.11.1/bin/npm',
1 verbose cli   'audit'
1 verbose cli ]
2 info using npm@6.11.3
3 info using node@v12.11.1
4 verbose npm-session ec2995233c8a15b3
5 http fetch POST 400 https://registry.npmjs.org/-/npm/v1/security/audits 527ms
6 verbose stack Error: Your configured registry (https://registry.npmjs.org/) may not support audit requests, or the audit endpoint may be temporarily unavailable.
6 verbose stack The server said: Invalid package tree, run  npm install  to rebuild your package-lock.json
6 verbose stack     at /Users/xxxxx/.nvm/versions/node/v12.11.1/lib/node_modules/npm/lib/audit.js:204:18
6 verbose stack     at tryCatcher (/Users/xxxxx/.nvm/versions/node/v12.11.1/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
6 verbose stack     at Promise._settlePromiseFromHandler (/Users/xxxxx/.nvm/versions/node/v12.11.1/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:517:31)
6 verbose stack     at Promise._settlePromise (/Users/xxxxx/.nvm/versions/node/v12.11.1/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:574:18)
6 verbose stack     at Promise._settlePromise0 (/Users/xxxxx/.nvm/versions/node/v12.11.1/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:619:10)
6 verbose stack     at Promise._settlePromises (/Users/xxxxx/.nvm/versions/node/v12.11.1/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:695:18)
6 verbose stack     at _drainQueueStep (/Users/xxxxx/.nvm/versions/node/v12.11.1/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:138:12)
6 verbose stack     at _drainQueue (/Users/xxxxx/.nvm/versions/node/v12.11.1/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:131:9)
6 verbose stack     at Async._drainQueues (/Users/xxxxx/.nvm/versions/node/v12.11.1/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:147:5)
6 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (/Users/xxxxx/.nvm/versions/node/v12.11.1/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
6 verbose stack     at processImmediate (internal/timers.js:439:21)
7 verbose cwd /Users/xxxxx/repos/test
8 verbose Darwin 18.7.0
9 verbose argv "/Users/xxxxx/.nvm/versions/node/v12.11.1/bin/node" "/Users/xxxxx/.nvm/versions/node/v12.11.1/bin/npm" "audit"
10 verbose node v12.11.1
11 verbose npm  v6.11.3
12 error code ENOAUDIT
13 error audit Your configured registry (https://registry.npmjs.org/) may not support audit requests, or the audit endpoint may be temporarily unavailable.
13 error audit The server said: Invalid package tree, run  npm install  to rebuild your package-lock.json
14 verbose exit [ 1, true ]
```

**Comment by TimothyJones** [comment]
Thanks for providing the example repo.

I'm not sure what's going on here, but I think it might be a node problem.

I could reproduce it with node v12.11.1, but it went away if I switched to 12.12.0 (the latest current release).

It also didn't happen in node v10.16.3, which is the current LTS release.

**Comment by TimothyJones** [comment]
I'll close this for now, because I don't think there's anything we can do with pact-node to fix it. Please feel free to reopen if you believe otherwise.
