### ISSUE TITLE
linux-x64-1.70.2/lib/ruby/bin/ruby: not found / TypeError: Cannot read property 'writePact' of undefined

### ISSUE THREAD

**Issue by basickarl** [pact-foundation/pact-js#380]
## Software versions

Linux 
node:10.16.0-alpine (Docker image)
pact-node@9.0.4/67
node 10.16.0

## Expected behaviour

Consumer test to work (not a provider test)

It's works locally on my Ubuntu 14.04 computer.

## Actual behaviour

```
Pact Binary Error: ./standalone/linux-x64-1.70.2/bin/pact-mock-service: exec: line 28: /home/node/app/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.70.2/lib/ruby/bin/ruby: not found
```

## Steps to reproduce

Cannot give code, code is pretty sensitive. But we can give the Dockerfile which makes the code:

```
# Build image
FROM node:10.16.0-alpine AS build-image
USER root
RUN apk --no-cache add python make g++ git wine
USER node
RUN mkdir /home/node/app/
WORKDIR /home/node/app/
COPY --chown=node:node package.json /home/node/app/
COPY --chown=node:node package-lock.json /home/node/app/
RUN mkdir /home/node/tmp/ && \
    npm cache verify && \
    npm install --only=production && \
    cp -a /home/node/app/node_modules /home/node/tmp/node_modules_production && \
    npm install --only=development && \
    cp -a /home/node/app/node_modules /home/node/tmp/node_modules
COPY --chown=node:node . .
RUN npx tsc && \
    ls -la /home/node/app/_build/
RUN rm -rf /home/node/app/node_modules
ENTRYPOINT [ "/bin/sh" ]

# General image
FROM node:10.16.0-alpine AS general-image
USER node
RUN mkdir /home/node/app/
WORKDIR /home/node/app/
COPY --chown=node:node --from=build-image /home/node/tmp/node_modules/ /home/node/app/node_modules/
COPY --chown=node:node --from=build-image /home/node/app/ /home/node/app/
RUN ls -la /home/node/app/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.70.2/lib/ruby/bin/
ENTRYPOINT [ "npm", "run" ]
```

Got the output when building the image:
```
Step 20/21 : RUN ls -la /home/node/app/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.70.2/lib/ruby/bin/
 ---> Running in 722df0ebeb5f
total 28
drwxrwxr-x    2 node     node          4096 Oct 17 11:40 .
drwxrwxr-x    6 node     node          4096 Oct 17 11:40 ..
-rwxr-xr-x    1 node     node           160 Jul 14  2015 gem
-rwxr-xr-x    1 node     node           160 Jul 14  2015 irb
-rwxr-xr-x    1 node     node           161 Jul 14  2015 rake
-rwxr-xr-x    1 node     node           139 Jul 14  2015 ruby
-rwxr-xr-x    1 node     node          1177 Jul 14  2015 ruby_environment
```

## Relevant log files

```
karl@karl-Dell-Precision-M3800:~/dev/s-g$ docker run --name "test-1" -e "PACT_HOSTNAME=https://xxxxxxx.com" "s-g-general:1" consumer_test

> s-g@0.1.0 consumer_test /home/node/app
> npm run build && npx cross-env s_g_NODE_ENV=test mocha "_build/test/contract/**/*.consumer.spec.js"


> s-g@0.1.0 build /home/node/app
> npx shx rm -rf _build && npx tsc

The configuration file /home/node/app/config/test.json does not exist, loading default configuration
Config lib initialized
[2019-10-17T11:41:15.287Z]  INFO: pact-node@9.0.4/67 on 2aabc4ddefa1: 
    Creating Pact Server with options: 
    {"consumer":"s g","cors":false,"dir":"/home/node/app/_pacts","host":"127.0.0.1","log":"/home/node/app/log/pact-consumer.log","pactFileWriteMode":"overwrite","port":8080,"provider":"s g Test Module","spec":2,"ssl":false}


  Consumer contract test
    example
[2019-10-17T11:41:15.314Z]  INFO: pact-node@9.0.4/67 on 2aabc4ddefa1: Created './standalone/linux-x64-1.70.2/bin/pact-mock-service service --consumer 's g' --pact_dir '/home/node/app/_pacts' --host '127.0.0.1' --log '/home/node/app/log/pact-consumer.log' --pact-file-write-mode 'overwrite' --port '8080' --provider 's g Test Module' --pact_specification_version '2'' process with PID: 78
[2019-10-17T11:41:15.321Z] ERROR: pact-node@9.0.4/67 on 2aabc4ddefa1: 
    Pact Binary Error: ./standalone/linux-x64-1.70.2/bin/pact-mock-service: exec: line 28: /home/node/app/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.70.2/lib/ruby/bin/ruby: not found
    
[2019-10-17T11:41:15.326Z]  WARN: pact-node@9.0.4/67 on 2aabc4ddefa1: Pact exited with code 127.
[2019-10-17T11:41:15.327Z]  INFO: pact-node@9.0.4/67 on 2aabc4ddefa1: Removing Pact with PID: 78
      1) "before all" hook for "should receive response with hello object"
      2) "after all" hook for "should receive response with hello object"


  0 passing (2s)
  2 failing

  1) Consumer contract test
       example
         "before all" hook for "should receive response with hello object":
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/node/app/_build/test/contract/example.consumer.spec.js)
  

  2) Consumer contract test
       example
         "after all" hook for "should receive response with hello object":
     TypeError: Cannot read property 'writePact' of undefined
      at Pact.finalize (node_modules/@pact-foundation/pact/httpPact.js:121:14)
      at Context.<anonymous> (_build/test/contract/example.consumer.spec.js:65:26)
      at Generator.next (<anonymous>)
      at /home/node/app/_build/test/contract/example.consumer.spec.js:7:71
      at new Promise (<anonymous>)
      at __awaiter (_build/test/contract/example.consumer.spec.js:3:12)
      at Context.<anonymous> (_build/test/contract/example.consumer.spec.js:64:20)

```

I even manually started the container and attached a terminal session and checked to see if the files exists and it does. Same error when I run the test manual:

```
~/app $ npx mocha "_build/test/contract/**/*.consumer.spec.js"
The configuration file /home/node/app/config/development.json does not exist, loading default configuration
Config lib initialized
[2019-10-17T12:09:10.433Z]  INFO: pact-node@9.0.4/103 on 8b2ec8012a4e: 
    Creating Pact Server with options: 
    {"consumer":"s g","cors":false,"dir":"/home/node/app/_pacts","host":"127.0.0.1","log":"/home/node/app/log/pact-consumer.log","pactFileWriteMode":"overwrite","port":8080,"provider":"s g Test Module","spec":2,"ssl":false}


  Consumer contract test
    example
[2019-10-17T12:09:10.469Z]  INFO: pact-node@9.0.4/103 on 8b2ec8012a4e: Created './standalone/linux-x64-1.70.2/bin/pact-mock-service service --consumer 's g' --pact_dir '/home/node/app/_pacts' --host '127.0.0.1' --log '/home/node/app/log/pact-consumer.log' --pact-file-write-mode 'overwrite' --port '8080' --provider 's g Test Module' --pact_specification_version '2'' process with PID: 114
[2019-10-17T12:09:10.475Z] ERROR: pact-node@9.0.4/103 on 8b2ec8012a4e: 
    Pact Binary Error: ./standalone/linux-x64-1.70.2/bin/pact-mock-service: exec: line 28: /home/node/app/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.70.2/lib/ruby/bin/ruby: not found
    
[2019-10-17T12:09:10.481Z]  WARN: pact-node@9.0.4/103 on 8b2ec8012a4e: Pact exited with code 127.
[2019-10-17T12:09:10.481Z]  INFO: pact-node@9.0.4/103 on 8b2ec8012a4e: Removing Pact with PID: 114
      1) "before all" hook for "should receive response with hello object"
      2) "after all" hook for "should receive response with hello object"


  0 passing (2s)
  2 failing

  1) Consumer contract test
       example
         "before all" hook for "should receive response with hello object":
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/node/app/_build/test/contract/example.consumer.spec.js)
  

  2) Consumer contract test
       example
         "after all" hook for "should receive response with hello object":
     TypeError: Cannot read property 'writePact' of undefined
      at Pact.finalize (node_modules/@pact-foundation/pact/httpPact.js:121:14)
      at Context.<anonymous> (_build/test/contract/example.consumer.spec.js:65:26)
      at Generator.next (<anonymous>)
      at /home/node/app/_build/test/contract/example.consumer.spec.js:7:71
      at new Promise (<anonymous>)
      at __awaiter (_build/test/contract/example.consumer.spec.js:3:12)
      at Context.<anonymous> (_build/test/contract/example.consumer.spec.js:64:20)
```

Might be something to do with alpines shell `ash`?:
```
~/app $ . /home/node/app/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.70.2/lib/ruby/bin/ruby
ash: /home/node/app/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.70.2/lib/ruby/bin/ruby: /home/node/bin/ruby_environment: not found
ash: exec: line 6: /home/node/bin.real/ruby: not found
```
Tried it with `bash` after doing a `npm install` via `ash`:
```
[2019-10-17T12:22:38.091Z] ERROR: pact-node@9.0.4/18 on d0a794e241a0: 
    Pact Binary Error: /home/node/app/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.70.2/lib/ruby/bin/ruby: line 6: /home/node/app/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.70.2/lib/ruby/bin.real/ruby: No such file or directory
```

Also another annoying thing is that the mock server is not automatically shutdown. This leads to my CI jobs timing out after hour if I don't cancel them manually.

**Comment by TimothyJones** [comment]
Pact-js uses the pact ruby standalone as the backing implementation- have a look at:

https://github.com/pact-foundation/pact-ruby-standalone/wiki/Using-the-pact-ruby-standalone-with-Alpine-Linux-Docker

Can you tell us a bit more about the mock server sticking around? Is it sticking around when this error happens?

**Comment by mefellows** [comment]
Have you googled for other issues when using Alpine? I think you might need some extra dependencies in your image. See https://docs.pact.io/docker#alpine-linux

**Comment by basickarl** [comment]
@TimothyJones Hey man thanks for the quick reply!

Here is the log for the Azure CI job log:
```
##[debug]Evaluating condition for step: 'Contract consumer test'
##[debug]Evaluating: SucceededNode()
##[debug]Evaluating SucceededNode:
##[debug]=> True
##[debug]Result: True
##[section]Starting: Contract consumer test
==============================================================================
Task         : Command line
Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
Version      : 2.151.2
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
==============================================================================
##[debug]VstsTaskSdk 0.9.0 commit 6c48b16164b9a1c9548776ad2062dad5cd543352
##[debug]Entering D:\a\_tasks\CmdLine_d9bafed4-0b18-4f58-968d-86655b4d2ce9\2.151.2\cmdline.ps1.
##[debug]Loading resource strings from: D:\a\_tasks\CmdLine_d9bafed4-0b18-4f58-968d-86655b4d2ce9\2.151.2\task.json
##[debug]Loaded 6 strings.
##[debug]SYSTEM_CULTURE: 'en-US'
##[debug]Loading resource strings from: D:\a\_tasks\CmdLine_d9bafed4-0b18-4f58-968d-86655b4d2ce9\2.151.2\Strings\resources.resjson\en-US\resources.resjson
##[debug]Loaded 6 strings.
##[debug]INPUT_FAILONSTDERR: 'false'
##[debug] Converted to bool: False
##[debug]INPUT_SCRIPT: 'echo %VARIABLE_NAME%
##[debug]set PACT_HOSTNAME=%host%
##[debug]npm run consumer_test'
##[debug]INPUT_WORKINGDIRECTORY: 'd:\a\1\s'
##[debug]Asserting container path exists: 'd:\a\1\s'
Generating script.
##[debug]AGENT_VERSION: '2.158.0'
##[debug]AGENT_TEMPDIRECTORY: 'd:\a\_temp'
##[debug]Asserting container path exists: 'd:\a\_temp'
##[debug]Asserting leaf path exists: 'C:\windows\system32\cmd.exe'
========================== Starting Command Output ===========================
##[debug]Entering Invoke-VstsTool.
##[debug] Arguments: '/D /E:ON /V:OFF /S /C "CALL "d:\a\_temp\fc15fa53-5cc9-4b2c-9f86-615ea9139fd9.cmd""'
##[debug] FileName: 'C:\windows\system32\cmd.exe'
##[debug] WorkingDirectory: 'd:\a\1\s'
##[command]"C:\windows\system32\cmd.exe" /D /E:ON /V:OFF /S /C "CALL "d:\a\_temp\fc15fa53-5cc9-4b2c-9f86-615ea9139fd9.cmd""
ECHO is off.

> s-g@0.1.0 consumer_test D:\a\1\s
> npm run build && npx cross-env s_g_NODE_ENV=test mocha "_build/test/contract/**/*.consumer.spec.js"


> s-g@0.1.0 build D:\a\1\s
> npx shx rm -rf _build && npx tsc

The configuration file D:\a\1\s\config/test.json does not exist, loading default configuration
Config lib initialized
[‌2019-10-08T14:10:43.637Z‌] ‌ INFO‌: pact-node@9.0.4&#x2F;4844 on fv-az66: ‌
    ‌Creating Pact Server with options: ‌
    {&quot;consumer&quot;:&quot;s g&quot;,&quot;cors&quot;:false,&quot;dir&quot;:&quot;D:\\a\\1\\s\\_pacts&quot;,&quot;host&quot;:&quot;127.0.0.1&quot;,&quot;log&quot;:&quot;D:\\a\\1\\s\\log\\pact-consumer.log&quot;,&quot;pactFileWriteMode&quot;:&quot;overwrite&quot;,&quot;port&quot;:8080,&quot;provider&quot;:&quot;s g Test Module&quot;,&quot;spec&quot;:2,&quot;ssl&quot;:false}‌


  Consumer contract test
    example
[‌2019-10-08T14:10:43.715Z‌] ‌ INFO‌: pact-node@9.0.4&#x2F;4844 on fv-az66: ‌Created &#x27;standalone\win32-1.70.2\bin\pact-mock-service.bat service --consumer &#x27;s g&#x27; --pact_dir &#x27;D:\a\1\s\_pacts&#x27; --host &#x27;127.0.0.1&#x27; --log &#x27;D:\a\1\s\log\pact-consumer.log&#x27; --pact-file-write-mode &#x27;overwrite&#x27; --port &#x27;8080&#x27; --provider &#x27;s g Test Module&#x27; --pact_specification_version &#x27;2&#x27;&#x27; process with PID: 5952‌
      1) "before all" hook for "should receive response with hello object"
      2) "after all" hook for "should receive response with hello object"


  0 passing (2s)
  2 failing

  1) Consumer contract test
       example
         "before all" hook for "should receive response with hello object":
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (D:\a\1\s\_build\test\contract\example.consumer.spec.js)
  

  2) Consumer contract test
       example
         "after all" hook for "should receive response with hello object":
     TypeError: Cannot read property 'writePact' of undefined
      at Pact.finalize (node_modules\@pact-foundation\pact\httpPact.js:121:14)
      at Context.<anonymous> (_build\test\contract\example.consumer.spec.js:65:26)
      at Generator.next (<anonymous>)
      at D:\a\1\s\_build\test\contract\example.consumer.spec.js:7:71
      at new Promise (<anonymous>)
      at __awaiter (_build\test\contract\example.consumer.spec.js:3:12)
      at Context.<anonymous> (_build\test\contract\example.consumer.spec.js:64:20)



[‌2019-10-08T14:10:45.781Z‌] ‌ INFO‌: pact@9.1.1&#x2F;4844 on fv-az66: ‌
    ‌Setting up Pact with Consumer &quot;s g&quot; and Provider &quot;s g Test Module&quot;‌
        using mock service on Port: &quot;8080&quot;‌
##[debug]Re-evaluate condition on job cancellation for step: 'Contract consumer test'.
[‌2019-10-08T15:08:08.731Z‌] ‌ INFO‌: pact-node@9.0.4&#x2F;4844 on fv-az66: ‌Removing all Pact servers.‌
[‌2019-10-08T15:08:08.731Z‌] ‌ INFO‌: pact-node@9.0.4&#x2F;4844 on fv-az66: ‌Removing Pact with PID: 5952‌
Terminate batch job (Y/N)? 
##[debug]Leaving Invoke-VstsTool.
##[debug]Leaving D:\a\_tasks\CmdLine_d9bafed4-0b18-4f58-968d-86655b4d2ce9\2.151.2\cmdline.ps1.
##[error]The operation was canceled.
##[debug]System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Microsoft.VisualStudio.Services.Agent.Util.ProcessInvoker.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, InputQueue`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.ProcessInvokerWrapper.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, InputQueue`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.DefaultStepHost.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Boolean inheritConsoleHandler, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.PowerShell3Handler.RunAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskRunner.RunAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken)
##[section]Finishing: Contract consumer test
```

@mefellows Arrrrghhh, I missed that part in the documentation, thanks man!

**Comment by mefellows** [comment]
It comes up a bit. We might even be able to catch those specific issues and send people to documented issues from the logs. I'll look again tomorrow when I'm not on mobile.

Did it resolve your issue tho?

**Comment by basickarl** [comment]
@mefellows @TimothyJones I did fix this specific issue! So thanks! I have a new Pact issue now, but that will be for another ticket, ta!

**Comment by mefellows** [comment]
👍
