### ISSUE TITLE
Body not being sent in Verifier POST/PUT requests

### ISSUE THREAD

**Issue by mc-carthy** [pact-foundation/pact-js#420]
Hey guys, 

I'm relatively new to Pact so apologies if this is user error. I've run into an issue (that seems to have occurred previously with different causes looking at past issues) where, when using a Verifier to sent POST/PUT requests, the body is not being sent with the request. Having looked at previous users' issues, this does not seem to be caused by encoding or not setting the `application/json` header correctly.

I hope this isn't something that has been covered elsewhere (I have checked out the existing issues and similar questions on StackOverflow but with no solution as of yet).

Thanks!

## Software versions

* **OS**: Mac OSX 10.14.6
* **Consumer Pact library**: Pact JS v9.8.1
* **Provider Pact library**: Pact JS v9.8.1
* **Node Version**: v13.10.1

## Expected behaviour

Pact verifier sends POST/PUT requests as specified in relevant pact file as part of test.

## Actual behaviour

Request sent successfully, however the body is not included, causing the test to fail when trying to ready a property of the body.

## Steps to reproduce

I have created a repository with a minimal consumer-provider set up that shows the problem I am experiencing here: https://github.com/mc-carthy/pactJsPostBodyIssue

The consumer generated pact file has already been added to the relevant directory in the provider. Running `npm test` from the provider directory will kick off the test, where it will fail due to not being able to parse the `name` property of the body of the POST request sent. I have added a log there that shows no body is present on the incoming request.

Running the provider with `npm start` and sending the same POST request directly to the provider works fine (I have exported a PostMan request that can be used here: https://gist.github.com/mc-carthy/5aa9bed06e368d8a7f096e4c8c8dc792)

Note: I haven't added any state handlers in order to keep the repository as bare-bones as possible. This issue was still present when using state handlers.

**Comment by mefellows** [comment]
Thanks for the detailed report @mc-carthy - it is genuinely much appreciated. Hopefully we can get it sorted for you quickly.

**Comment by mefellows** [comment]
I think there is something wrong with the express route setup in your test. If you run `node provider.js` directly it works:

```
➜  provider git:(master) ✗ curl -v -X POST localhost:3001/users  -d '{
          "name": "Test User"
        }'
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 3001 (#0)
> POST /users HTTP/1.1
> Host: localhost:3001
> User-Agent: curl/7.54.0
> Accept: */*
> Content-Length: 41
> Content-Type: application/x-www-form-urlencoded
>
* upload completely sent off: 41 out of 41 bytes
< HTTP/1.1 200 OK
< X-Powered-By: Express
< Content-Type: application/json; charset=utf-8
< Content-Length: 8
< ETag: W/"8-h5EdGu1QmHe4OkjsU292jNzSLfE"
< Date: Fri, 20 Mar 2020 11:13:41 GMT
< Connection: keep-alive
<
* Connection #0 to host localhost left intact
{"id":1}
```

If I remove the pact test, and just let your test configuration run the server and do the same `cURL`, I get the stack trace.


```
➜  provider git:(master) ✗ curl -v -X POST localhost:3001/users  -d '{
          "name": "Test User"
        }'
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 3001 (#0)
> POST /users HTTP/1.1
> Host: localhost:3001
> User-Agent: curl/7.54.0
> Accept: */*
> Content-Length: 41
> Content-Type: application/x-www-form-urlencoded
>
* upload completely sent off: 41 out of 41 bytes
< HTTP/1.1 500 Internal Server Error
< X-Powered-By: Express
< Content-Security-Policy: default-src 'none'
< X-Content-Type-Options: nosniff
< Content-Type: text/html; charset=utf-8
< Content-Length: 4096
< Date: Fri, 20 Mar 2020 11:15:02 GMT
< Connection: keep-alive
<
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>TypeError: Cannot read property &#39;name&#39; of undefined<br> &nbsp; &nbsp;at /private/tmp/pactJsPostBodyIssue/provider/routes.js:10:20<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/private/tmp/pactJsPostBodyIssue/provider/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at next (/private/tmp/pactJsPostBodyIssue/provider/node_modules/express/lib/router/route.js:137:13)<br> &nbsp; &nbsp;at Route.dispatch (/private/tmp/pactJsPostBodyIssue/provider/node_modules/express/lib/router/route.js:112:3)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/private/tmp/pactJsPostBodyIssue/provider/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at /private/tmp/pactJsPostBodyIssue/provider/node_modules/express/lib/router/index.js:281:22<br> &nbsp; &nbsp;at Function.process_params (/private/tmp/pactJsPostBodyIssue/provider/node_modules/express/lib/router/index.js:335:12)<br> &nbsp; &nbsp;at next (/private/tmp/pactJsPostBodyIssue/provider/node_modules/express/lib/router/index.js:275:10)<br> &nbsp; &nbsp;at Function.handle (/private/tmp/pactJsPostBodyIssue/provider/node_modules/express/lib/router/index.js:174:3)<br> &nbsp; &nbsp;at router (/private/tmp/pactJsPostBodyIssue/provider/node_modules/express/lib/router/index.js:47:12)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/private/tmp/pactJsPostBodyIssue/provider/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at trim_prefix (/private/tmp/pactJsPostBodyIssue/provider/node_modules/express/lib/router/index.js:317:13)<br> &nbsp; &nbsp;at /private/tmp/pactJsPostBodyIssue/provider/node_modules/express/lib/router/index.js:284:7<br> &nbsp; &nbsp;at Function.process_params (/private/tmp/pactJsPostBodyIssue/provider/node_modules/express/lib/router/index.js:335:12)<br> &nbsp; &nbsp;at next (/private/tmp/pactJsPostBodyIssue/provider/node_modules/express/lib/router/index.js:275:10)<br> &nbsp; &nbsp;at expressInit (/private/tmp/pactJsPostBodyIssue/provider/node_modules/express/lib/middleware/init.js:40:5)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/private/tmp/pactJsPostBodyIssue/provider/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at trim_prefix (/private/tmp/pactJsPostBodyIssue/provider/node_modules/express/lib/router/index.js:317:13)<br> &nbsp; &nbsp;at /private/tmp/pactJsPostBodyIssue/provider/node_modules/express/lib/router/index.js:284:7<br> &nbsp; &nbsp;at Function.process_params (/private/tmp/pactJsPostBodyIssue/provider/node_modules/express/lib/router/index.js:335:12)<br> &nbsp; &nbsp;at next (/private/tmp/pactJsPostBodyIssue/provider/node_modules/express/lib/router/index.js:275:10)<br> &nbsp; &nbsp;at query (/private/tmp/pactJsPostBodyIssue/provider/node_modules/express/lib/middleware/query.js:45:5)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/private/tmp/pactJsPostBodyIssue/provider/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at trim_prefix (/private/tmp/pactJsPostBodyIssue/provider/node_modules/express/lib/router/index.js:317:13)<br> &nbsp; &nbsp;at /private/tmp/pactJsPostBodyIssue/provider/node_modules/express/lib/router/index.js:284:7<br> &nbsp; &nbsp;at Function.process_params (/private/tmp/pactJsPostBodyIssue/provider/node_modules/express/lib/router/index.js:335:12)<br> &nbsp; &nbsp;at next (/private/tmp/pactJsPostBodyIssue/provider/node_modules/express/lib/router/index.js:275:10)<br> &nbsp; &nbsp;at Function.handle (/private/tmp/pactJsPostBodyIssue/provider/node_modules/express/lib/router/index.js:174:3)<br> &nbsp; &nbsp;at Function.handle (/private/tmp/pactJsPostBodyIssue/provider/node_modules/express/lib/application.js:174:10)<br> &nbsp; &nbsp;at Server.app (/private/tmp/pactJsPostBodyIssue/provider/node_modules/express/lib/express.js:39:9)<br> &nbsp; &nbsp;at Server.emit (events.js:182:13)<br> &nbsp; &nbsp;at parserOnIncoming (_http_server.js:652:12)<br> &nbsp; &nbsp;at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)</pre>
</body>
</html>
* Connection #0 to host localhost left intact
```

**Comment by mefellows** [comment]
Ah! You're not using the body parser middleware in your app: `app.use(bodyParser.json());`

I would suggest setting things up in such a way that you can import a fully configured express app into your tests, otherwise as your provider expands, you won't be guaranteed to test the real thing.

**Comment by mc-carthy** [comment]
Amazing, thank you very much @mefellows 

Had a suspicion it was user error, thank you very much for your help (especially at this hour in Australia!).

**Comment by mefellows** [comment]
I was currently reading legal docs and this was a timely excuse to stop doing that - glad I could help!
