### ISSUE TITLE
Verifying redirects in provider

### ISSUE THREAD

**Issue by gvijayakumar-16** [pact-foundation/pact-js#446]
Hi,

I am trying to write tests for an api which does redirect (302).

My pact verifier is configured as below:

```
describe("Pact Verification", () => {
    it("validates the expectations of service", async function () {
        let opts = {
            provider: "ui-api",
            logLevel: "INFO",
            providerBaseUrl: "https://my-hostedservice.com",
            pactUrls: [
                path.resolve(
                    process.cwd(),
                    "./pacts/ui-web-api.json"
                ),
            ],
            validateSSL: false,
            providerVersion: "1.0.0"
        }
        return new Verifier(opts).verifyProvider().then(output => {
            console.log("Pact Verification Complete!")
            console.log(output)
        })
    })
})
```

When I run the above, I get the error ` NoMethodError: undefined method 'strip' for nil:NilClass`

I am assuming this is because status code is being returned as null in the response and it is trying to strip that data - as that is the only data I am asserting for.

To debug this further, I spun up a local provider (http://localhost:8081) and from inside that I tried hitting the actual url by restricting redirects. I get the expected results.

So, does that mean redirects are happening in the original scenario?

I looked at the code and cross checked with the `http-proxy` docs and found that followRedirects defaulted to false.

Anything I am missing here?

**Comment by bethesque** [comment]
Can you run this test with the environment variable `BACKTRACE=true` please?

**Comment by mefellows** [comment]
Can you also please provide your pact file (redacted if necessary)? Apologies this one went stale.

**Comment by mefellows** [comment]
I've just pushed up a branch that shows a successful `302` test for consumer and provider. Feel free to modify the code to show how it fails for you https://github.com/pact-foundation/pact-js/compare/repro/446?expand=1.

**Comment by gvijayakumar-16** [comment]
Logs when I run with BACTRACE=true

```
NoMethodError:
       undefined method `strip' for nil:NilClass
     # ./standalone/linux-x64-1.84.0/pact/lib/vendor/ruby/2.2.0/gems/rack-2.1.2/lib/rack/mock.rb:242:in `block in identify_cookie_attributes'
     # ./standalone/linux-x64-1.84.0/pact/lib/vendor/ruby/2.2.0/gems/rack-2.1.2/lib/rack/mock.rb:239:in `each'
     # ./standalone/linux-x64-1.84.0/pact/lib/vendor/ruby/2.2.0/gems/rack-2.1.2/lib/rack/mock.rb:239:in `identify_cookie_attributes'
     # ./standalone/linux-x64-1.84.0/pact/lib/vendor/ruby/2.2.0/gems/rack-2.1.2/lib/rack/mock.rb:220:in `block in parse_cookies_from_header'
     # ./standalone/linux-x64-1.84.0/pact/lib/vendor/ruby/2.2.0/gems/rack-2.1.2/lib/rack/mock.rb:218:in `each'
     # ./standalone/linux-x64-1.84.0/pact/lib/vendor/ruby/2.2.0/gems/rack-2.1.2/lib/rack/mock.rb:218:in `parse_cookies_from_header'
     # ./standalone/linux-x64-1.84.0/pact/lib/vendor/ruby/2.2.0/gems/rack-2.1.2/lib/rack/mock.rb:169:in `initialize'
     # ./standalone/linux-x64-1.84.0/pact/lib/vendor/ruby/2.2.0/gems/rack-test-1.1.0/lib/rack/mock_session.rb:31:in `new'
     # ./standalone/linux-x64-1.84.0/pact/lib/vendor/ruby/2.2.0/gems/rack-test-1.1.0/lib/rack/mock_session.rb:31:in `request'
     # ./standalone/linux-x64-1.84.0/pact/lib/vendor/ruby/2.2.0/gems/rack-test-1.1.0/lib/rack/test.rb:266:in `process_request'
     # ./standalone/linux-x64-1.84.0/pact/lib/vendor/ruby/2.2.0/gems/rack-test-1.1.0/lib/rack/test.rb:129:in `custom_request'
     # ./standalone/linux-x64-1.84.0/pact/lib/vendor/ruby/2.2.0/gems/rack-test-1.1.0/lib/rack/test.rb:58:in `get'
     # ./standalone/linux-x64-1.84.0/pact/lib/vendor/ruby/2.2.0/gems/pact-1.49.3/lib/pact/provider/test_methods.rb:24:in `replay_interaction'
     # ./standalone/linux-x64-1.84.0/pact/lib/vendor/ruby/2.2.0/gems/pact-1.49.3/lib/pact/provider/rspec.rb:98:in `block (3 levels) in describe_interaction'
     # ./standalone/linux-x64-1.84.0/pact/lib/vendor/ruby/2.2.0/gems/pact-1.49.3/lib/pact/provider/rspec.rb:214:in `run_once'
     # ./standalone/linux-x64-1.84.0/pact/lib/vendor/ruby/2.2.0/gems/pact-1.49.3/lib/pact/provider/rspec.rb:95:in `block (2 levels) in describe_interaction'
     # ./standalone/linux-x64-1.84.0/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.9.1/lib/rspec/core/example.rb:450:in `instance_exec'
     # ./standalone/linux-x64-1.84.0/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.9.1/lib/rspec/core/example.rb:450:in `instance_exec'
     # ./standalone/linux-x64-1.84.0/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.9.1/lib/rspec/core/hooks.rb:356:in `run'
     # ./standalone/linux-x64-1.84.0/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.9.1/lib/rspec/core/hooks.rb:515:in `block in run_owned_hooks_for'
     # ./standalone/linux-x64-1.84.0/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.9.1/lib/rspec/core/hooks.rb:514:in `each'
     # ./standalone/linux-x64-1.84.0/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.9.1/lib/rspec/core/hooks.rb:514:in `run_owned_hooks_for'
     # ./standalone/linux-x64-1.84.0/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.9.1/lib/rspec/core/hooks.rb:601:in `block in run_example_hooks_for'
     # ./standalone/linux-x64-1.84.0/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.9.1/lib/rspec/core/hooks.rb:600:in `reverse_each'
     # ./standalone/linux-x64-1.84.0/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.9.1/lib/rspec/core/hooks.rb:600:in `run_example_hooks_for'
     # ./standalone/linux-x64-1.84.0/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.9.1/lib/rspec/core/hooks.rb:470:in `run'
     # ./standalone/linux-x64-1.84.0/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.9.1/lib/rspec/core/example.rb:497:in `run_before_example'
     # ./standalone/linux-x64-1.84.0/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.9.1/lib/rspec/core/example.rb:256:in `block in run'
     # ./standalone/linux-x64-1.84.0/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.9.1/lib/rspec/core/example.rb:503:in `block in with_around_and_singleton_context_hooks'
     # ./standalone/linux-x64-1.84.0/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.9.1/lib/rspec/core/example.rb:460:in `block in with_around_example_hooks'
     # ./standalone/linux-x64-1.84.0/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.9.1/lib/rspec/core/hooks.rb:472:in `block in run'
     # ./standalone/linux-x64-1.84.0/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.9.1/lib/rspec/core/hooks.rb:610:in `run_around_example_hooks_for'
     # ./standalone/linux-x64-1.84.0/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.9.1/lib/rspec/core/hooks.rb:472:in `run'
     # ./standalone/linux-x64-1.84.0/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.9.1/lib/rspec/core/example.rb:460:in `with_around_example_hooks'
     # ./standalone/linux-x64-1.84.0/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.9.1/lib/rspec/core/example.rb:503:in `with_around_and_singleton_context_hooks'
     # ./standalone/linux-x64-1.84.0/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.9.1/lib/rspec/core/example.rb:254:in `run'
     # ./standalone/linux-x64-1.84.0/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.9.1/lib/rspec/core/example_group.rb:633:in `block in run_examples'
     # ./standalone/linux-x64-1.84.0/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.9.1/lib/rspec/core/example_group.rb:629:in `map'
     # ./standalone/linux-x64-1.84.0/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.9.1/lib/rspec/core/example_group.rb:629:in `run_examples'
     # ./standalone/linux-x64-1.84.0/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.9.1/lib/rspec/core/example_group.rb:595:in `run'
     # ./standalone/linux-x64-1.84.0/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.9.1/lib/rspec/core/example_group.rb:596:in `block in run'
     # ./standalone/linux-x64-1.84.0/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.9.1/lib/rspec/core/example_group.rb:596:in `map'
     # ./standalone/linux-x64-1.84.0/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.9.1/lib/rspec/core/example_group.rb:596:in `run'
     # ./standalone/linux-x64-1.84.0/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.9.1/lib/rspec/core/example_group.rb:596:in `block in run'
     # ./standalone/linux-x64-1.84.0/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.9.1/lib/rspec/core/example_group.rb:596:in `map'
     # ./standalone/linux-x64-1.84.0/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.9.1/lib/rspec/core/example_group.rb:596:in `run'
     # ./standalone/linux-x64-1.84.0/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.9.1/lib/rspec/core/example_group.rb:596:in `block in run'
     # ./standalone/linux-x64-1.84.0/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.9.1/lib/rspec/core/example_group.rb:596:in `map'
     # ./standalone/linux-x64-1.84.0/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.9.1/lib/rspec/core/example_group.rb:596:in `run'
     # ./standalone/linux-x64-1.84.0/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.9.1/lib/rspec/core/example_group.rb:596:in `block in run'
     # ./standalone/linux-x64-1.84.0/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.9.1/lib/rspec/core/example_group.rb:596:in `map'
     # ./standalone/linux-x64-1.84.0/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.9.1/lib/rspec/core/example_group.rb:596:in `run'
     # ./standalone/linux-x64-1.84.0/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.9.1/lib/rspec/core/runner.rb:121:in `block (3 levels) in run_specs'
     # ./standalone/linux-x64-1.84.0/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.9.1/lib/rspec/core/runner.rb:121:in `map'
     # ./standalone/linux-x64-1.84.0/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.9.1/lib/rspec/core/runner.rb:121:in `block (2 levels) in run_specs'
     # ./standalone/linux-x64-1.84.0/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.9.1/lib/rspec/core/configuration.rb:2031:in `with_suite_hooks'
     # ./standalone/linux-x64-1.84.0/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.9.1/lib/rspec/core/runner.rb:116:in `block in run_specs'
     # ./standalone/linux-x64-1.84.0/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.9.1/lib/rspec/core/reporter.rb:74:in `report'
     # ./standalone/linux-x64-1.84.0/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.9.1/lib/rspec/core/runner.rb:115:in `run_specs'
     # ./standalone/linux-x64-1.84.0/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.9.1/lib/rspec/core/runner.rb:89:in `run'
     # ./standalone/linux-x64-1.84.0/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.9.1/lib/rspec/core/runner.rb:71:in `run'
     # ./standalone/linux-x64-1.84.0/pact/lib/vendor/ruby/2.2.0/gems/pact-1.49.3/lib/pact/provider/pact_spec_runner.rb:88:in `run_specs'
     # ./standalone/linux-x64-1.84.0/pact/lib/vendor/ruby/2.2.0/gems/pact-1.49.3/lib/pact/provider/pact_spec_runner.rb:34:in `run'
     # ./standalone/linux-x64-1.84.0/pact/lib/vendor/ruby/2.2.0/gems/pact-1.49.3/lib/pact/cli/run_pact_verification.rb:69:in `run_with_pact_uri_object'
     # ./standalone/linux-x64-1.84.0/pact/lib/vendor/ruby/2.2.0/gems/pact-1.49.3/lib/pact/cli/run_pact_verification.rb:50:in `run_specs'
     # ./standalone/linux-x64-1.84.0/pact/lib/vendor/ruby/2.2.0/gems/pact-1.49.3/lib/pact/cli/run_pact_verification.rb:21:in `call'
     # ./standalone/linux-x64-1.84.0/pact/lib/vendor/ruby/2.2.0/gems/pact-1.49.3/lib/pact/cli/run_pact_verification.rb:13:in `call'
     # ./standalone/linux-x64-1.84.0/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.30.1/lib/pact/provider_verifier/app.rb:169:in `verify_pact'
     # ./standalone/linux-x64-1.84.0/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.30.1/lib/pact/provider_verifier/app.rb:43:in `block in call'
     # ./standalone/linux-x64-1.84.0/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.30.1/lib/pact/provider_verifier/app.rb:42:in `collect'
     # ./standalone/linux-x64-1.84.0/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.30.1/lib/pact/provider_verifier/app.rb:42:in `call'
     # ./standalone/linux-x64-1.84.0/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.30.1/lib/pact/provider_verifier/app.rb:34:in `call'
     # ./standalone/linux-x64-1.84.0/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.30.1/lib/pact/provider_verifier/cli/verify.rb:56:in `verify'
     # ./standalone/linux-x64-1.84.0/pact/lib/vendor/ruby/2.2.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
     # ./standalone/linux-x64-1.84.0/pact/lib/vendor/ruby/2.2.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
     # ./standalone/linux-x64-1.84.0/pact/lib/vendor/ruby/2.2.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
     # ./standalone/linux-x64-1.84.0/pact/lib/vendor/ruby/2.2.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
     # ./standalone/linux-x64-1.84.0/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.30.1/lib/pact/provider_verifier/cli/custom_thor.rb:17:in `start'
     # ./standalone/linux-x64-1.84.0/pact/lib/app/pact-provider-verifier.rb:33:in `<main>'
```

**Comment by gvijayakumar-16** [comment]
On a side note, can we have this _BACKTRACE=true_ added to documentation, so that it would be easier to debug for users?

**Comment by mefellows** [comment]
@gvijayakumar-16 this is not a usual debug request. But if it becomes something we should request more often, I'll add to the request issue template.

Have you looked at the code at https://github.com/pact-foundation/pact-js/issues/446#issuecomment-636549664 to see if you can get it working for you? The example above works from end to end.

**Comment by gvijayakumar-16** [comment]
Yes, I did look at the code above and I am trying to reproduce the issue. I ran the example in the code and also pointed to some external sites and it did work.

The api's I am testing are not available outside my organisation's network. So trying to reproduce the issue is a bit difficult.

You can hold/close this issue. If I am able to reproduce the issue, I can reopen this issue or open a new one if its not related. Thanks.

Also, is there any way I can see the request and response the provider tests are making? This will be useful for debugging in my end. 
PS: Tried the req and res of requestFilter, but wanted to know if any other option is available.

**Comment by bethesque** [comment]
This is where the error is being raised.

https://github.com/rack/rack/blob/2.1.2/lib/rack/mock.rb#L242

It looks like it's something to do with your cookie header, not the redirect necessarily.

**Comment by gvijayakumar-16** [comment]
Yes @bethesque looks like that way.

https://github.com/pact-foundation/pact-js/compare/repro/446...gvijayakumar-16:repro/446

I have added the response headers I get as part of the request to the example @mefellows  provided. It gives the same error when you run the provider test.

**Comment by bethesque** [comment]
I can see if updating rack fixes that.

**Comment by mefellows** [comment]
Github not that smart Beth :P

![Screen Shot 2020-06-03 at 10 25 28 am](https://user-images.githubusercontent.com/53900/83582328-94446d80-a584-11ea-9a02-5d0b82370b17.png)

Re-opening until it shows the bug is fixed.

**Comment by mefellows** [comment]
@gvijayakumar-16 `10.9.5` of pact-node is on the way out. Once it's out, you should be able to re-install pact or upgrade pact-node explicitly to get the latest.

**Comment by mefellows** [comment]
@gvijayakumar-16 did this solve your problem? Closing as it's a very old issue and has gone stale. Please re-open if it didn't fix it.
