### ISSUE TITLE
Pact installation fails and throws error in post installation process

### ISSUE THREAD

**Issue by riginoommen** [pact-foundation/pact-js#485]
## Issue Classification

- [x] Bug report

## Bug Report
Installation of pact fails on nodejs specifically on the postinstall process. log are given below.
### Software versions

_NOTE: only applicable for bug reports_

- **OS**: e.g. Mac OSX 10.11.5
- **Consumer Pact library**: e.g. Pact JS v2.6.0
- **Provider Pact library**: e.g. pact-jvm-provider-maven_2.11 v 3.3.8
- **Node Version**: `v10.15.3`

### Issue Checklist

Confirm the following:

- [x] I have upgraded to the latest
- [x] I have created a reproducable git repository (see below) to illuminate the problem
- [x] I have the read the FAQs in the Readme
- [x] I have triple checked, that there are **no unhandled promises** in my code

### Expected behaviour

- Installation to be completed with successul results

### Actual behaviour

Error thwrn on post installation process

### Steps to reproduce

https://github.com/riginoommen/template-graphql-typescript

### Relevant log files
```bash
riginoommen-mac:template-graphql-typescript riginoommen$ npm i -S @pact-foundation/pact@latest

> @pact-foundation/pact-node@10.9.7 postinstall /Users/riginoommen/study/template-graphql-typescript/node_modules/@pact-foundation/pact/node_modules/@pact-foundation/pact-node
> node postinstall.js

Installing Pact Standalone Binary for darwin.
Downloading Pact Standalone Binary v1.85.0 for platform darwin from https://github.com/pact-foundation/pact-ruby-standalone/releases/download/v1.85.0/pact-1.85.0-osx.tar.gz
Please note: we are tracking this download anonymously to gather important usage statistics. To disable tracking, set 'pact_do_not_track: true' in your package.json 'config' section.
Error: Error while installing binary: Postinstalled Failed Unexpectedly: Error downloading binary from https://github.com/pact-foundation/pact-ruby-standalone/releases/download/v1.85.0/pact-1.85.0-osx.tar.gz: Error: Error while installing binary: Error: unable to get local issuer certificate
    at throwError (/Users/riginoommen/study/template-graphql-typescript/node_modules/@pact-foundation/pact/node_modules/@pact-foundation/pact-node/standalone/install.js:29:11)
    at /Users/riginoommen/study/template-graphql-typescript/node_modules/@pact-foundation/pact/node_modules/@pact-foundation/pact-node/standalone/install.js:311:16
    at process._tickCallback (internal/process/next_tick.js:68:7)
npm WARN apollo-cache-control@0.1.1 requires a peer of graphql@0.10.x - 0.13.x but none is installed. You must install peer dependencies yourself.
npm WARN apollo-server-core@1.4.0 requires a peer of graphql@^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0 but none is installed. You must install peer dependencies yourself.
npm WARN apollo-tracing@0.1.4 requires a peer of graphql@0.10.x - 0.13.x but none is installed. You must install peer dependencies yourself.
npm WARN graphql-extensions@0.0.10 requires a peer of graphql@0.10.x - 0.13.x but none is installed. You must install peer dependencies yourself.
npm WARN graphql-playground-middleware-lambda@1.7.12 requires a peer of aws-lambda@^0.1.2 but none is installed. You must install peer dependencies yourself.
npm WARN graphql-subscriptions@0.5.8 requires a peer of graphql@^0.10.5 || ^0.11.3 || ^0.12.0 || ^0.13.0 but none is installed. You must install peer dependencies yourself.
npm WARN jsdom@15.2.1 requires a peer of canvas@^2.5.0 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.2.3 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.2.3 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN template-graphql-typescript@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @pact-foundation/pact-node@10.9.7 postinstall: `node postinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @pact-foundation/pact-node@10.9.7 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/riginoommen/.npm/_logs/2020-07-29T15_32_13_191Z-debug.log
riginoommen-mac:template-graphql-typescript riginoommen$
```

**Comment by mefellows** [comment]
Thanks @riginoommen, although I am unable to reproduce this error and our travis builds are passing (which perform this action). It may be temporary, although I suspect we'd know about it in our community [slack channel](slack.pact.io)

Are you running on a corporate laptop that perhaps doesn't allow downloads via Github this way?

Also see https://github.com/pact-foundation/pact-node#installation if you are behind a proxy and you need to specify certificates etc.
