### ISSUE TITLE
Unable to use matchers for query in interaction

### ISSUE THREAD

**Issue by aelmekeev** [pact-foundation/pact-js#510]
Issue seems to bee introduced in #452.
[Relevant slack thread](https://pact-foundation.slack.com/archives/C9VBGLUM9/p1600680307014400). 

## Issue Classification

- [ ] Feature request
- [x] Bug report

### Software versions

- **OS**: e.g. Mac OSX 10.14.6
- **Consumer Pact library**: Pact JS v ^9.11.0
- **Provider Pact library**: N/A
- **Node Version**: v12.16.2

### Issue Checklist

Confirm the following:

- [x] I have upgraded to the latest
- [x] I have created a reproducable git repository (see below) to illuminate the problem
- [x] I have the read the FAQs in the Readme
- [x] I have triple checked, that there are **no unhandled promises** in my code

### Expected behaviour

We should be able to use matchers for query.

### Actual behaviour

`Query must only contain strings.` is thrown.

### Steps to reproduce

https://github.com/aelmekeev/pact-js/pull/1

* `git checkout pact-js-issue-510`
* `npm install` in root
* `npm run compile` in root
* `cd ./examples/e2e`
* `npm install`
* `npm run test:consumer`

### Relevant log files

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/Users/alex.elmekeev/.nvm/versions/node/v12.16.2/bin/node',
1 verbose cli   '/Users/alex.elmekeev/.nvm/versions/node/v12.16.2/bin/npm',
1 verbose cli   'run',
1 verbose cli   'test:consumer'
1 verbose cli ]
2 info using npm@6.14.4
3 info using node@v12.16.2
4 verbose run-script [ 'pretest:consumer', 'test:consumer', 'posttest:consumer' ]
5 info lifecycle e2e@1.0.0~pretest:consumer: e2e@1.0.0
6 info lifecycle e2e@1.0.0~test:consumer: e2e@1.0.0
7 verbose lifecycle e2e@1.0.0~test:consumer: unsafe-perm in lifecycle true
8 verbose lifecycle e2e@1.0.0~test:consumer: PATH: /Users/alex.elmekeev/.nvm/versions/node/v12.16.2/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/alex.elmekeev/other/pact-js/examples/e2e/node_modules/.bin:/Users/alex.elmekeev/.nix-profile/bin:/Users/alex.elmekeev/.nvm/versions/node/v12.16.2/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/opt/postgresql@9.6/bin:/Users/alex.elmekeev/babylon/tools/git:/Users/alex.elmekeev/babylon/scripts/bin:/Users/alex.elmekeev/Library/Python/3.7/bin
9 verbose lifecycle e2e@1.0.0~test:consumer: CWD: /Users/alex.elmekeev/other/pact-js/examples/e2e
10 silly lifecycle e2e@1.0.0~test:consumer: Args: [ '-c', 'mocha test/consumer.spec.js' ]
11 silly lifecycle e2e@1.0.0~test:consumer: Returned: code: 1  signal: null
12 info lifecycle e2e@1.0.0~test:consumer: Failed to exec test:consumer script
13 verbose stack Error: e2e@1.0.0 test:consumer: `mocha test/consumer.spec.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/alex.elmekeev/.nvm/versions/node/v12.16.2/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:310:20)
13 verbose stack     at ChildProcess.<anonymous> (/Users/alex.elmekeev/.nvm/versions/node/v12.16.2/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:310:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid e2e@1.0.0
15 verbose cwd /Users/alex.elmekeev/other/pact-js/examples/e2e
16 verbose Darwin 18.7.0
17 verbose argv "/Users/alex.elmekeev/.nvm/versions/node/v12.16.2/bin/node" "/Users/alex.elmekeev/.nvm/versions/node/v12.16.2/bin/npm" "run" "test:consumer"
18 verbose node v12.16.2
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error e2e@1.0.0 test:consumer: `mocha test/consumer.spec.js`
22 error Exit status 1
23 error Failed at the e2e@1.0.0 test:consumer script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by mefellows** [comment]
Thanks so much for this, I'll aim to look into this next week at the latest.

**Comment by mefellows** [comment]
My guilt has been building up on a few OSS issues to the point I need to do it right now :)

I've just pushed a fix up for this and tested with the e2e example. If the build passes, I'll merge in and release ASAP.

Thanks for all of your help on the forums of late also!
