### ISSUE TITLE
V3 Branch Breaks with Preflight OPTIONS request

### ISSUE THREAD

**Issue by thomashibbard** [pact-foundation/pact-js#520]
## Issue Classification

- [ ] Feature request
- [x] Bug report

### Software versions

_NOTE: only applicable for bug reports_

- **OS**: e.g. Mac OSX Catalina 10.15.5 (19F101)
- **Consumer Pact library**: e.g. Pact JS `@pact-foundation/pact^10.0.0-beta.19`
- **Provider Pact library**: `au.com.dius:pact-jvm-provider-junit5:4.0.10`
- **Node Version**: `v10.16.0`

### Issue Checklist

Confirm the following:

- [x] I have upgraded to the latest
- [x] I have created a reproducable git repository (see below) to illuminate the problem
- [x] I have the read the FAQs in the Readme
- [x] I have triple checked, that there are **no unhandled promises** in my code

### Expected behaviour

Creates a Pact that accepts an `OPTIONS` preflight and returns the correct body and headers. (`cors` is definitely set to `true` in `PactV3Options`)

### Actual behaviour

Fails because it does not expect `OPTIONS`. Fails because returned body's `headers` object is incorrect.

### Steps to reproduce
1. Go to linked repo
2. `npm install`
3. `npm run pact`
4. see unexpected errors (shown in repo README for reference)

Provide a repository, gist or reproducible code snippet so that we can test the problem.

There are a few more details in this repository's README: https://github.com/thomashibbard/pact-js-beta-preflight-issue

### Relevant log files

`PactV3Options` do not support a logging property as far as I can tell, but there is this error logged to the console:

``` 
console.error
    Error: Headers Authorization,Accept-Version forbidden
        at dispatchError (/Users/thibbard/Desktop/pact-js-beta-preflight-issue/node_modules/jsdom/lib/jsdom/living/xhr/xhr-utils.js:62:19)
        at validCORSPreflightHeaders (/Users/thibbard/Desktop/pact-js-beta-preflight-issue/node_modules/jsdom/lib/jsdom/living/xhr/xhr-utils.js:99:5)
        at Request.preflightClient.on.resp (/Users/thibbard/Desktop/pact-js-beta-preflight-issue/node_modules/jsdom/lib/jsdom/living/xhr/xhr-utils.js:367:12)
        at Request.emit (events.js:198:13)
        at Request.onRequestResponse (/Users/thibbard/Desktop/pact-js-beta-preflight-issue/node_modules/request/request.js:1059:10)
        at ClientRequest.emit (events.js:198:13)
        at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:556:21)
        at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
        at Socket.socketOnData (_http_client.js:442:20)
        at Socket.emit (events.js:198:13) undefined```

**Comment by uglyog** [comment]
Thanks for the example project.

You can change the log level using the `LOG_LEVEL` environment variable. I'll update the docs for that.

I'll see if I can get a fix for this out today.

**Comment by uglyog** [comment]
Looks like it is an issue with jsdom: https://github.com/jsdom/jsdom/pull/2867

I don't know if this comment will help: https://github.com/jsdom/jsdom/issues/2408#issuecomment-562425503

**Comment by uglyog** [comment]
jsdom does not support handling `access-control-allow-headers: *`, which means accept all headers.

I've updated the mock server to return the contents of the `access-control-request-headers` header which seems to now work. For your test, it will now return `access-control-allow-headers: Authorization, Accept-Version, *` and jsdom seems to accept that.

**Comment by uglyog** [comment]
10.0.0-beta.21 has been released with the fix

**Comment by TimothyJones** [comment]
Looks like this is fixed - please feel free to reopen if there are any further issues.
