### ISSUE TITLE
Error executing pact js in github actions

### ISSUE THREAD

**Issue by leonleo997** [pact-foundation/pact-js#644]
Hey there, I'm having issues trying to execute the contract tests in github actions

### Software versions
- **Consumer Pact library**:  Pact JS v9.15.4
- **Node Version**: `12`

### Expected behaviour

Contract tests are being executed in github actions

### Actual behaviour

Github actions is throwing this error:

```js
[2021-04-18 23:58:42.919 +0000] INFO (1937 on fv-az249-415): pact-node@10.12.1: Creating Pact Server with options: 
{"consumer":"Consumer","cors":true,"dir":"/home/runner/work/animal-shelter-ui/animal-shelter-ui/test/contract/pacts","host":"127.0.0.1","log":"/home/runner/work/animal-shelter-ui/animal-shelter-ui/test/contract/logs/pact.log","pactFileWriteMode":"overwrite","port":8080,"provider":"Provider","spec":2,"ssl":false}
[2021-04-18 23:58:43.354 +0000] ERROR (1937 on fv-az249-415): pact-node@10.12.1: Pact Binary Error: /home/runner/work/animal-shelter-ui/animal-shelter-ui/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.88.45/pact/lib/ruby/lib/ruby/gems/2.2.0/gems/bundler-1.9.9/lib/bundler/shared_helpers.rb:78: warning: Insecure world writable dir /opt/hostedtoolcache/node/12.22.1/x64/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin in PATH, mode 040777

[2021-04-18 23:58:43.970 +0000] INFO (1937 on fv-az249-415): pact@9.15.4: Setting up Pact with Consumer "Consumer" and Provider "Provider"
    using mock service on Port: "8080"
  console.error
    Error: Error: connect ECONNREFUSED 127.0.0.1:80
        at Object.dispatchError (/home/runner/work/animal-shelter-ui/animal-shelter-ui/node_modules/jsdom/lib/jsdom/living/xhr/xhr-utils.js:62:19)
        at Request.<anonymous> (/home/runner/work/animal-shelter-ui/animal-shelter-ui/node_modules/jsdom/lib/jsdom/living/xhr/XMLHttpRequest-impl.js:655:18)
        at Request.emit (events.js:326:22)
        at Request.onRequestError (/home/runner/work/animal-shelter-ui/animal-shelter-ui/node_modules/request/request.js:877:8)
        at ClientRequest.emit (events.js:314:20)
        at Socket.socketErrorListener (_http_client.js:427:9)
        at Socket.emit (events.js:314:20)
        at emitErrorNT (internal/streams/destroy.js:92:8)
        at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
        at processTicksAndRejections (internal/process/task_queues.js:84:21) undefined

      at VirtualConsole.<anonymous> (node_modules/jsdom/lib/jsdom/virtual-console.js:29:45)
      at Object.dispatchError (node_modules/jsdom/lib/jsdom/living/xhr/xhr-utils.js:65:53)
      at Request.<anonymous> (node_modules/jsdom/lib/jsdom/living/xhr/XMLHttpRequest-impl.js:655:18)
      at Request.onRequestError (node_modules/request/request.js:877:8)

  console.error


      at node_modules/@pact-foundation/src/httpPact.ts:121:17

  console.error
    Pact verification failed!

      at node_modules/@pact-foundation/src/httpPact.ts:122:17

  console.error
    Actual interactions do not match expected interactions for mock MockService.
    
    Missing requests:
    	GET /animals
    
    
    See /home/runner/work/animal-shelter-ui/animal-shelter-ui/test/contract/logs/pact.log for details.
    

      at node_modules/@pact-foundation/src/httpPact.ts:123:17

FAIL test/contract/specs/list-animal.test.js
  Animal Service
    When a request to list all animals is made
      ✕ should return the correct data (94 ms)

  ● Animal Service › When a request to list all animals is made › should return the correct data

    Network Error

      at createError (node_modules/axios/lib/core/createError.js:16:15)
      at XMLHttpRequest.handleError (node_modules/axios/lib/adapters/xhr.js:84:14)
      at XMLHttpRequest.invokeTheCallbackFunction (node_modules/jsdom/lib/jsdom/living/generated/EventHandlerNonNull.js:18:28)
      at XMLHttpRequest.<anonymous> (node_modules/jsdom/lib/jsdom/living/helpers/create-event-accessor.js:35:32)
      at innerInvokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:338:25)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
      at XMLHttpRequestImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
      at fireAnEvent (node_modules/jsdom/lib/jsdom/living/helpers/events.js:18:36)
      at requestErrorSteps (node_modules/jsdom/lib/jsdom/living/xhr/xhr-utils.js:128:3)
      at Object.dispatchError (node_modules/jsdom/lib/jsdom/living/xhr/xhr-utils.js:59:3)
      at Request.<anonymous> (node_modules/jsdom/lib/jsdom/living/xhr/XMLHttpRequest-impl.js:655:18)
      at Request.onRequestError (node_modules/request/request.js:877:8)

  ● Animal Service › When a request to list all animals is made › should return the correct data

    Pact verification failed - expected interactions did not match actual.

      at new VerificationError (node_modules/@pact-foundation/pact/src/errors/verificationError.js:19:42)
      at node_modules/@pact-foundation/src/httpPact.ts:127:17

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        3.988 s
Ran all test suites matching /.\/test\/contract\//i.
[2021-04-18 23:58:44.074 +0000] INFO (1937 on fv-az249-415): pact@9.15.4: Pact File Written
[2021-04-18 23:58:44.075 +0000] INFO (1937 on fv-az249-415): pact-node@10.12.1: Removing Pact process with PID: 1953
[2021-04-18 23:58:44.076 +0000] INFO (1937 on fv-az249-415): pact-node@10.12.1: Deleting Pact Server with options: 
{"consumer":"Consumer","cors":true,"dir":"/home/runner/work/animal-shelter-ui/animal-shelter-ui/test/contract/pacts","host":"127.0.0.1","log":"/home/runner/work/animal-shelter-ui/animal-shelter-ui/test/contract/logs/pact.log","pactFileWriteMode":"overwrite","port":8080,"provider":"Provider","spec":2,"ssl":false}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! animal-shelter-ui@0.1.0 test:contract: `jest --testPathPattern=./test/contract/ --runInBand`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the animal-shelter-ui@0.1.0 test:contract script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-04-18T23_58_44_215Z-debug.log
Error: Process completed with exit code 1.
```

### Steps to reproduce

create a pull request or send a commit to a branch

**Comment by leonleo997** [comment]
FYI: This is my repo  https://github.com/leonleo997/animal-shelter-ui
This is the log of the fail: https://github.com/leonleo997/animal-shelter-ui/pull/10/checks?check_run_id=2376536693

**Comment by TimothyJones** [comment]
I don't think this is a pact problem (we ran our builds and releases for those versions from github actions).

The error suggests that you're starting pact on `:8080`, but trying to connect to `:80`. Is there something in your code that needs to be changed?

**Comment by TimothyJones** [comment]
I couldn't find the pact test in your repo: https://github.com/leonleo997/animal-shelter-ui/search?q=pact

Make sure that you are getting your client to connect to the pact mock during the pact test.

If you believe it is still a pact problem, can you produce a minimal example, please?

**Comment by mefellows** [comment]
I think this is the test here https://github.com/leonleo997/animal-shelter-ui/blob/test/contract-tests-setup/test/contract/specs/list-animal.test.js (in a branch).

And based on https://github.com/leonleo997/animal-shelter-ui/blob/test/contract-tests-setup/controllers/AnimalsController.js it should be using the `API` env var as a base url, so perhaps that's being set incorrectly?

**Comment by leonleo997** [comment]
yes, the problem about the non connection was another issue (my bad because I didn't set the env var but it is done). However, I'm getting like a warning. This is the warning:

```bash
[2021-04-19 00:20:37.766 +0000] ERROR (1910 on fv-az121-302): pact-node@10.12.1: Pact Binary Error: /home/runner/work/animal-shelter-ui/animal-shelter-ui/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.88.45/pact/lib/ruby/lib/ruby/gems/2.2.0/gems/bundler-1.9.9/lib/bundler/shared_helpers.rb:78: warning: Insecure world writable dir /opt/hostedtoolcache/node/12.22.1/x64/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin in PATH, mode 040777
```

This is the link of the build (open the run contract tests stage)

**Comment by mefellows** [comment]
That warning can be ignored. It relates to the way GH sets permissions on that directory, and the Ruby runtime warns because it's, well, world writeable. It's not an actual problem though - is there an actual problem with the build?

**Comment by leonleo997** [comment]
nope, the build is okay, thank you for your help!

**Comment by mefellows** [comment]
Great to hear!
