### ISSUE TITLE
VerifierV3 doesn't work with SSL_CERT_FILE

### ISSUE THREAD

**Issue by tugtugtug** [pact-foundation/pact-js#736]
### Software versions

- **OS**: Ubuntu 20.04
- **Consumer Pact library**: @pact-foundation/pact 10.0.0-beta.44
- **Provider Pact library**: @pact-foundation/pact 10.0.0-beta.44
- **Node Version**: v14.17.6

### Issue Checklist

Please confirm the following:

- [x] I have upgraded to the latest
- [x] I have the read the FAQs in the Readme
- [x] I have triple checked, that there are **no unhandled promises** in my code and have [read](https://github.com/pact-foundation/pact-js/#test-fails-when-it-should-pass) the section on intermittent test failures
- [x] I have set my log level to debug and attached a log file showing the complete request/response cycle
- [ ] For bonus points and virtual high fives, I have created a reproduceable git repository (see below) to illustrate the problem

### Expected behaviour
VerifierV3 should support similar ways to configure the SSL certificate as the current version of the Verifier. i.e. allowing specifying SSL_CERT_FILE env variable.

The reason we switched to the V3 is because the Verifier in the 10.0 branch doesn't seem to be regularly tested, and doesn't even work with setupStates. This could be another bug.
```
[2021-09-14 01:19:11.082 +0000] DEBUG (740119 on ci0700000004610): pact@10.0.0-beta.44: setting up state
    state: {
      "consumer": "abc@Test",
      "state": "Has some tenants",
      "states": [
        "Has some tenants"
      ],
      "params": {}
    }
[2021-09-14 01:19:11.082 +0000] DEBUG (740119 on ci0700000004610): pact@10.0.0-beta.44: unknown state action 'undefined' received, ignoring
```

### Workaround
One workaround for this is SSL issue is to create a plain http localhost proxy for this verifier.

### Actual behaviour
SSL_CERT_FILE has no effect.

### Steps to reproduce
Configure the VerifierV3 to a locally hosted broker with a self-signed cert and run verifyProvider.

### Relevant log files
```
  Pact Verification
Restful Restful Server listening on port 0
[HPM] Proxy created: /  -> https://abc.intranet.net
[2021-09-14 01:02:45.311 +0000] INFO (736596 on ci0700000004610): pact@10.0.0-beta.44: debug request/response logging enabled
[2021-09-14 01:02:45.314 +0000] TRACE (736596 on ci0700000004610): pact@10.0.0-beta.44: submitted test to verify_provider
[2021-09-14T01:02:45Z ERROR pact_verifier] Failed to load pact - Could not load pacts from the pact broker 'https://abc.intranet.net' - IoError("Failed to access pact broker path '/' - error sending request for url (https://abc.intranet.net/): error trying to connect: invalid certificate: UnknownIssuer. URL: 'https://abc.intranet.net'")

Failures:

1) Failed to load pact - Could not load pacts from the pact broker 'https://abc.intranet.net - IoError("Failed to access pact broker path '/' - error sending request for url (https://abc.intranet.net/): error trying to connect: invalid certificate: UnknownIssuer. URL: 'https://abc.intranet.net'")


There were 1 pact failures

[2021-09-14 01:02:45.489 +0000] TRACE (736596 on ci0700000004610): pact@10.0.0-beta.44: verification failed
    val: false
    err: null
    1) validates the expectations of Matching Service
Restful Restful Server shutdown on port 0
```

**Comment by mefellows** [comment]
Thanks @tugtugtug, yes, this env var will not work. Marking this as a feature enhancement for this version.

**Comment by TimothyJones** [comment]
Just to note - the verifier has had a substantial update in `@pact-foundation/pact 10.0.0-beta.45` (although I suspect the SSL_CERT_FILE still isn't respected).

**Comment by mefellows** [comment]
There is this flag that is available Tim that we should consider exposing `--disable-ssl-verification` (but doesn't solve the problem of caring about self-signed certificates, of course).

_<insert snarky comments about the use of self-signed certificates in the age of Let's Encrypt... />_

**Comment by mefellows** [comment]
It looks like the underlying client library does support this: https://docs.rs/reqwest/0.11.4/reqwest/struct.ClientBuilder.html#method.add_root_certificate. We should add that ability too.

Wondering if we should preserve the use of that env var Tim and/or provide an explicit option in the `PactV3` interface?

**Comment by TimothyJones** [comment]
We do support disabling of SSL - it's `disableSSLVerification` if importing from `/v3` or `disableSslVerification` if using the `Verifier` import after beta 45.

**Comment by TimothyJones** [comment]
`SSL_CERT_FILE`  is pretty standard - it's what OpenSSL will look for. I'm a bit surprised this doesn't just work by default, but perhaps the rust core doesn't use OpenSSL.

**Comment by tugtugtug** [comment]
Thanks folks, I did try upgrading to beta45 + 46, but I'm getting some dependency issues. I tried to install neon-cli, rust and other things, but issue remains.
```
npm ERR! path /test/node_modules/@pact-foundation/pact
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install --fallback-to-build=false || neon build --release
npm ERR! response status 404 Not Found on https://github.com/pact-foundation/pact-js/releases/download/v10.0.0-beta.46/node-v83-linux-x64-glibc.tar.gz
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@1.0.5
npm ERR! node-pre-gyp info using node@14.17.6 | linux | x64
npm ERR! node-pre-gyp info check checked for "/test/node_modules/@pact-foundation/pact/native/index.node" (not found)
npm ERR! node-pre-gyp http GET https://github.com/pact-foundation/pact-js/releases/download/v10.0.0-beta.46/node-v83-linux-x64-glibc.tar.gz
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/pact-foundation/pact-js/releases/download/v10.0.0-beta.46/node-v83-linux-x64-glibc.tar.gz 
npm ERR! node-pre-gyp ERR! install error 
npm ERR! node-pre-gyp ERR! stack Error: response status 404 Not Found on https://github.com/pact-foundation/pact-js/releases/download/v10.0.0-beta.46/node-v83-linux-x64-glibc.tar.gz
npm ERR! node-pre-gyp ERR! stack     at /test/node_modules/@mapbox/node-pre-gyp/lib/install.js:67:15
npm ERR! node-pre-gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:95:5)
npm ERR! node-pre-gyp ERR! System Linux 5.4.0-81-generic
npm ERR! node-pre-gyp ERR! command "/usr/bin/node" "/test/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build=false"
npm ERR! node-pre-gyp ERR! cwd /test/node_modules/@pact-foundation/pact
npm ERR! node-pre-gyp ERR! node -v v14.17.6
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.5
npm ERR! node-pre-gyp ERR! not ok 
npm ERR! neon ERR! Command failed: cargo metadata --format-version=1 --no-deps
npm ERR! error: could not find `Cargo.toml` in `/test/node_modules/@pact-foundation/pact/native` or any parent directory
npm ERR! 
npm ERR! 
npm ERR! Error: Command failed: cargo metadata --format-version=1 --no-deps
npm ERR! error: could not find `Cargo.toml` in `/test/node_modules/@pact-foundation/pact/native` or any parent directory
npm ERR! 
npm ERR!     at ChildProcess.exithandler (child_process.js:390:12)
npm ERR!     at ChildProcess.emit (events.js:400:28)
npm ERR!     at maybeClose (internal/child_process.js:1055:16)
npm ERR!     at Socket.<anonymous> (internal/child_process.js:441:11)
npm ERR!     at Socket.emit (events.js:400:28)
npm ERR!     at Pipe.<anonymous> (net.js:675:12)
```

**Comment by TimothyJones** [comment]
Apologies, beta-46 is currently broken (see #737). 45 should work fine, though. Did you get the same error with 45?

**Comment by tugtugtug** [comment]
> We do support disabling of SSL - it's `disableSSLVerification` if importing from `/v3` or `disableSslVerification` if using the `Verifier` import after beta 45.

@TimothyJones I did try beta-45, which does indeed compile, but I thought `disableSSLVerification` works only after beta-45 (I tried 45 and it didn't have any effect with beta-45). I guess I need to wait for the next working beta?

Got this with beta-45, Verifier.
```
[2021-09-14T13:00:31Z WARN  rustls::session] Sending fatal alert BadCertificate
```

**Comment by TimothyJones** [comment]
`disableSSLVerification` should work before beta-45. I'm not sure when it was introduced exactly.

From beta-45 onwards:

* You no longer need to import the verifier from `@pact-foundation/pact/v3` (but you can continue to do so)
* The option was renamed to `disableSslVerification` (note change to camelcase to make it consistent with the rest of the options)
*  If you are using beta-45 or later, and importing from `@pact-foundation/pact/v3`, then both `disableSslVerification` and `disableSSLVerification` should work

**Comment by TimothyJones** [comment]
I've started to construct a migration guide here, which hopefully makes things a bit clearer: https://github.com/pact-foundation/pact-js/blob/feat/v3.0.0/MIGRATION.md

We're fighting an unrelated problem which is currently blocking beta releases at the moment.

**Comment by tugtugtug** [comment]
ah got it, tried again, I'm testing `Verifier` imported from `@pact-foundation/pact`  with `beta-45` and have both of the following options set
```
			disableSslVerification: true,
			disableSslVerification: true,
```
I can see in the debug log
```
[2021-09-14 13:19:13.401 +0000] TRACE (869089 on ci0700000004610): pact@10.0.0-beta.45: Verifying pacts with: {"providerStatesSetupUrl":"http://localhost:42469/_pactSetup","validateSSL":false,"provider":"test@Test","providerBaseUrl":"http://localhost:42469","stateHandlers":{},"pactBrokerUrl":"https://test.intranet.net","consumerVersionTags":["branch/master"],"providerVersionTags":["branch/master"],"consumerVersionSelectors":[],"enablePending":true,"publishVerificationResult":false,"providerVersion":"1.0.0","logLevel":"trace","disableSslVerification":true,"changeOrigin":false}

[2021-09-14 13:19:13.480 +0000] DEBUG (869089 on ci0700000004610): pact-core@13.1.5: --request-timeout
30000
--loglevel
trace
--state-change-url
http://localhost:42469/_pactSetup
--provider-name
test@Test
--port
42469
--hostname
localhost
--broker-url
https://test.interanet.net
--consumer-version-tags
branch/master
--provider-tags
branch/master
--enable-pending
--provider-version
1.0.0
--disable-ssl-verification
```
and later rustls complains
```
[2021-09-14T13:19:13Z WARN  rustls::session] Sending fatal alert BadCertificate
```
Maybe setting this is not enough to get self-signed cert to work? i.e. we still need to pass the CA file into the tls engine?

**Comment by TimothyJones** [comment]
To be clear, both of these should work in beta-45 (using any pact spec version):

```
import { Verifier } from '@pact-foundation/pact';

new Verifier({ disableSslVerification: true, /* ... your other options here*/ });
```
or

```
import { VerifierV3 } from '@pact-foundation/pact/v3';

new VerifierV3({ disableSSLVerification: true, /* ... your other options here*/ });
```

If they don't disable SSL, then that's a bug.

**Comment by TimothyJones** [comment]
Ah, our messages crossed.

@uglyog : Are we invoking the rust verifier incorrectly, or is there a bug in the way `--disable-ssl-verification` works?

**Comment by tugtugtug** [comment]
> To be clear, both of these should work in beta-45 (using any pact spec version):
> 
> ```
> import { Verifier } from '@pact-foundation/pact';
> 
> new Verifier({ disableSslVerification: true, /* ... your other options here*/ });
> ```
> 
> or
> 
> ```
> import { VerifierV3 } from '@pact-foundation/pact/v3';
> 
> new VerifierV3({ disableSSLVerification: true, /* ... your other options here*/ });
> ```
> 
> If they don't disable SSL, then that's a bug.

I'm currently testing the former, pretty sure the argument `--disable-ssl-verification` is passed to

**Comment by tugtugtug** [comment]
Sorry clicked on the wrong button, github really should have a prompt before closing the issue...

**Comment by mefellows** [comment]
> `SSL_CERT_FILE` is pretty standard - it's what OpenSSL will look for. I'm a bit surprised this doesn't just work by default, but perhaps the rust core doesn't use OpenSSL.

It doesn't use OpenSSL. I can't recall the exact reason, but I think to do with portability (probably Alpine?). It uses a native Rust TLS module.

Digging a little further, there is an open [issue](https://github.com/rustls/rustls/issues/540) for that. It seems like it may be supported already and that it currently looks in the following directories file certs:

```
/var/ssl
/usr/share/ssl
/usr/local/ssl
/usr/local/openssl
/usr/local/etc/openssl
/usr/local/share
/usr/lib/ssl
/usr/ssl
/etc/openssl
/etc/pki/ca-trust/extracted/pem
/etc/pki/tls
/etc/ssl
/data/data/com.termux/files/usr/etc/tls
/boot/system/data/ssl
```

for these files:
```
cert.pem
certs.pem
ca-bundle.pem
certs/ca-certificates.crt
certs/ca-root-nss.crt
certs/ca-bundle.crt
CARootCertificates.pem
tls-ca-bundle.pem
```

It also mentions some exceptions for Mac/Windows, but I'd be keen to see the results of any tests.

This all being said, disabling should work, so something has gone awry there.

**Comment by mefellows** [comment]
OK, regarding self-signed certificate. The underlying CLI definitely accepts a self-signed certificate. The pact failures are expected, but you can see that with `--disable-ssl-verification` it ignores the bad cert:

```
➜  pact_verifier_cli git:(master) ✗ ../target/debug/pact_verifier_cli --port 443 --hostname self-signed.badssl.com --scheme https --file ~/development/public/pact-js/examples/e2e/pacts/e2e_consumer_example-e2e_provider_example.json --disable-ssl-verification                                          <aws:pact-prod>

Verifying a pact between e2e Consumer Example and e2e Provider Example
  Given is not authenticated
    WARNING: State Change ignored as there is no state change URL provided
  Given Has some animals
    WARNING: State Change ignored as there is no state change URL provided
  Given Has an animal with ID 1
    WARNING: State Change ignored as there is no state change URL provided
  Given Has no animals
    WARNING: State Change ignored as there is no state change URL provided
  a request for all animals
    returns a response which
      has status code 401 (FAILED)
      includes headers
      has a matching body (OK)
  a request for all animals
    returns a response which
      has status code 200 (FAILED)
      includes headers
        "Content-Type" with value "application/json; charset=utf-8" (FAILED)
      has a matching body (FAILED)
  a request for an animal with ID 1
    returns a response which
      has status code 200 (FAILED)
      includes headers
        "Content-Type" with value "application/json; charset=utf-8" (FAILED)
      has a matching body (FAILED)
  a request for an animal with ID 100
    returns a response which
      has status code 404 (OK)
      includes headers
      has a matching body (OK)
  a request to create a new mate
    returns a response which
      has status code 200 (FAILED)
      includes headers
        "Content-Type" with value "application/json; charset=utf-8" (FAILED)
      has a matching body (FAILED)


Failures:

1) Verifying a pact between e2e Consumer Example and e2e Provider Example Given is not authenticated - a request for all animals
    1.1) has status code 401
           expected 401 but was 404
2) Verifying a pact between e2e Consumer Example and e2e Provider Example Given Has some animals - a request for all animals
    2.1) has a matching body
           expected 'application/json;charset=utf-8' body but was 'text/html'
    2.2) has status code 200
           expected 200 but was 404
    2.3) includes header 'Content-Type' with value 'application/json; charset=utf-8'
           Expected header 'Content-Type' to have value 'application/json; charset=utf-8' but was 'text/html'
3) Verifying a pact between e2e Consumer Example and e2e Provider Example Given Has an animal with ID 1 - a request for an animal with ID 1
    3.1) has a matching body
           expected 'application/json;charset=utf-8' body but was 'text/html'
    3.2) has status code 200
           expected 200 but was 404
    3.3) includes header 'Content-Type' with value 'application/json; charset=utf-8'
           Expected header 'Content-Type' to have value 'application/json; charset=utf-8' but was 'text/html'
4) Verifying a pact between e2e Consumer Example and e2e Provider Example - a request to create a new mate
    4.1) has a matching body
           expected 'application/json;charset=utf-8' body but was 'text/html'
    4.2) has status code 200
           expected 200 but was 404
    4.3) includes header 'Content-Type' with value 'application/json; charset=utf-8'
           Expected header 'Content-Type' to have value 'application/json; charset=utf-8' but was 'text/html'

There were 4 pact failures

➜  pact_verifier_cli git:(master) ✗ ../target/debug/pact_verifier_cli --port 443 --hostname self-signed.badssl.com --scheme https --file ~/development/public/pact-js/examples/e2e/pacts/e2e_consumer_example-e2e_provider_example.json                                                                     <aws:pact-prod>

Verifying a pact between e2e Consumer Example and e2e Provider Example
  Given is not authenticated
    WARNING: State Change ignored as there is no state change URL provided
12:11:45 [WARN] Sending fatal alert BadCertificate
  Given Has some animals
    WARNING: State Change ignored as there is no state change URL provided
12:11:45 [WARN] Sending fatal alert BadCertificate
  Given Has an animal with ID 1
    WARNING: State Change ignored as there is no state change URL provided
12:11:46 [WARN] Sending fatal alert BadCertificate
  Given Has no animals
    WARNING: State Change ignored as there is no state change URL provided
12:11:46 [WARN] Sending fatal alert BadCertificate
12:11:47 [WARN] Sending fatal alert BadCertificate
  a request for all animals
      Request Failed - Invalid response: error sending request for url (https://self-signed.badssl.com/animals/available): error trying to connect: invalid certificate: UnknownIssuer
  a request for all animals
      Request Failed - Invalid response: error sending request for url (https://self-signed.badssl.com/animals/available): error trying to connect: invalid certificate: UnknownIssuer
  a request for an animal with ID 1
      Request Failed - Invalid response: error sending request for url (https://self-signed.badssl.com/animals/1): error trying to connect: invalid certificate: UnknownIssuer
  a request for an animal with ID 100
      Request Failed - Invalid response: error sending request for url (https://self-signed.badssl.com/animals/100): error trying to connect: invalid certificate: UnknownIssuer
  a request to create a new mate
      Request Failed - Invalid response: error sending request for url (https://self-signed.badssl.com/animals): error trying to connect: invalid certificate: UnknownIssuer


Failures:

1) Verifying a pact between e2e Consumer Example and e2e Provider Example Given is not authenticated - a request for all animals - Invalid response: error sending request for url (https://self-signed.badssl.com/animals/available): error trying to connect: invalid certificate: UnknownIssuer

2) Verifying a pact between e2e Consumer Example and e2e Provider Example Given Has some animals - a request for all animals - Invalid response: error sending request for url (https://self-signed.badssl.com/animals/available): error trying to connect: invalid certificate: UnknownIssuer

3) Verifying a pact between e2e Consumer Example and e2e Provider Example Given Has an animal with ID 1 - a request for an animal with ID 1 - Invalid response: error sending request for url (https://self-signed.badssl.com/animals/1): error trying to connect: invalid certificate: UnknownIssuer

4) Verifying a pact between e2e Consumer Example and e2e Provider Example Given Has no animals - a request for an animal with ID 100 - Invalid response: error sending request for url (https://self-signed.badssl.com/animals/100): error trying to connect: invalid certificate: UnknownIssuer

5) Verifying a pact between e2e Consumer Example and e2e Provider Example - a request to create a new mate - Invalid response: error sending request for url (https://self-signed.badssl.com/animals): error trying to connect: invalid certificate: UnknownIssuer


There were 5 pact failures
```

**Comment by mefellows** [comment]
Ah! The failure is in the communication to the Pact Broker, not to the target. This needs to be supported in rust (I just checked).

**Comment by mefellows** [comment]
OK, so an update on this. https://github.com/pact-foundation/pact-reference/pull/149 has been merged and we'll get a new FFI release out soon, which will enable platform specific support for ssl configuration.

This will support the open SSL env vars for platforms that use it (e.g. Linux), and also allow the importing into Windows/Mac keystores.

**Comment by TimothyJones** [comment]
Awesome! @mefellows  - I'll put a ticket on the V3 project board for hooking up the builds so that the FFI is auto-released and a PR made to pact-js-core (like the Ruby binaries have).

**Comment by tugtugtug** [comment]
Thanks a lot @TimothyJones, we just upgraded to `pact-10.0.0-beta.54` and the verifier worked as expected now.
