### ISSUE TITLE
pact-node@10.14.0: Pact Binary Error when trying to run a test

### ISSUE THREAD

**Issue by erickbelfy** [pact-foundation/pact-js#766]
I had an issue while trying to setup Pact provider when i try to run my tests here it follows

### Software versions

_Please provide at least OS and version of pact-js_

- **OS**: _e.g. Mac OSX 10.11.5_
- **Pact Node version**:  `10.14.0`
- **Node Version**: `v16.11.1`
- **Other Versions**: _Any other versions you think might be relevant (optional)_
```
   "@pact-foundation/pact": "^9.16.5",
    "@pact-foundation/pact-mock-service": "^2.1.0",
    "@pact-foundation/pact-node": "^10.14.0",
```
### Issue Checklist

Please confirm the following:

- [x] I have upgraded to the latest
- [ ] I have the read the FAQs in the Readme
- [ ] I have triple checked, that there are **no unhandled promises** in my code
- [ ] I have set my log level to debug and attached a log file showing the complete request/response cycle
- [ ] For bonus points and virtual high fives, I have created a reproduceable git repository (see below) to illustrate the problem

### Expected behaviour
It should create a server that runs the Pact provider and test all the cases

### Actual behaviour
it gives me the error below:

```
[2021-11-04 15:02:50.945 +0000] INFO (97114 on MAC-CA-BELFOER2): pact-node@10.14.0: Creating Pact Server with options:
{"consumer":"customer-signup-gateway-consumer","cors":true,"dir":"/Users/belfoer1/Documents/oss-ui/packages/apps/signup/server/pact/pacts","host":"127.0.0.1","log":"/Users/belfoer1/Documents/oss-ui/packages/apps/signup/server/pact/logs","pactFileWriteMode":"update","port":3000,"provider":"customer-sign-up","spec":2,"ssl":false,"timeout":30000}
[2021-11-04 15:02:51.720 +0000] ERROR (97114 on MAC-CA-BELFOER2): pact-node@10.14.0: Pact Binary Error: /Users/belfoer1/Documents/oss-ui/node_modules/@pact-foundation/pact-node/standalone/darwin-1.88.77/pact/lib/ruby/lib/ruby/gems/2.2.0/gems/bundler-1.9.9/lib/bundler/shared_helpers.rb:78: warning: Insecure world writable dir /Users/belfoer1/Library/Android in PATH, mode 040777

[2021-11-04 15:02:52.066 +0000] ERROR (97114 on MAC-CA-BELFOER2): pact-node@10.14.0: Pact Binary Error: /Users/belfoer1/Documents/oss-ui/node_modules/@pact-foundation/pact-node/standalone/darwin-1.88.77/pact/lib/vendor/ruby/2.2.0/gems/pact-mock_service-3.9.0/lib/pact/mock_service/run.rb:75:in `initialize': Is a directory @ rb_sysopen - /Users/belfoer1/Documents/oss-ui/packages/apps/signup/server/pact/logs (Errno::EISDIR)
	from /Users/belfoer1/Documents/oss-ui/node_modules/@pact-foundation/pact-node/standalone/darwin-1.88.77/pact/lib/vendor/ruby/2.2.0/gems/pact-mock_service-3.9.0/lib/pact/mock_service/run.rb:75:in `open'
	from /Users/belfoer1/Documents/oss-ui/node_modules/@pact-foundation/pact-node/standalone/darwin-1.88.77/pact/lib/vendor/ruby/2.2.0/gems/pact-mock_service-3.9.0/lib/pact/mock_service/run.rb:75:in `open_log_file'
	from /Users/belfoer1/Documents/oss-ui/node_modules/@pact-foundation/pact-node/standalone/darwin-1.88.77/pact/lib/vendor/ruby/2.2.0/gems/pact-mock_service-3.9.0/lib/pact/mock_service/run.rb:69:in `service_options'
	from /Users/belfoer1/Documents/oss-ui/node_modules/@pact-foundation/pact-node/standalone/darwin-1.88.77/pact/lib/vendor/ruby/2.2.0/gems/pact-mock_service-3.9.0/lib/pact/mock_service/run.rb:37:in `mock_service'
	from /Users/belfoer1/Documents/oss-ui/node_modules/@pact-foundation/pact-node/standalone/darwin-1.88.77/pact/lib/vendor/ruby/2.2.0/gems/pact-mock_service-3.9.0/lib/pact/mock_service/run.rb:28:in `call'
	from /Users/belfoer1/Documents/oss-ui/node_modules/@pact-foundation/pact-node/standalone/darwin-1.88.77/pact/lib/vendor/ruby/2.2.0/gems/pact-mock_service-3.9.0/lib/pact/mock_service/run.rb:13:in `call'
	from /Users/belfoer1/Documents/oss-ui/node_modules/@pact-foundation/pact-node/standalone/darwin-1.88.77/pact/lib/vendor/ruby/2.2.0/gems/pact-mock_service-3.9.0/lib/pact/mock_service/cli.rb:32:in `service'
	from /Users/belfoer1/Documents/oss-ui/node_modules/@pact-foundation/pact-node/standalone/darwin-1.88.77/pact/lib/vendor/ruby/2.2.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
	from /Users/belfoer1/Documents/oss-ui/node_modules/@pact-foundation/pact-node/standalone/darwin-1.88.77/pact/lib/vendor/ruby/2.2.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/belfoer1/Documents/oss-ui/node_modules/@pact-foundation/pact-node/standalone/darwin-1.88.77/pact/lib/vendor/ruby/2.2.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
	from /Users/belfoer1/Documents/oss-ui/node_modules/@pact-foundation/pact-node/standalone/darwin-1.88.77/pact/lib/vendor/ruby/2.2.0/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
	from /Users/belfoer1/Documents/oss-ui/node_modules/@pact-foundation/pact-node/standalone/darwin-1.88.77/pact/lib/app/pact-mock-service.rb:15:in `<main>'

[2021-11-04 15:02:52.080 +0000] WARN (97114 on MAC-CA-BELFOER2): pact-node@10.14.0: Pact exited with code 1.
[2021-11-04 15:02:52.080 +0000] INFO (97114 on MAC-CA-BELFOER2): pact-node@10.14.0: Removing Pact process with PID: 97235
```

### Steps to reproduce

given code:

```
// eslint-disable-next-line import/no-extraneous-dependencies
import { Pact } from '@pact-foundation/pact';
import path from 'path';
import config from '../src/config';

const { PACT_CONSUMER, PACT_PROVIDER, PORT } = config();

global.provider = new Pact({
  cors: true,
  consumer: PACT_CONSUMER,
  provider: PACT_PROVIDER,
  pactfileWriteMode: 'update',
  port: parseInt(PORT, 10),
  log: path.resolve(process.cwd(), 'pact/logs'),
  dir: path.resolve(process.cwd(), 'pact/pacts'),
  logLevel: 'info',
  spec: 2,
});
```

```
/* eslint jest/expect-expect: "off" */
import request from 'supertest';
import { Matchers } from '@pact-foundation/pact';
import express from 'express';
import signupRoutes from './signup-routes';

const app = express();

app.use(express.json());
app.use(express.urlencoded({ extended: false }));
app.use(signupRoutes);

const newAccountMock = {
  accountUuid: 'mock-hash',
  realm: 'mock',
  userUuid: 'mock-hash',
};

const account = {
  emailAddress: 'jhonPACT@company.com',
  password: 'myPWD@',
  firstName: 'jhon',
  lastName: 'PACT',
  customerName: 'company',
};

describe('pacts', () => {
  afterEach(() => global.provider.verify());
  describe('adding new customer', () => {
    it('should add a new customer', async () => {
      console.log('IT', global.provider.mockService);
      await global.provider.addInteraction({
        state: 'Add a new customer',
        uponReceiving: 'A request for API ',
        withRequest: {
          method: 'POST',
          path: '/signup',
          body: account,
        },
        willRespondWith: {
          status: 201,
          body: Matchers.eachLike(newAccountMock),
        },
      });
      await request(app)
        .post('/signup')
        .send(account)
        .set('Accept', 'application/json')
        .expect('Content-Type', /json/)
        .expect(201);
      console.log('am i here?????');
    });
  });
});
```

**Comment by mefellows** [comment]
The error looks to be complaining that the specified log file is actually already a directory

**Comment by erickbelfy** [comment]
So the script doesn't override the log files?

**Comment by erickbelfy** [comment]
After a couple hours of reading i found the pactfoundation/pact-broker docker and I was able to spin the service locally and after running the tests I have this console error:

```
console.error


      at ../../../../node_modules/@pact-foundation/src/httpPact.ts:145:17
      at tryCatcher (../../../../node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (../../../../node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (../../../../node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (../../../../node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (../../../../node_modules/bluebird/js/release/promise.js:725:18)
      at _drainQueueStep (../../../../node_modules/bluebird/js/release/async.js:93:12)
      at _drainQueue (../../../../node_modules/bluebird/js/release/async.js:86:9)

    console.error
      Pact verification failed!

      at ../../../../node_modules/@pact-foundation/src/httpPact.ts:146:17
      at tryCatcher (../../../../node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (../../../../node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (../../../../node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (../../../../node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (../../../../node_modules/bluebird/js/release/promise.js:725:18)
      at _drainQueueStep (../../../../node_modules/bluebird/js/release/async.js:93:12)
      at _drainQueue (../../../../node_modules/bluebird/js/release/async.js:86:9)

    console.error


      at ../../../../node_modules/@pact-foundation/src/httpPact.ts:147:17
      at tryCatcher (../../../../node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (../../../../node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (../../../../node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (../../../../node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (../../../../node_modules/bluebird/js/release/promise.js:725:18)
      at _drainQueueStep (../../../../node_modules/bluebird/js/release/async.js:93:12)
      at _drainQueue (../../../../node_modules/bluebird/js/release/async.js:86:9)

  ● signup pacts › adding new customer › should add a new customer

    Failed: ""

      44 |   afterAll(() => provider.finalize());
      45 |   describe('adding new customer', () => {
    > 46 |     test('should add a new customer', async () => {
         |     ^
      47 |       console.log('IT', provider.mockService);
      48 |       await provider.addInteraction({
      49 |         state: 'Add a new customer',

      at Env.it (../../../../node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:95:24)
      at Suite.<anonymous> (src/routes/api/signup-provider.pact.test.ts:46:5)
      at Suite.<anonymous> (src/routes/api/signup-provider.pact.test.ts:45:3)

  ● signup pacts › adding new customer › should add a new customer

    Failed: ""

      41 | describe('signup pacts', () => {
      42 |   beforeAll(() => provider.setup());
    > 43 |   afterEach(() => provider.verify());
         |   ^
      44 |   afterAll(() => provider.finalize());
      45 |   describe('adding new customer', () => {
      46 |     test('should add a new customer', async () => {

      at Env.afterEach (../../../../node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:46:24)
      at Suite.<anonymous> (src/routes/api/signup-provider.pact.test.ts:43:3)
      at Object.<anonymous> (src/routes/api/signup-provider.pact.test.ts:41:1)
```

**Comment by mefellows** [comment]
I'm a bit confused about what you're doing here.

You have express running in your consumer test. With Pact, you don't need to run your provider - Pact exists to mock the provider. The whole point is _not_ to have to run your provider when you test your consumer - see [how pact works](https://docs.pact.io/getting_started/how_pact_works).

The errors [here](https://github.com/pact-foundation/pact-js/issues/766#issuecomment-961409693) are because you aren't starting the Pact mock service. See our working [examples](https://github.com/pact-foundation/pact-js/tree/master/examples).

You might also like to run one of our tutorials to get a basic idea:

* in browser (15 mins): https://docs.pactflow.io/docs/workshops/tutorials
* full workshop (~1 hours):  https://github.com/pact-foundation/pact-workshop-js/ 

> So the script doesn't override the log files?

It does, but the argument accepts a path to a _file_ and not a _dir_. I think Pact is trying to write to a file, but you've specified a directory and it's failing because of that.

> After a couple hours of reading i found the pactfoundation/pact-broker docker image, I configured the docker-compose file and I was able to spin the service locally and after running the tests I have the following console error:

The Pact Broker doesn't run any tests, it's a contract repository (amongst other things). I'm not sure what you're trying to do with that?

**Comment by erickbelfy** [comment]
I am trying to understand the workflow and I clearly found it a bit confusing, but I will read all o the info you provided, thanks a lot for sharing!

**Comment by TimothyJones** [comment]
It looks like this one might not be a problem with Pact, so I'll close it for now. Please feel free to reopen it if you think there is something we can fix.
