### ISSUE TITLE
EISDIR error during plugin binary post install

### ISSUE THREAD

**Issue by crazycabo** [pact-foundation/pact-js#781]
### Software versions

- **OS**: MacOS 12.0.1 Monterey / Ubuntu AWS AMI 16.04 x64
- **Consumer Pact library**: Pact JS 9.16.5 / 9.17.0

### Issue Checklist

Please confirm the following:

- [x] I have upgraded to the latest
- [x] I have the read the FAQs in the Readme
- [x] I have triple checked, that there are **no unhandled promises** in my code and have [read](https://github.com/pact-foundation/pact-js/#test-fails-when-it-should-pass) the section on intermittent test failures
- [x] I have set my log level to debug and attached a log file showing the complete request/response cycle
- [ ] For bonus points and virtual high fives, I have created a reproducible git repository (see below) to illustrate the problem

### Expected behaviour

Pact binary downloads to default path.

### Actual behaviour

Download seems to fail because the plugin is trying to read a file, when it's actually a directory.

### Steps to reproduce

Simple NPM install before test execution. We've seen this hundreds of times locally and in our production Docker builds in AWS. The error thrown is difficult to decipher as the message does not indicate what it's accessing that causing a failure.

### Relevant log files

```
1669 info run @pact-foundation/pact-node@10.15.0 postinstall node_modules/@pact-foundation/pact-node node postinstall.js
1670 info run core-js@3.18.1 postinstall node_modules/core-js node -e "try{require('./postinstall')}catch(e){}"
1671 info run core-js-pure@3.18.1 postinstall node_modules/core-js-pure node -e "try{require('./postinstall')}catch(e){}"
1672 info run core-js@3.18.1 postinstall { code: 0, signal: null }
1673 timing build:run:postinstall:node_modules/core-js Completed in 62ms
1674 info run core-js-pure@3.18.1 postinstall { code: 0, signal: null }
1675 timing build:run:postinstall:node_modules/core-js-pure Completed in 57ms
1676 info run @pact-foundation/pact-node@10.15.0 postinstall { code: 1, signal: null }
1677 timing reify:rollback:createSparse Completed in 2646ms
1678 timing reify:rollback:retireShallow Completed in 41ms
1679 timing command:install Completed in 25794ms
1680 verbose stack Error: command failed
1680 verbose stack     at ChildProcess.<anonymous> (/Users/crazycabo350/.nvm/versions/node/v16.13.0/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
1680 verbose stack     at ChildProcess.emit (node:events:390:28)
1680 verbose stack     at maybeClose (node:internal/child_process:1064:16)
1680 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
1681 verbose pkgid @pact-foundation/pact-node@10.15.0
1682 verbose cwd /Users/crazycabo350/git_repos/term-plan-management
1683 verbose Darwin 21.1.0
1684 verbose argv "/Users/crazycabo350/.nvm/versions/node/v16.13.0/bin/node" "/Users/crazycabo350/.nvm/versions/node/v16.13.0/bin/npm" "i"
1685 verbose node v16.13.0
1686 verbose npm  v8.1.0
1687 error code 1
1688 error path /Users/crazycabo350/git_repos/term-plan-management/node_modules/@pact-foundation/pact-node
1689 error command failed
1690 error command sh -c node postinstall.js
1691 error Installing Pact Standalone Binary for darwin.
1691 error Downloading Pact Standalone Binary v1.88.80 for platform darwin from https://github.com/pact-foundation/pact-ruby-standalone/releases/download/v1.88.80/pact-1.88.80-osx.tar.gz
1692 error Error: Error while installing binary: Postinstalled Failed Unexpectedly: Error downloading binary from https://github.com/pact-foundation/pact-ruby-standalone/releases/download/v1.88.80/pact-1.88.80-osx.tar.gz: Error: Error while installing binary: Error: EISDIR: illegal operation on a directory, read
1692 error     at throwError (/Users/crazycabo350/git_repos/term-plan-management/node_modules/@pact-foundation/pact-node/standalone/install.js:42:11)
1692 error     at /Users/crazycabo350/git_repos/term-plan-management/node_modules/@pact-foundation/pact-node/standalone/install.js:335:16
1693 verbose exit 1
```

**Comment by mefellows** [comment]
Hi @crazycabo, it might relate to the fact that you're on the latest/greatest OSX version, which we don't test on (we use the default agents GH has that doesn't currently support arm/latest OSX).

I'm not sure how else that would be a directory and not a file, if not for some other unknown behaviour on that system.

There are related issues, but this one does seem different.

**Comment by crazycabo** [comment]
Well, here's the same error on one of the Ubuntu Docker containers we run builds on.

```14:03:41.628 -0500  + docker run --rm -v /home/ubuntu/.npmrc:/home/node/.npmrc -v /home/ubuntu/.npmrc:/home/node/.npmrc -v /home/ubuntu/workspace/erm-plan-management_build_master:/tmp/project docker.nextgearcapital.com/infrastructure/ngc-ui-builder:master_26_1f77c52
14:03:42.210 -0500  deleting /tmp/project/target
14:03:42.210 -0500  validating your project
14:03:42.210 -0500  	looking for /tmp/project/.git
14:03:42.210 -0500  	looking for /tmp/project/package.json
14:03:42.210 -0500  copying your project into ./copy
14:03:42.210 -0500  	project copied using command "rsync -ar --exclude=build --exclude=node_modules --exclude=.idea /tmp/project/ ./copy"
14:03:42.210 -0500  	working directory is now /opt/app/copy
14:03:42.210 -0500  Build project: START
14:03:42.210 -0500  	Execute npm with command ci
14:03:42.210 -0500  	Install dependencies
14:04:21.046 -0500  
14:04:21.046 -0500  > @pact-foundation/pact-node@10.14.0 postinstall /opt/app/copy/node_modules/@pact-foundation/pact-node
14:04:21.046 -0500  > node postinstall.js
14:04:21.046 -0500  
14:04:21.046 -0500  Installing Pact Standalone Binary for linux.
14:04:21.046 -0500  Downloading Pact Standalone Binary v1.88.77 for platform linux from https://github.com/pact-foundation/pact-ruby-standalone/releases/download/v1.88.77/pact-1.88.77-linux-x86_64.tar.gz
14:04:21.046 -0500  Error: Error while installing binary: Postinstalled Failed Unexpectedly: Error downloading binary from https://github.com/pact-foundation/pact-ruby-standalone/releases/download/v1.88.77/pact-1.88.77-linux-x86_64.tar.gz: Error: Error while installing binary: Error: EISDIR: illegal operation on a directory, read
14:04:21.046 -0500      at throwError (/opt/app/copy/node_modules/@pact-foundation/pact-node/standalone/install.js:42:11)
14:04:21.046 -0500      at /opt/app/copy/node_modules/@pact-foundation/pact-node/standalone/install.js:335:16
14:04:21.046 -0500  npm ERR! code ELIFECYCLE
14:04:21.046 -0500  npm ERR! errno 1
14:04:21.046 -0500  npm ERR! @pact-foundation/pact-node@10.14.0 postinstall: `node postinstall.js`
14:04:21.046 -0500  npm ERR! Exit status 1
14:04:21.046 -0500  npm ERR! 
14:04:21.046 -0500  npm ERR! Failed at the @pact-foundation/pact-node@10.14.0 postinstall script.```

**Comment by mefellows** [comment]
I'm sceptical. If this were the case it would be breaking a lot of builds right now. Do you have any corporate proxies/security systems installed that might be interfering?

**Comment by TimothyJones** [comment]
I'm able to install both 10.14.0 and 10.15.0 of pact-node without any issues. 

* Can you tell us more about your environment?
* Do you have a cached node_modules? Perhaps the cache is corrupt.
* Are you downloading the binary (the default), or providing it via custom `config` key in npm?
* Are you able to produce a repository or docker image that reproduces this problem outside your network? This will tell us if it is your network.

```
npm i @pact-foundation/pact-node@10.14.0

> @pact-foundation/pact-node@10.14.0 postinstall /Users/home/office/test/node_modules/@pact-foundation/pact-node
> node postinstall.js

Installing Pact Standalone Binary for darwin.
Downloading Pact Standalone Binary v1.88.77 for platform darwin from https://github.com/pact-foundation/pact-ruby-standalone/releases/download/v1.88.77/pact-1.88.77-osx.tar.gz
Please note: we are tracking this download anonymously to gather important usage statistics. To disable tracking, set 'pact_do_not_track: true' in your package.json 'config' section.
Downloaded 0.02%...
Downloaded 10.63%...
Downloaded 50.25%...
Downloaded 93.47%...
Finished downloading binary to /Users/home/office/test/node_modules/@pact-foundation/pact-node/standalone/pact-1.88.77-osx.tar.gz
Extracting binary from /Users/home/office/test/node_modules/@pact-foundation/pact-node/standalone/pact-1.88.77-osx.tar.gz.
Checksum passed for 'pact-1.88.77-osx.tar.gz'.
Extraction done.


### If you ❤ Pact and want to support us, please donate here: http://donate.pact.io/node


Pact Standalone Binary is ready.
```

**Comment by TimothyJones** [comment]
@crazycabo What was the fix?
