### ISSUE TITLE
The pact mock service doesn't appear to be running (on mac, works fine on windows)

### ISSUE THREAD

**Issue by akshay-nm** [pact-foundation/pact-js#860]
I am facing the same issue as mentioned in https://github.com/pact-foundation/pact-js/issues/383
I have gone through it and the solutions mentioned there don't work for me. 
I've tried setting up the jest timeout to 30000 but I am still receiving the same error.
My `pact.log` file is empty.

Here is my setup.js file contents:

```
import "isomorphic-fetch";
import chai from "chai";

const path = require("path");
const Pact = require("@pact-foundation/pact").Pact;

// jest.setTimeout(30000);

global.port = 7000;
global.jestExpect = global.expect;
global.expect = chai.expect;
global.provider = new Pact({
  cors: true,
  port: global.port,
  log: path.resolve(process.cwd(), "logs", "pact.log"),
  loglevel: "debug",
  dir: path.resolve(process.cwd(), "pacts"),
  spec: 2,
  pactfileWriteMode: "update",
  consumer: "storefront",
  provider: "api",
  host: "127.0.0.1",
});
```

These are my logs: 
```
yarn run v1.22.15
$ cross-env CI=true react-scripts test --runInBand --setupFiles ./pact/setup.js --setupFilesAfterEnv ./pact/jest-wrapper.js --testMatch "**/*.pact.test.js"
[2022-04-12 12:34:22.261 +0000] INFO (5625 on mac.local): pact-node@10.17.2: Creating Pact Server with options: 
{"timeout":30000,"consumer":"storefront","cors":true,"dir":"/Users/akshay-nm/projects/restobazaar/storefront/pacts","host":"127.0.0.1","log":"/Users/akshay-nm/projects/restobazaar/storefront/logs/pact.log","logLevel":"INFO","pactfileWriteMode":"update","provider":"api","spec":2,"ssl":false,"port":7000,"loglevel":"debug","pactFileWriteMode":"overwrite"}
  console.log
    Setup file loaded

      at Object.<anonymous> (pact/setup.js:29:9)

[2022-04-12 12:34:27.842 +0000] ERROR (5625 on mac.local): pact@9.17.3: The pact mock service doesn't appear to be running
  - Please check the logs above to ensure that there are no pact service startup failures
  - Please check that pact lifecycle methods are called in the correct order (setup() needs to be called before this method)
  - Please check that your test code waits for the promises returned from lifecycle methods to complete before calling the next one
  - To learn more about what is happening during your pact run, try setting logLevel: 'DEBUG'
FAIL src/app/tests/menu-items/get-all.menu-items.pact.test.js (12.688 s)
  ● Get all menu-items › given there are menu-items › when a call to the API is made › will receive the list of menu-items

    thrown: "Exceeded timeout of 5000 ms for a hook.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

    > 1 | beforeAll((done) => {
        | ^
      2 |   global.provider.setup().then(() => done());
      3 | });
      4 |

      at Object.<anonymous> (pact/jest-wrapper.js:1:1)
      at TestScheduler.scheduleTests (node_modules/@jest/core/build/TestScheduler.js:333:13)
      at runJest (node_modules/@jest/core/build/runJest.js:404:19)
      at _run10000 (node_modules/@jest/core/build/cli/index.js:320:7)
      at runCLI (node_modules/@jest/core/build/cli/index.js:173:3)


  ● Test suite failed to run

    Port 7000 is unavailable on address 127.0.0.1

      at Server.<anonymous> (node_modules/@pact-foundation/src/common/net.ts:44:18)

  ● Test suite failed to run

    The pact mock service wasn't running when finalize was called

      4 |
      5 | afterAll((done) => {
    > 6 |   global.provider.finalize().then(() => done());
        |                   ^
      7 | });
      8 |

      at Pact.finalize (node_modules/@pact-foundation/src/httpPact.ts:183:9)
      at pact/jest-wrapper.js:6:19
      at TestScheduler.scheduleTests (node_modules/@jest/core/build/TestScheduler.js:333:13)
      at runJest (node_modules/@jest/core/build/runJest.js:404:19)
      at _run10000 (node_modules/@jest/core/build/cli/index.js:320:7)
      at runCLI (node_modules/@jest/core/build/cli/index.js:173:3)

  ● Test suite failed to run

    thrown: "Exceeded timeout of 5000 ms for a hook.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      3 | });
      4 |
    > 5 | afterAll((done) => {
        | ^
      6 |   global.provider.finalize().then(() => done());
      7 | });
      8 |

      at Object.<anonymous> (pact/jest-wrapper.js:5:1)
      at TestScheduler.scheduleTests (node_modules/@jest/core/build/TestScheduler.js:333:13)
      at runJest (node_modules/@jest/core/build/runJest.js:404:19)
      at _run10000 (node_modules/@jest/core/build/cli/index.js:320:7)
      at runCLI (node_modules/@jest/core/build/cli/index.js:173:3)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        14.159 s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Software versions

_Please provide at least OS and version of pact-js_

- **OS**: Mac OS 11.6
- **Consumer Pact library**: @pact-foundation/pact@9.17.3
- **Provider Pact library**: -
- **Node Version**: 16.9.1

**Comment by YOU54F** [comment]
Hey dude,

Could you try the debugging steps and report back

https://github.com/pact-foundation/pact-js#debugging

or try `find . -name pact-mock-service`

**Comment by mefellows** [comment]
>     thrown: "Exceeded timeout of 5000 ms for a hook.

This is often an indicator of a slow startup - you might want to increase your test timeout to see if it helps. 

But the debugging steps above will also be helpful.

**Comment by YOU54F** [comment]
Just noticed you are using chai, and overwriting expect, that comes from jest which is packaged with react-scripts? Not noticed that setup before. Anyway your jest timeout won't have any impact on your chai settings? Do you need a chai expect timeout


We built [jest-pact](https://github.com/pact-foundation/jest-pact) to make it an easier experience for jest users wishing to use pact

**Comment by akshay-nm** [comment]
I removed chai, and I just pulled the tests which are working on my windows PC. 
I am sharing what I have right now: 

`setup.js`
```
require("isomorphic-fetch");
const path = require("path");
const Pact = require("@pact-foundation/pact").Pact;

global.port = 7000;
global.provider = new Pact({
  cors: true,
  port: global.port,
  log: path.resolve(process.cwd(), "logs", "pact.log"),
  loglevel: "debug",
  dir: path.resolve(process.cwd(), "pacts"),
  spec: 2,
  pactfileWriteMode: "update",
  consumer: "storefront",
  provider: "api",
  host: "127.0.0.1",
});

```

My provider: 
```
const provider = new Pact({
  consumer: "storefront",
  provider: "api",
  log: path.resolve(process.cwd(), "logs", "pact.log"),
  logLevel: "debug",
  dir: path.resolve(process.cwd(), "pacts"),
  spec: 2,
  pactfileWriteMode: "update",
  host: "127.0.0.1",
  port: 7000,
});

```

here is my addIntegration step in each test: 
```
await provider.addInteraction({
          state: "there are menu items",
          uponReceiving: "a request for all menu items",
          withRequest: {
            ... 
          },
          willRespondWith: {
            ...
          },
        });
```
This is what I get when I run `find . -name pact-mock-service`:
```
./node_modules/.bin/pact-mock-service
./node_modules/@pact-foundation/pact-node/standalone/darwin-1.88.83/pact/bin/pact-mock-service
./node_modules/@pact-foundation/pact-node/standalone/darwin-1.88.83/pact/lib/vendor/ruby/2.2.0/bin/pact-mock-service
./node_modules/@pact-foundation/pact-node/standalone/darwin-1.88.83/pact/lib/vendor/ruby/2.2.0/gems/pact-mock_service-3.9.0/bin/pact-mock-service
./node_modules/@pact-foundation/pact/node_modules/.bin/pact-mock-service
```

**Comment by akshay-nm** [comment]
> > ```
> > thrown: "Exceeded timeout of 5000 ms for a hook.
> > ```
> 
> This is often an indicator of a slow startup - you might want to increase your test timeout to see if it helps.
> 
> But the debugging steps above will also be helpful.

I tried setting timeout to 30000 and still no change in the result.

**Comment by YOU54F** [comment]
Hey, 

It's always easier to help when you show full code snippets or even better, a repo in action. I can't see half your setup, which makes diagnosing tricky 

We have several examples where you can see it in action

https://github.com/pact-foundation/pact-js/tree/master/examples
https://github.com/pactflow/example-consumer/tree/master/src

The mock verifier is installed which is good, but no calls are reaching it. 

Can you show how you are setting the timeout now?

Also why are polyfilling fetch? is your client code using a fetch method and the polyfill is required for running your tests in a node env?

**Comment by YOU54F** [comment]
Also as this works on windows, is your mac M1 arch? Are you running your terminal in Rosetta mode?

**Comment by mefellows** [comment]
> I tried setting timeout to 30000 and still no change in the result.

Yes, but the timeout you have shown still says 5000ms so don't think it has properly taken effect.

I'd you can provide a reproducible example we can download and run that would be ideal.

**Comment by TimothyJones** [comment]
>     Port 7000 is unavailable on address 127.0.0.1

Is there something running on port 7000?

Sometimes pact is still running in the background if a test aborts without running the teardown in an earlier run. You can check with `ps aux | grep ruby`

**Comment by KlausKer** [comment]
@akshay-nm 

I faced the same problems when i tried running jest-pact with jest 28.x.x

Down grading to jest ^26.6.3 solved that.

**Comment by mefellows** [comment]
I'm going to close this off as there is no current way to reproduce this problem. If it can be demonstrated (ideally as a github example that runs on Windows showing the problem) please re-open so we can take a look.
