### ISSUE TITLE
pactjs 10.0.0-beta.59 tests fail on SLES 15 [CI]

### ISSUE THREAD

**Issue by schowave** [pact-foundation/pact-js#864]
### Software versions

_Please provide at least OS and version of pact-js_

- **OS**:SUSE Linux Enterprise Server 15
- **Consumer Pact library**: 10.0.0-beta.59
- **Node Version**: 16.15.0

### Issue Checklist

Please confirm the following:

- [X] I have upgraded to the latest
- [X] I have the read the FAQs in the Readme
- [X] I have triple checked, that there are **no unhandled promises** in my code and have [read](https://github.com/pact-foundation/pact-js/#test-fails-when-it-should-pass) the section on intermittent test failures
- [X] I have set my log level to debug and attached a log file showing the complete request/response cycle
- [ ] For bonus points and virtual high fives, I have created a reproduceable git repository (see below) to illustrate the problem

### Expected behaviour

pacttests execute successfully and contracts are generated

### Actual behaviour

Pacttests fail with the following message

```
    /lib64/libc.so.6: version `GLIBC_2.29' not found (required by /XXX/frontend/node_modules/.pnpm/@pact-foundation+pact-core@13.6.0/node_modules/@pact-foundation/pact-core/build/Release/libpact_ffi.so)

      at Runtime._loadModule (node_modules/.pnpm/jest-runtime@27.5.1/node_modules/jest-runtime/build/index.js:1180:29)
      at bindings (node_modules/.pnpm/bindings@1.5.0/node_modules/bindings/bindings.js:112:48)
      at Object.<anonymous> (node_modules/.pnpm/@pact-foundation+pact-core@13.6.0/node_modules/@pact-foundation/pact-core/src/ffi/index.ts:6:21)
```

Did something change here, because with version 10.0.0-beta.54 it was still working. Locally on our windows/mac system this works perfectly! It seems that the pact-core requirements changed... Is there a possibility to provide a workaround here?

**Comment by schowave** [comment]
This is an issue with the build server. There is ServicePack 3 with glibc 2.31 available, but not installed.... While fixing that the build should work again...
